### ISSUE TITLE
Unsure how to access entire Access Token

### ISSUE THREAD

**Issue by JevVan** [jaredhendrickson13/pfsense-api#103]
I'd prefer to use the Access Token method for auth.  However, when I generate the token, the resulting token is truncated in the GUI and only displays about 20 characters followed by ...    .   How do I get the full access token?   My first issue post on git ever, and I don't know that there is actually an issue other than my ability to figure it out.   Thanks for your help!

**Comment by jaredhendrickson13** [comment]
Hey!

The`client-token` is only shown once after it is generated. It will be displayed on the confirmation banner towards the top of the page (shown below). The entire token will be displayed here. The token should be copied and stored somewhere safe. Once that banner is dismissed, the page reloads, etc. you cannot view the token again. The API does not store the actual token in the config, rather a hash of the token is stored which I believe is what you are seeing.  The `client-id` however, will be displayed within the UI as it is not considered sensitive. 

![Screen Shot 2021-03-12 at 8 57 40 AM](https://user-images.githubusercontent.com/50180862/110966909-06679100-8313-11eb-83e7-ab0e20b33f99.png)

Hope this helps. Let me know if you have any issues. 

Thanks!

**Comment by JevVan** [comment]
That's it!    I think I was focusing on the bottom and never noticed that banner.  Thanks!
