### ISSUE TITLE
Please add this to the readme.md documentation

### ISSUE THREAD

**Issue by KaiSoelter** [jaredhendrickson13/pfsense-api#104]
Please add this to the readme.md documentation

Under Authorization

To pass the credentials add an Authorization-Header containing  
- user/pass when using local database
- clientid/token when using API Token. (token from one-time banner, not the token hash)
separated by **SPACES** without a type

Like so
curl -k -X GET -H "Authorization: user pass" -H "Content-Type: application/json" -d "{\"interface\": \"lan\"}" "https://<hostname>/api/v1/services/dhcpd/static_mapping"

curl -k -X GET -H "Authorization: clientid token" -H "Content-Type: application/json" -d "{\"interface\": \"lan\"}" "https://<hostname>/api/v1/services/dhcpd/static_mapping"

Thank you

**Comment by jaredhendrickson13** [comment]
Hey!

Thanks for reaching out. These are already documented in the README.md under the [Authentication & Authorization section](https://github.com/jaredhendrickson13/pfsense-api#authentication--authorization). There are collapsable menus for each API authentication type (e.g. Local Database, JWT, API Token) that contain the details for authenticating using each type. The authorization sub-section only applies to permissions required by clients _after_ authenticating. 

Thanks!

**Comment by KaiSoelter** [comment]
Yikes! Stupid me. I am sorry.
