### ISSUE TITLE
Unable to update this api with pfsense 2.5.0

### ISSUE THREAD

**Issue by h-medjahed** [jaredhendrickson13/pfsense-api#107]
When we try to update we get the following error:
pkg add https://github.com/jaredhendrickson13/pfsense-api/releases/latest/download/pfSense-2.4-pkg-API.txz && /etc/rc.restart_webgui
Fetching pfSense-2.4-pkg-API.txz: 100%  181 KiB 185.0kB/s    00:01
Installing pfSense-pkg-API-1.1_7...
**pkg: wrong architecture: FreeBSD:11:amd64 instead of FreeBSD:12:amd64
Failed to install the following 1 package(s): https://github.com/jaredhendrickson13/pfsense-api/releases/latest/download/pfSense-2.4-pkg-API.txz**

**Comment by jaredhendrickson13** [comment]
Hey! 

Looks like you are installing the package built for pfSense 2.4. Change the install command to pull the 2.5 build instead:

`pkg add https://github.com/jaredhendrickson13/pfsense-api/releases/latest/download/pfSense-2.5-pkg-API.txz && /etc/rc.restart_webgui`

Let me know if you have any further issues. 

Thanks!

**Comment by h-medjahed** [comment]
Thanks it works
