### ISSUE TITLE
Wish: Please include DNS Forwarder -> Host Overides

### ISSUE THREAD

**Issue by KaiSoelter** [jaredhendrickson13/pfsense-api#109]
I wish for a feature to update the IP-adresses of host overrides in pfsense on 
Services -> DNS Forwarder -> Host Overides (services_dnsmasq.php)  
and subsequently apply the changes.

**Comment by jaredhendrickson13** [comment]
Hey!

Thanks for your patience. I have these features now implemented in the v1.3.0 beta build. The command to install the beta build is in #115. Feel free to install the beta and try it out. If there's anything missing or not working as expected please let me know. 

Thanks again!

**Comment by KaiSoelter** [comment]
Hey!
Thank you very much. So Nice.

**Comment by KaiSoelter** [comment]
Works fine for the DNS Resolver. Nice. Thank you.
Does not work for DNS Forwarder. Those settings are separte.

**Comment by jaredhendrickson13** [comment]
Are you using the correct endpoints for each on v1.3.0beta?

For DNS Resolver host overrides the endpoint will be `/api/v1/services/unbound/host_override`

For DNS Forwarder host overrides the endpoint will be `/api/v1/services/dnsmasq/host_override`

**Comment by KaiSoelter** [comment]
Sorry. That was my fault. I was unable to get .130 on my pfsense textbox.
I will test this feature when it is in the main release

**Comment by degas2226** [comment]
Hi Jared,

I don't see beta package for 2.4 version of pfsense. Is this not supported for 2.4?
