### ISSUE TITLE
Alias in Alias Entry

### ISSUE THREAD

**Issue by notyettested** [jaredhendrickson13/pfsense-api#112]
im working extensively with  having Host aliasses in Group Aliasses. but when i try to either use POST to create a new Alias or PUT to update one i get the following: {'status': 'bad request', 'code': 400, 'return': 4058, 'message': 'Invalid firewall alias IP address or hostname', 'data': []}

is it not possible to use Aliasnames instead of Hostnames or IP Adresses or do i have to use some other Method?

**Comment by jaredhendrickson13** [comment]
Hey!

Currently it's not possible. I actually wasn't aware pfSense supported this so thanks for bringing it up. Luckily, adding this feature is a non-disruptive change so it can be included in the next patch. I'll work on this and update this issue when I have a PR containing the feature.

Thanks again!

**Comment by notyettested** [comment]
Hi,

thanks for the fast Reply! i´ll try it out as soon as its available.

im currently working on a python client to feed our 4+ PFSense Servers the same information simultaniously. was a small setback to see it not working with nested Aliasses yet.

**Comment by jaredhendrickson13** [comment]
I have a beta build for v1.2.1 that includes this feature. The command to install the beta build is available in #113. You're welcome to install the beta build and try it out, if there's anything missing or not working as expected please let me know. 

Thanks!

**Comment by notyettested** [comment]
tested it out, works like a Charm!
