### ISSUE TITLE
Can't add ipalias on carp interfaces

### ISSUE THREAD

**Issue by beavis69** [jaredhendrickson13/pfsense-api#117]
Hello,

It seems we cant create ipalias on carp interface.

POST v1/firewall/virtual_ip         "mode": "ipalias", "interface": "_vip6037c85eb2926", "subnet": "10.1.1.255/32", "descr": ""
{"status":"bad request","code":400,"return":4024,"message":"Unknown virtual IP interface","data":[]}

It seems that function get_pfsense_if_id can't validate carp interfaces.

**Comment by jaredhendrickson13** [comment]
Hey!

Thanks for your time on this. Your PR looks great, give me a couple days to review and test the behavior of this change throughout other components of the API. If I have any questions or any changes are needed I'll be sure to relay that information within the PR. 

Thanks!

**Comment by beavis69** [comment]
Thanks for your time too ! :+1: 

I've made more tests and i think you can remove the test is_carp_enabled() , because in some case you need to add ipalias even if carp is temporarily disabled.

The only side effects i've seen is that carp events are being sent between nodes when adding ipalias on carp interfaces, but it's not related to the api.

Thanks !
