### ISSUE TITLE
Get /api/v1/services/dhcpd/lease returns nothing

### ISSUE THREAD

**Issue by grillp** [jaredhendrickson13/pfsense-api#119]
Versions:
PfSense: `2.5`
pfsense API: `pfSense-2.5-pkg-API.txz`

When I call the `/api/v1/services/dhcpd/lease` endpoint it returns:

`{"status":"ok","code":200,"return":0,"message":"Success","data":[]}`

But no data. 

I checked the source code and see that it reads `/var/dhcpd/var/db/dhcpd.leases`.

I checked the file and it contains the lease data, but it looks like it is not being processed. 

Documentation also says it returns nothing 🤷🏻‍♂️

Is it not implemented fully or a bug?

**Comment by jaredhendrickson13** [comment]
Hey!

This endpoint seems to be working for me on 2.5. Do any leases show up in the Status > DHCP Leases page within the UI? If there are no leases there, an empty data array returned by the API would be expected. Another possibility is that the leases file is formatted in a way that is not recognized by the API, a scrubbed copy of dhcpd.leases file would be helpful for debugging in that case. Lastly, ensure you are not passing any extra parameters (anything other than authentication parameters) to the endpoint. Extra parameters will trigger an API query to filter the return data for specific criteria, if that criteria is not matched an empty data array will be returned. 

When I call this endpoint with no leases I receive:
```shell
curl -s -k -d '{"client-id": "admin", "client-token": "pfsense"}' -X GET https://localhost/api/v1/services/dhcpd/lease
```
```json
{
    "status":"ok",
    "code":200,
    "return":0,
    "message":"Success",
    "data":[]
}
```

When I call this endpoint after registering DHCP leases I receive:
```shell
curl -s -k -d '{"client-id": "admin", "client-token": "pfsense"}' -X GET https://localhost/api/v1/services/dhcpd/lease | jq .
```
```json
{
  "status": "ok",
  "code": 200,
  "return": 0,
  "message": "Success",
  "data": [
    {
      "state": "active",
      "ip": "192.168.1.50",
      "mac": "65:9d:99:17:71:2c",
      "starts": "2021/04/03 13:08:52",
      "ends": "2021/04/03 15:08:52",
      "hostname": "",
      "online": true
    },
    {
      "state": "active",
      "ip": "192.168.1.54",
      "mac": "3c:ce:69:91:d8:b1",
      "starts": "2021/04/03 13:10:56",
      "ends": "2021/04/03 15:10:56",
      "hostname": "test",
      "online": true
    }
  ]
}
```

**Comment by grillp** [comment]
Yep, that appears to be the case! Looks like I had some lingering parameters on the CLI that I left in.

Sorry. You can close this reqissue.

G./

**Comment by jaredhendrickson13** [comment]
No worries! Glad that's all it was. 

Thanks!
