### ISSUE TITLE
Add documentation on how to use the API

### ISSUE THREAD

**Issue by HeLiBloks** [jaredhendrickson13/pfsense-api#12]
Please add some one liners on how to use the api with curl
Im kind of stuck at:
```bash
curl -X GET 'https://pfsense/api/v1/system/api/' -d '{"client-id": "rufus", "client-token": "baghera"}' | jq '.'    
```

**Comment by jaredhendrickson13** [comment]
Hi there,

Current documentation is at https://documenter.getpostman.com/view/9873986/TVCZZVsG

This will include examples using the HTTP client of your choice (E.g. curl, Python requests, etc.)

Also, the next release v0.0.4 will be distributed with documentation embedded within the UI to make things easier to learn. That should be available in the coming weeks. 

Let me know if you have any troubles. 

Thanks!

**Comment by ozrouter** [comment]
Same here, I don't see a full example, ie:

curl --location --request POST 'https://{{$hostname}}/api/v1/firewall/rules/delete/' \
--data-raw '{
	"id": 0
}'

how is the client id/token added?

**Comment by ozrouter** [comment]
Same here, from the docs I don't see a full example, ie:

curl --location --request GET 'https://cd.pfsense/api/v1/firewall/rules/' --data-raw '"client-id": "admin","client-token": "pfsense"'

running this does nothing
