### ISSUE TITLE
Invalid priviledge name in docs and code for 'page-firewall-alias-edit' 

### ISSUE THREAD

**Issue by grillp** [jaredhendrickson13/pfsense-api#122]
pfSense 2.5.0
pfsense-api: pfSense-2.5-pkg-API.txz

I want to create an API user that has least-privilege access to the API's it needs. In this case a user for updating Firewall Aliases.

Reading the documentation `/api/v1/firewall/alias/entry` and `/api/v1/firewall/alias/entry` POST/PUT/DELETE it mentions that user needs the `page-firewall-aliases-edit` privilege.

Similarly the code ([one example here](https://github.com/jaredhendrickson13/pfsense-api/blob/23b1054d4e26c9e84170ad386093ad2101e6963f/pfSense-pkg-API/files/etc/inc/api/models/APIFirewallAliasUpdate.inc#L26)) indicates the same `page-firewall-aliases-edit` privilege.

However, if I try and add that privilege to a user using the API I get an `Unknown user privilege` error message:
```
>  curl  -k -s -H "Content-Type: application/json" -d '{"client-id": "admin", "client-token": "xxx", "username": "api", "priv": "page-firewall-aliases-edit"}' -X POST https://pfsense.home/api/v1/user/privilege
{"status":"bad request","code":400,"return":5006,"message":"Unknown user privilege","data":[]}
```

If I use the WebConfigurator to give the user the privilege `WebCfg - Firewall: Alias: Edit` and query the user using the API, it shows as `page-firewall-alias-edit`.
```
curl  -k -s -H "Content-Type: application/json" -d '{"client-id": "admin", "client-token": "xxx"}' -X GET https://pfsense.home/api/v1/user | jq
{
  "status": "ok",
  "code": 200,
  "return": 0,
  "message": "Success",
  "data": [
    {
      "name": "admin",
...
      "uid": "0",
      "priv": [
        "user-shell-access"
      ]
    },
    {
      "scope": "user",
...
      "name": "api",
      "priv": [
        "page-system-api",
        "page-status-dhcpleases",
        "page-firewall-aliases",
        "page-firewall-alias-edit"
      ]
    }
  ]
}
```

Is this a bug? Has the privilege name changed in 2.5? Should it be `page-firewall-alias-edit` instead of `page-firewall-aliases-edit`?

**Comment by grillp** [comment]
I searched the source code of [pfsense](https://github.com/pfsense/pfsense) to find the relevant privilege codes and only found hits for [page-firewall-alias-edit](https://github.com/pfsense/pfsense/search?q=page-firewall-alias-edit&type=code) and not for [page-firewall-aliases-edit](https://github.com/pfsense/pfsense/search?q=page-firewall-aliases-edit&type=code), which would indicate my suspicion is correct.

**Comment by grillp** [comment]
Also If I try and use the `/api/v1/firewall/alias` API to create (PUT) a new alias using the user that has the correct `page-firewall-alias-edit` privilege, I get an `Authorization failed` response:
```
curl  -k -s -H "Content-Type: application/json" -d '{"client-id": "api", "client-token": "api", "name": "APITEST"}' -X POST https://pfsense.home/api/v1/firewall/alias | jq
{
  "status": "forbidden",
  "code": 403,
  "return": 4,
  "message": "Authorization failed",
  "data": []
}
```

**Comment by grillp** [comment]
I have created a pull request to fix the issue: https://github.com/jaredhendrickson13/pfsense-api/pull/123

**Comment by jaredhendrickson13** [comment]
Good catch, you are correct. I'll review the pull request and merge this in today. 

Thanks!
