### ISSUE TITLE
405 Not allowed 

### ISSUE THREAD

**Issue by caspertl** [jaredhendrickson13/pfsense-api#126]
Hi.

Following your documentation, I get a 405 Not allowed when trying to do the following request:

`[DELETE] /api/v1/firewall/alias/`.

```
<html>
<head>
	<title>405 Not Allowed</title>
</head>
<body>
	<center>
		<h1>405 Not Allowed</h1>
	</center>
	<hr>
	<center>nginx</center>
</body>
</html>
```

It is also unclear if you expect the "id" as a query-param or request body. But I've tried them both.

![image](https://user-images.githubusercontent.com/14234358/114560656-2d481880-9c6d-11eb-94f9-fe5b924f7cbc.png)

**Comment by jaredhendrickson13** [comment]
Hey!

The response you're receiving typically occurs if the webConfigurator service is not restarted after installing the API. The API makes some modifications to the NGINX service for PUT and DELETE requests to work. You can run `/etc/rc.restart_webgui` from the command line to restart the webConfigurator. 

As far as the request, you can either submit the data as URL encoded query parameters or a JSON body. JSON is the recommended content type as it supports all the necessary typing the API expects.

Hopefully this helps. Let me know if you have any further issues. 

Thanks!

**Comment by caspertl** [comment]
> Hey!
> 
> The response you're receiving typically occurs if the webConfigurator service is not restarted after installing the API. The API makes some modifications to the NGINX service for PUT and DELETE requests to work. You can run `/etc/rc.restart_webgui` from the command line to restart the webConfigurator.
> 
> As far as the request, you can either submit the data as URL encoded query parameters or a JSON body. JSON is the recommended content type as it supports all the necessary typing the API expects.
> 
> Hopefully this helps. Let me know if you have any further issues.
> 
> Thanks!

Hi! Thank you very much for the prompt reply. Restarting the webConfigurator did not solve the PUT/DELETE issues. However, I realized that my pfSense was running an older version. I updated to the latest version + updated the pfSense API to the latest version and now it works perfectly. 👍
