### ISSUE TITLE
Issue: [DHCPd] Static ARP Table is not loaded automatically after modification 

### ISSUE THREAD

**Issue by top-infra** [jaredhendrickson13/pfsense-api#129]
Hello,

It seems that the static ARP table binding is not loaded automatically with the reload of dhcp service. 
Instead, it is related to the interface changes. 

So the bind reload is not enough for this change (Static ARP Table). A /etc/rc.reload_interfaces is needed.

**Comment by jaredhendrickson13** [comment]
Hey!

Thanks for reporting this issue. I'll take a look at this further and implement fixes where needed within the next patch.

Thanks again!

**Comment by jaredhendrickson13** [comment]
I had some time today to look at this but couldn't seem to replicate. Perhaps I'm misunderstanding the issue. Are you referring to the DHCP static mappings not assigning a static ARP entry with the `arp_table_static_entry` field set to `true`? Perhaps some screenshots or steps to reproduce the issue would be helpful.

Thanks!

**Comment by top-infra** [comment]
Thanks for reply and above all thanks for this elegant api interface.
What I want to simulate is something like 802.1x at the router level. So the static ARP map control is a good candidate
The LAN member who has a unknown MAC cannot communicate to router. It is not a question about request dhcp service,
The option name is: Enable Static ARP entries

Now the issue:
Let's assume that my machine A has a Mac X which is not in the static ARP map
- If I use Pfsense WebGui to add a static map of Mac X => OK, Machine A can ping router
- If I use API to add a static map of Mac X => KO. Machine A cannot ping router. To make it work, I must call manually another API -> reload interface. 

ARP Static MAP for IP release works perfect, there is no issue

**Comment by jaredhendrickson13** [comment]
Sorry for wait on this one. I've looked through the pfSense code pretty thoroughly and don't see any calls to `reload_interfaces()` or `reload_interfaces_sync()` on the DHCP Server pages. I'm hesitant to add a call to either of those functions as they may cause unexpected behavior for some users. The only reloads I am seeing are the ones currently present on the API endpoint. I have however added the `staticarp` field to the /api/v1/services/dhcpd endpoint in #184. This will allow you to  interact with this field as necessary and if you still experience this issue, my recommendation is to immediately make a call to /api/v1/diagnostics/command_prompt afterwards to initiate `/etc/rc.reload_interfaces`. I'll keep a note of this issue in the codebase going forward to re-evaluate as changes are made to pfSense and the API. 

Thanks!
