### ISSUE TITLE
Firewall Rule Doesn't get applied when including pdnpipe

### ISSUE THREAD

**Issue by sowri1** [jaredhendrickson13/pfsense-api#132]
We are trying to include traffic limiters with the firewall rule through API. 
When trying to include the pdnpipe  in the request body, we receive 
`{"status":"bad request","code":400,"return":4225,"message":"Firewall rule dnpipe and pdnpip queue and a virtual interface cannot be selected","data":[]}`
The request body is 
`
{'apply': True,
 'descr': 'xxxxxx',
 'dnpipe': 'up_pipe',
 'dst': 'any',
 'interface': 'lan',
 'ipprotocol': 'inet',
 'pdnpipe': 'down_pipe',
 'protocol': 'any',
 'src': '<firewall-alias>',
 'statetype': 'keep state',
 'type': 'pass'}
`
But when removing the pdnpipe, it worked except that we could not limit the download speed. But when updating the firewall from web interface and selecting the download pipe, it worked. And we also tried retrieving the firewall rule from the API after updating from the web-interface, it showed the same data (with pdnpipe being present). We tried updating the firewall rule with pdnpipe, even then it throws the same error.

PfSense-ver: 2.5.1
pfSense-pkg-API-ver: 1.2_2

**Comment by jaredhendrickson13** [comment]
Hey!

Thanks for reporting this issue. Could you include the configuration for the `up_pipe` and `down_pipe` limiters? That will help me locate any logic error there may be causing this. The API seems to think they are of incompatible types which is why that response is being given.

Thanks again!

**Comment by sowri1** [comment]
The configuration for the up_pipe and down_pipe limters
`
data = {
	"name": <filter_name (up or down)>,
	"bandwidth": [
		{
			"bw": speed,
			"bwscale": "Mb"
		}
	],
	"description": description,
	"apply": true,
	"aqm": "gred",
	"sched": "wf2q+",
}
`

**Comment by nicolapiazzi** [comment]
Hi,
Also modifiing same problem, is possible only to put dnpipe value
pdnpipe have error also if called separately

 curl -s -H "Content-Type: application/json" -d '{"client-id": "admin", "client-token": "password", "tracker": "1620915610", "pdnpipe": "d014"}' -X PUT http://pfwan.munetwork.it/api/v1/firewall/rule

{"status":"bad request","code":400,"return":4225,"message":"Firewall rule dnpipe and pdnpip queue and a virtual interface cannot be selected","data":[]}

thanks Nicola

**Comment by sowri1** [comment]
> Hi,
> Also modifiing same problem, is possible only to put dnpipe value
> pdnpipe have error also if called separately
> 
> curl -s -H "Content-Type: application/json" -d '{"client-id": "admin", "client-token": "password", "tracker": "1620915610", "pdnpipe": "d014"}' -X PUT http://pfwan.munetwork.it/api/v1/firewall/rule
> 
> {"status":"bad request","code":400,"return":4225,"message":"Firewall rule dnpipe and pdnpip queue and a virtual interface cannot be selected","data":[]}
> 
> thanks Nicola

**Comment by nicolapiazzi** [comment]
Why closed the issue ?

**Comment by sowri1** [comment]
> Why closed the issue ?

I closed the issue by mistake... thanks for mentioning.
