### ISSUE TITLE
Missing Id for Firewall Outbound Mapping 

### ISSUE THREAD

**Issue by maltere** [jaredhendrickson13/pfsense-api#139]
Hello, 

it seems to me that the Objects returned by the _Firewall Outbound Mappings_-Endpoint are not including an corresponding id.
However, an id is required in order to delete a mapping. Is this a bug or an error in the documentation?

I make the call to `GET /api/v1/firewall/nat/outbound/mapping` and the returned Keys are:

```py
[
    {
        "source": {"network": "10.10.10.0/24"},
        "sourceport": "",
        "descr": "",
        "target": "1.2.3.4",
        "targetip": "",
        "targetip_subnet": "",
        "interface": "wan",
        "poolopts": "",
        "source_hash_key": "",
        "ipprotocol": "inet",
        "destination": {"any": ""},
        "updated": {
            "time": "1623648668",
            "username": "admin@xxx (Local Database)",
        },
        "created": {
            "time": "1623648668",
            "username": "admin@xxx (Local Database)",
        },
    },
]
```

Furthermore, the returned values seem non-consistent with the values that need to be set for creating new mappings. (e.g. `source` is not supposed to be an object and `ipprotocol` is not documented)

Appreciate any response. Great API so far!

**Comment by maltere** [comment]
I got it working by experimenting random ids today. You can use the Array Index of the `GET` request as ID.

Keep in mind that the index changes after each deletion for later entries.

**Comment by jaredhendrickson13** [comment]
Hey there!

Sorry for the delayed response, I've taken a bit of a break from this project the last few months but will be ramping up development again soon. 

As for your issue, obtaining object IDs is covered in the documentation [here](https://github.com/jaredhendrickson13/pfsense-api#obtaining-object-ids). If you have any further issues please let me know.

Thanks!
