### ISSUE TITLE
Firewall/rule - update rule - discrepancy between API and documentation?

### ISSUE THREAD

**Issue by ragnarbullnielsen** [jaredhendrickson13/pfsense-api#14]
Thanks for the solid work on this project!  Just what I've been looking for to automate firewall rule enabling/disabling from my Home Assistant system.

However, when I try to implement rule dis- / enabling using the API, I run into problems.

The documentation (again, solid work!) states that all fields except tracker ID are optional.  However, when I try to disable an existing rule using the bare minimum of information, it doesn't work:

ragnar@ragnars-bigmac ~ % curl -i http://pfsense.address/api/v1/firewall/rule -X PUT -d '{"client-id": "secretapiuser", "client-token": "secretapipassword", "tracker": 1577540218, "disabled": true}'

HTTP/1.1 400 Bad Request
Server: nginx
Date: Thu, 01 Oct 2020 17:21:34 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Referer: no-referrer

{"status":"bad request","code":400,"return":4036,"message":"Firewall rule protocol required","data":[]}

If I try to include protocol, it asks further:

ragnar@ragnars-bigmac ~ % curl -i http://pfsense.address/api/v1/firewall/rule -X PUT -d '{"client-id": "secretapiuser", "client-token": "secretapipassword", "tracker": 1577540218, "disabled": true, "protocol": "tcp"}'

HTTP/1.1 400 Bad Request
Server: nginx
Date: Thu, 01 Oct 2020 17:31:42 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Referer: no-referrer

{"status":"bad request","code":400,"return":4047,"message":"Firewall rule source and destination port required","data":[]}

I haven't dug any further, but I suspect it will go on asking until I've expanded the information to define a complete firewall rule. 

Is this by design, and have I just misread or misinterpreted the documentation?

BR,
Ragnar

**Comment by jaredhendrickson13** [comment]
Hi there,

Thanks for reporting this issue! You are correct, the tracker ID should be the only required field when updating a firewall rule. Looking at the code, it seems I have the `protocol` field being validated as a required field which is a bug. When the `protocol` field is updated, it also triggers validation on the `srcport` and `dstport` as well, which is why you continued to receive an error after specifying the protocol. I am working on a few other smaller bugs and will include this bug fix in a patched release either end of day today or tomorrow. 

Thanks again,

**Comment by ragnarbullnielsen** [comment]
Cool!  My first PR on Github -- nice to know it wasn't moot :-)

**Comment by dbates-ftnt** [comment]
I've just hit this issue as well and I'm on 1.0.1  (latest)

Trying to use the API to toggle on/off a rule.  

I can retrieve the object:

`          "id": "",
            "tracker": "1602257611",
            "type": "pass",
            "interface": "opt1",
            "ipprotocol": "inet",
            "tag": "",
            "tagged": "",
            "max": "",
            "max-src-nodes": "",
            "max-src-conn": "",
            "max-src-states": "",
            "statetimeout": "",
            "statetype": "keep state",
            "os": "",
            "protocol": "icmp",
            "icmptype": "any",
            "source": {
                "address": "154.47.80.4"
            },
            "destination": {
                "any": ""
            },
            "log": "",
            "descr": "",
            "dnpipe": "high-latency-in",
            "pdnpipe": "high-latency-out",
            "created": {
                "time": "1602257611",
                "username": "admin@192.168.134.100 (Local Database)"
            },
            "updated": {
                "time": "1602258597",
                "username": "admin@192.168.134.100 (Local Database)"
            }
        },`

But when I try and edit it: 

```
{
    "tracker": 1602257611,
	"disabled": true
}
```

I get the error: 

```
{
    "status": "bad request",
    "code": 400,
    "return": 4031,
    "message": "Firewall rule tracker ID required",
    "data": []
}
```

**Comment by jaredhendrickson13** [comment]
@dbates-ftnt This looks to be a slightly different issue. Return code `4031` will only be set when the `tracker` item is missing from the parsed request body. Either your HTTP client is not sending the request body in an expected format, or there is a syntax error in your request body preventing the JSON content body from being parsed when it reaches pfSense. Feel free to open a new issue and include more information about your HTTP client and I can help out. This is likely an area that could use some more transparency in future releases.

Thanks!
