### ISSUE TITLE
Using API to create a firewall rule using Port Alias's

### ISSUE THREAD

**Issue by bgatesnccs** [jaredhendrickson13/pfsense-api#141]
Hello there, 
 We are utilizing this API to create large entries of Firewall rules currently, we are starting to implement using Port Alias's so we can slim down the ammount of individual rules we have to create. 
Is it possible to use the Port alias we have defined in Firewall>Aliases>Ports>AliasName1
Essentially the API Call should be similar to this if it is possible to define the ports using the alias
{
    "type": "pass",
    "interface": "lan",
    "ipprotocol": "inet",
    "protocol": "tcp/udp",
    "src": "X.X.X.X",
    "srcport": "any",
    "dst": "X.X.X.X",
    "dstport": AliasName1,
    "descr": "PortAlias",
    "top": true
}

**Comment by jaredhendrickson13** [comment]
Hey!

Yes, you may specify the alias name within the `srcport` or `dstport` fields as long as the `protocol` field is set to `tcp`, `udp`, or `tcp/udp`. Here's an example:

```
$ curl -s -H "Authorization: xxxxx xxxxxxxxxx" -d '{"type": "pass", "ipprotocol": "inet", "protocol": "tcp", "src": "LAN", "srcport": "any", "dst": "any", "dstport": "TEST_PORTS", "interface": "LAN"}' -X POST https://jaredhendrickson.com/api/v1/firewall/rule | jq .
{
  "status": "ok",
  "code": 200,
  "return": 0,
  "message": "Success",
  "data": {
    "type": "pass",
    "interface": "lan",
    "ipprotocol": "inet",
    "protocol": "tcp",
    "source": {
      "network": "lan"
    },
    "destination": {
      "any": "",
      "port": "TEST_PORTS"
    },
    "tracker": 1626471133,
    "created": {
      "time": 1626471133,
      "username": "jhendrickson@192.168.1.x (API)"
    },
    "updated": {
      "time": 1626471133,
      "username": "jhendrickson@192.168.1.x(API)"
    }
  }
}
```

Hope this helps. Let me know if you have any questions or run into any issues. 

Thanks!
