### ISSUE TITLE
Wish: Get external IP

### ISSUE THREAD

**Issue by fbnielsen1959** [jaredhendrickson13/pfsense-api#144]
It would be nice to get the external (real) IP

shell example:
dig @resolver1.opendns.com myip.opendns.com +short
dig @ns1-1.akamaitech.net whoami.akamai.net +short
They work in the PFSense shell and are NOT dependent on some website that may be down.
+ they are fast < 0.03 sek.

Note: akamai.net is changing it. (the above version still works.)
dig +short TXT whoami.ipv4.akahelp.net
But this result needs parsing
See: https://developer.akamai.com/blog/2018/05/10/introducing-new-whoami-tool-dns-resolver-information

opendns.com is using it for DDNS, so I doubt it will change, as it will break all DDNS for their users.

**Comment by JeGr** [comment]
AFAIK you can't use dig to bind on a specific IP or interface, so in MultiWAN setups that won't show the IP of the second/third/etc. interface.

What would be better is to use the internal test via `curl` to the configured IP/DNS of the check service. Per default that should point to `checkip.dyn.com` but the user can enter his own service(s) in Services/DynDNS to override that.
With `curl` you can bin to an interface (physical interface name) or an IP address so the check can be mapped to the appropriate interface/IP and use that for the check.

```
> curl --interface vtnet0 checkip.dyn.com
<html><head><title>Current IP Check</title></head><body>Current IP Address: 1.2.3.4</body></html>
```

**Comment by jaredhendrickson13** [comment]
Since this is not a feature currently in pfSense (at least that I'm aware of), I'm thinking a better course for this would be to create an endpoint that allows you to run shell commands similar to the Diagnostics > Command Prompt page in the UI. This would allow you to run these commands whichever way works best and is a feature that currently exists within pfSense. What do you think?

**Comment by JeGr** [comment]
Depends on what you mean by "not currently on pfSense". Internally the check is used e.g. for all things related Dynamic DNS. 
The IP that's recognized is used for example in `services_dyndns_edit.php` via

`        $pconfig['curl_ipresolve_v4'] = isset($a_dyndns[$id]['curl_ipresolve_v4']);`

it should be available by importing `dyndns.class` and referencing `$conf['curl_ipresolve_v4']` then you should get the same output as pfSense itself uses for dyndns purposes or by using `function dyndnsCheckIP($int) ...` in `services.inc`.

**Comment by fbnielsen1959** [comment]
I like the idea of a shell command endpoint.
That would open for all sorts of specialized features.
