### ISSUE TITLE
API Token 

### ISSUE THREAD

**Issue by andrecallman** [jaredhendrickson13/pfsense-api#146]
Hi there 

I was testing the api and found a litle problem.

How can I get de API Client token in API Tokens?

The text showed is just 402b953253e7f1ee7a4f...

**Comment by andrecallman** [comment]
![image](https://user-images.githubusercontent.com/19828305/126794239-b271da59-07be-4c58-8ebd-e9eba4f29ffa.png)

**Comment by jaredhendrickson13** [comment]
Hey!

This looks to be a duplicate of #103. The text you have highlighted is just a hash representation of the token, the actual token is only displayed once after it is generated up in the green confirmation banner. Refer to #103 for more info. 

Thanks!
