### ISSUE TITLE
Small info extension

### ISSUE THREAD

**Issue by fbnielsen1959** [jaredhendrickson13/pfsense-api#147]
services/dhcpd/static_mapping is missing online info.
You can see it in the GUI under Status -> Leases (For both Static and DHCP)

**Comment by jaredhendrickson13** [comment]
Hey!

This information is found under the `/api/v1/services/dhcpd/lease` endpoint. The `/api/v1/services/dhcpd/static_mapping` endpoint is only for interacting with the DHCP static mapping configurations that reside in the Services > DHCP Server UI page.

Hope this helps.

Thanks!

**Comment by fbnielsen1959** [comment]
Hi
The static leases are not included in the `/api/v1/services/dhcpd/lease` endpoint.
And the online status is not in the `/api/v1/services/dhcpd/static_mapping`  endpoint.
Online status is shown for all leases (dhcp/static) in the gui.

Flemming

**Comment by jaredhendrickson13** [comment]
Yes, looks like you are correct. Currently the process to fetch the lease for static mappings is missing. I was able to rewrite the `/api/v1/services/dhcpd/lease` endpoint to better match the UI and that fix will be included in the next patch. Should have that patch tested and released by the end of the day. 

Thanks for pointing this out!
