### ISSUE TITLE
DHCP update range issue

### ISSUE THREAD

**Issue by Hundeklemmen** [jaredhendrickson13/pfsense-api#149]
**Error Message:** (2022)
```
DHCPd start range is outside of available IP range
```
**Endpoint:**
PUT /api/v1/services/dhcpd

Tested subnet details:
**Subnet:**
x.x.x.192
**Mask:**
255.255.255.192
**Available range:**
x.x.x.193 - x.x.x.254

When start range is set to x.x.x.193 and/or end range is set to x.x.x.193 it will cause the error while the UI have no issues.

**Comment by jaredhendrickson13** [comment]
Hey!

I'm assuming the gateway for this interface is x.x.x.193? If so, one difference between the API validation and the UI validation is the API will not allow the DHCP range to start with the gateway's address even though the UI does allow this. Doing so in the past had caused some issues with automated testing and to my understanding, including the gateway's address in the DHCP pool has no practical use case. I've tested this and bumping the start range to x.x.x.194 will allow the change from the API.

If I'm mistaken and there is a legitimate use case for including the gateway's address in the DHCP pool I'm open to changing this. Again this is all under the assumption that the gateway is x.x.x.193, if that's not the case let me know and I can take another look.

Thanks!

**Comment by Hundeklemmen** [comment]
Correct the gateway ip address is x.x.x.193
Our usecase involves having all devices connected to the interface assigned a static mapping, so by having the range start at x.x.x.194 and end at x.x.x.195 we waste 2 ip addresses per interface

So ideally to not waste any ips, we would set the pool to start and end to x.x.x.193

**Comment by jaredhendrickson13** [comment]
Gotcha, that is a fair use case and does seem to be the only way such a configuration can exist. I will work on a fix for this and have it included in a patch. Time permitting, I should be able to have that released next week. 

I appreciate the insights. Let me know if you have any questions in the meantime. 

Thanks again!
