### ISSUE TITLE
Support GRE interface

### ISSUE THREAD

**Issue by Hoto-Cocoa** [jaredhendrickson13/pfsense-api#156]
I can query interfaces using this API.

However I can't manage GRE interface configuration by using this API.

Here is some example features:
 -  Show remote/local address of GRE tunnel when get interfaces list
 - Add/Update/Delete GRE tunnel via API

**Comment by MokkaSchnalle** [comment]
This feature would be awesome. This will also fix the missing option to use gateway groups for GRE tunnels.
