### ISSUE TITLE
kill states by IP

### ISSUE THREAD

**Issue by george-vieira** [jaredhendrickson13/pfsense-api#160]
I tried looking over the docs and don't see an api call to filter states by IP and then kill the states. if there is a way, please let me know as all I can see is to list the current states but can't see anything I can do with it ie kill.
I need to be able to add a new rule but then kill any connections to it which is what I see lacking.

**Comment by jaredhendrickson13** [comment]
Hey!

Currently there is not endpoint to do this. I'll keep this open as a feature request for a future release.

Thanks!

**Comment by jaredhendrickson13** [comment]
Hey!

These features have been implemented on the v1.4.0 (#172) branch and are live on the v1.4.0beta_4 build that is posted on that pull request. Feel free to try it out. We are likely 1-2 months away from v1.4.0 being released as a production release.

Thanks!

**Comment by george-vieira** [comment]
that's brilliant, thanks. I can finally control my daughters internet browsing and kicking her off when time is up :)
