### ISSUE TITLE
Is there any recommended api client?

### ISSUE THREAD

**Issue by IonicaBizau** [jaredhendrickson13/pfsense-api#163]
Is there a recommended API client you would suggest? I work more with Node.js, but could not find any client for Node.js. Is there any page with the client libraries connecting to the API?

Thank you for the wonderful package!

**Comment by yaleman** [comment]
I'm starting to write one here https://github.com/yaleman/pfsense-api-client

**Comment by jaredhendrickson13** [comment]
Update on this. v1.4.0 will make the switch to Swagger/OpenAPI for documentation and structure. This will also include the ability for auto-generated API clients in your desired language.

**Comment by wisefella** [comment]
Any new/updates on API client? Looking to develop an iOS app/client to control pfSense. Would prefer to not reinvent the wheel. Thanks.

**Comment by sjafferali** [comment]
Not sure how much it would help for iOS development, but I have a API client created for go at https://github.com/sjafferali/pfsense-api-goclient.
