### ISSUE TITLE
certificate not decoded

### ISSUE THREAD

**Issue by gfrankliu** [jaredhendrickson13/pfsense-api#165]
I tried to import an existing CA using https://github.com/jaredhendrickson13/pfsense-api#systemca following the example given:

```
{
	"method": "existing",
	"crt": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZxekNDQTVPZ0F3SUJBZ0lVQi9rT2RoMzdTZnRxeHRqL1MxSTRkUTQyYXRvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pURUxNQWtHQTFVRUJoTUNWVk14Q3pBSkJnTlZCQWdNQWxWVU1RMHdDd1lEVlFRSERBUlBjbVZ0TVNFdwpId1lEVlFRS0RCaEpiblJsY201bGRDQlhhV1JuYVhSeklGQjBlU0JNZEdReEZ6QVZCZ05WQkFNTURuUmxjM1F1CmMyVmpiV1YwTG1Odk1CNFhEVEl3TURJd05ESXdNelV3...",
	"prv": "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUpRZ0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQ1N3d2dna29BZ0VBQW9JQ0FRREQ5RkNLU1U3SmY0QngKeWlKNkNOWGhOckI0ZVhjTk9TTm9GUVJIbXlsV2dHbEN5djMydFdicmF3RFhhQzk2aVpOSTFzNG5qWTdQT3BlWgpoNmFlaTJ5NllheS9VWWtOUkZGQmp4WlZlLzRwS2pKeXBQRlFBUlpMVko2TlNXaU5raGkwbDlqeWtacTlEbkFnCk1mclZyUEo1YktDM3JJVV...",
	"descr": "TEST CA"
}
```

My CA pem file is /tmp/ca.pem, and I base64 encoded it `cat /tmp/ca.pem | base64`. I used the long base64 string in the API call. The API call went fine. I logged in pfsense UI and can see the CA created. In the certificate box, I only see the base64 encoded long string, not the actual decoded pem file. Is that normal?

**Comment by jaredhendrickson13** [comment]
Hey!

Thanks for pointing this out, this should not be happening. It looks like pfSense may be re-encoding the certificate before it's written to the configuration somewhere along the way. I'll track this down and have a fix implemented in the next patch. I'll keep this issue updated with progress. 

Thanks again!
