### ISSUE TITLE
Change Local DB authentication from HTTP request body to HTTP basic authentication 

### ISSUE THREAD

**Issue by pincher95** [jaredhendrickson13/pfsense-api#174]
**Is your feature request related to existing pfSense functionality that is missing from the API? Please describe.**

Local Database (default)
Uses the same credentials as the pfSense webConfigurator. To authenticate API calls, simply add a client-id value containing your username and a client-token value containing your password to your payload. For example {"client-id": "admin", "client-token": "pfsense"}

**Is your feature request related to a problem? Please describe.**

It's more an inconvenience, for example I was writing API client in GO and wanted to set auth once to http client to be used across all API calls since in current setup auth included in request body it was set in each API call. 

**Describe the solution you'd like**

I think it will make more sense to use Local DB as http basic authentication  
curl -u admin:pfsense https://127.0.0.1/api/v1/......

**Comment by jaredhendrickson13** [comment]
Hey!

The current local database authentication mechanism was the original one and replacing that entirely would break many peoples implementations, which is really the only reason it still exists in it's current state. But I can easily add a condition that checks for basic authentication and then fallback to the request body if basic authentication was not used.

Thanks!

**Comment by danielmichaels** [comment]
Despite being one of those users who has built a lot of code based on the current implementation of local database auth, I still love the idea of a fallback from basic auth to the request body. Keep up the good work!
