### ISSUE TITLE
Create/Update DHCP Services (Lease Times & DHCP Options)

### ISSUE THREAD

**Issue by crawc** [jaredhendrickson13/pfsense-api#176]
**Is your feature request related to existing pfSense functionality that is missing from the API? Please describe.**
A URL or documentation about the requested functionality. Ex. /firewall_rule.php [...]
/services_dhcp.php?if=opt1
When you GET the DHCP these fields are return but it doesn't appear that they can be set when creating/updating DHCP services:

            "defaultleasetime": "2592000",
            "maxleasetime": "2678400",
            "numberoptions": {
                "item": [
                    {
                        "number": "66",
                        "type": "string",
                        "value": "IlRoaXMgaXMgbXkgb3B0aW9uIDY2IGluIGJhc2U2NCI="
                    }
                ]
            }

**Is your feature request related to a problem? Please describe.**
Currently unable to set these options using the API

**Describe the solution you'd like**
Implement these fields when creating/updating DHCP services.

**Describe alternatives you've considered**
After using the API to create the service I must use the pfSense interface (/services_dhcp.php?if=opt1) to set them and restart DHCP.

**Additional context**
Great work on this! Very helpful.

**Comment by jaredhendrickson13** [comment]
Hey! 

These features have been implemented on the v1.4.0 (#172) branch and are live on the v1.4.0beta_4 build that is posted on that pull request. Feel free to try it out. We are likely 1-2 months away from v1.4.0 being released as a production release.

Thanks!

**Comment by crawc** [comment]
**Awesome work! @jaredhendrickson13 ** 

Both the Lease time and other DHCP options seem to work great. I've tested mostly with stings for the DHCP options.
`                "item": [
                    {
                        "number": "66",
                        "type": "string",
                        "value": "\"https://boot.myserver.com/boot/\""
                    }
                ]
            }`


**Would it be possible to add the NTP servers too?**
`            "ntpserver": [
                "0.pool.ntp.org",
                "1.pool.ntp.org",
                "2.pool.ntp.org"
            ]`
