### ISSUE TITLE
add support for pfsense+

### ISSUE THREAD

**Issue by bajtpop** [jaredhendrickson13/pfsense-api#182]
Can you add support for pfsense+ ?

WARNING: No overrides exist for 21.05.1-RELEASE, it may be unsupported. Using default overrides.

**Comment by bajtpop** [comment]
I can send you system.inc if needed. There is couple new functions.

**Comment by jaredhendrickson13** [comment]
Hey!

See #140. Full pfSense Plus compatibility unfortunately requires more than just the file overrides. Both pfSense CE and pfSense Plus are pretty similar at the moment, but as time goes on they are branching further and further apart which will cause the package to break more and more often over time. I don't have access to a pfSense Plus host unfortunately and the increased complexity and workload it would require is too much for me support hence my decision to only support pfSense CE at this time. 

If you can get the API package to even install on pfSense Plus, my recommendation would be to create the necessary file overrides (the overridden section is within the nginx configuration functions) and test the endpoints you need thoroughly to ensure they work as expected. I would expect this implementation to break over time however. 

Best of luck to you. 

Thanks!
