### ISSUE TITLE
Routing Gateway Groups

### ISSUE THREAD

**Issue by twyxxywt** [jaredhendrickson13/pfsense-api#189]
I know this is probably not been used by a lot of people. If this can be implemented and allowing toggling of gateway on different tiers (e.g. priority) would be nice.

Been playing around and when polling the gateway details I do see field "tiername". But when I attempted to update that field it doesn't do anything. Also saw field "isdefaultgw" on the specific GW when I set to Tier 1 Gateway Priority. Try set that to true on my other WAN link doesn't do anything neither.

Thank you for all your amazing works. Discovered yesterday and been helpful automating few things.

**Comment by AAGEM** [comment]
Configure gateway group via API
We would like to configure the Default Gateway used by psfense.
Then select a Gateway Group via the API among those previously configured in pfsense.
This operation is only possible via GUI through System / Routing / Gateways by selecting the Default Gateway IPv4.

Thanks
