### ISSUE TITLE
Ability to add group membership when creating users with the api

### ISSUE THREAD

**Issue by jpoCruz** [jaredhendrickson13/pfsense-api#192]
**Is your feature request related to existing pfSense functionality that is missing from the API? Please describe.**
Hello there!

I'd like to automate the creation of users for our pfsense openvpn combo. Reading through the docs, it doesn't look like there is a way to create users and insert them into "group memberships".

It would be amazing if this was a functionality you could add! 

If there already is a way to do this using the API, I apologize! I'd love to know how to do it, in that case.

Thank you so much :)

**Comment by jaredhendrickson13** [comment]
Hey!

Groups themselves can't be created from the API yet, but you are able to assign users to existing groups using /api/v1/user/group endpoint. You can see the documentation for that here: https://github.com/jaredhendrickson13/pfsense-api#usergroup. 

For example:
```
curl -s -k -d '{"client-id" : "admin", "client-token": "pfsense", "username": "test_user", "group": ["some_group1", "some_group2"]}' -X POST https://localhost/api/v1/user/group
{
  "status": "ok",
  "code": 200,
  "return": 0,
  "message": "Success",
  "data": [
    "all",
    "some_group1",
    "some_group2"
  ]
}
```

This must be done after the user is created however, which can also be done via API using the /api/v1/user endpoint: https://github.com/jaredhendrickson13/pfsense-api#user.

One thing to note about this endpoint going forward, [v1.4.0](https://github.com/jaredhendrickson13/pfsense-api/pull/172) will be changing this functionality. /api/v1/user/group will be used to create, update, read and delete groups and group memberships will be moved to the /api/v1/user endpoint using a newly added `groups` field instead. Just something to keep in mind. 

Hope this helps, let me know if you have any trouble getting it to work.

Thanks!

**Comment by jpoCruz** [comment]
Ahh, I see! 

That seems absolutely perfect and feels like it'll work perfectly.
I'll try to implement this and if I do end up having any problems, I'll let you know. I'll also keep the v1.4.0 changes changes in mind!

Thank you for the quick answer and thanks for the help.
