### ISSUE TITLE
Missing spoofmac field is causing interface rules malfunction.

### ISSUE THREAD

**Issue by VIKMSTR** [jaredhendrickson13/pfsense-api#195]
**Describe the bug**
Missing spoofmac field in the XML configuration
**To Reproduce**
1. Create new vlan 
2. Assign new interface with the newly created LAN
3. Export the XML configuration
4. See the differences between newly created and original interfaces.

**Expected behavior**
Unlike other interfaces, the empty field <spoofmac></spoofmac> is missing from the interface configuration of newly created interface. This causes, that the newly created interface is handled incorrectly and cannot load rules attached to it.

When opening in GUI and clicking Save on the interface editation page, the empty field is added and rules are correctly loaded.

Sending empty value for spoofmac attribute is not possible, due to mac validation on the API endpoint.

**Screenshots or Response**
exported config.xml
```xml
                <opt14>
			<descr><![CDATA[OPT14]]></descr>
			<if>vmx2</if>
			<spoofmac></spoofmac>
		</opt14>
		<opt15>
			<if>vmx0.89</if>
			<descr><![CDATA[OPT15]]></descr>
			<ipaddr>192.49.21.21</ipaddr>
			<subnet>24</subnet>
			<ipaddrv6>dhcp6</ipaddrv6>
			<ipv6usev4iface></ipv6usev4iface>
		</opt15>
```
OPT14 is created manually, OPT15 via API

**pfSense Version & Package Version:**
 - pfSense Version: [e.g. pfSense 2.5.2]
 - Package Version [e.g. v1.2.4]

**Affected Endpoints:**
 - URL: [e.g. /api/v1/interface]

**Additional context**
Is this issue fixed on a later versions of the API? Maybe it is already solved with newer release, IDK.

**Comment by jaredhendrickson13** [comment]
Hey!

Thanks for bringing this up. pfSense usually treats missing values and empty values the same therefor this usually wouldn't cause any issues but of course that's not always the case; but I haven't looked deeper into the code to verify. Regardless, you are correct it would be best to default that value to an empty string if none was specified and allow interface updates to revert to the default (empty) value. I'll get this fixed, I have a patch planned for release this weekend so I'll have this included. 

Thanks!
