### ISSUE TITLE
Gateway Groups

### ISSUE THREAD

**Issue by EULABreaker** [jaredhendrickson13/pfsense-api#197]
**Is your feature request related to existing pfSense functionality that is missing from the API? Please describe.**
A URL or documentation about the requested functionality. Ex. /firewall_rule.php [...]

/system_gateways.php

**Is your feature request related to a problem? Please describe.**

Would like to be able to change gateway tiers within gateway groups

**Describe the solution you'd like**

Be able to change / add / remove gateway groups

**Describe alternatives you've considered**

I haven't tried any

**Additional context**

**Comment by jaredhendrickson13** [comment]
Duplicate of #189.
