### ISSUE TITLE
2.6.0 - Missing functions in system.inc

### ISSUE THREAD

**Issue by mbentley** [jaredhendrickson13/pfsense-api#199]
**Describe the bug**
There is an error that comes up in a few places (main dashboard, upgrade page, auto backups) due to a couple missing functions in system.inc that appear to be new in 2.6.0 in `/etc/inc/system.inc`:

https://github.com/pfsense/pfsense/blob/95d74811193b4be8eb515b5dd13e963971f8de57/src/etc/inc/system.inc#L2797-L2843

![screenshot 2022-02-18 at 2 34 09 AM](https://user-images.githubusercontent.com/414445/154642167-092a78ed-aa77-424e-ad8e-426d931db9b7.png)

Crash bug report:

```
Crash report begins.  Anonymous machine information:

amd64
12.3-STABLE
FreeBSD 12.3-STABLE RELENG_2_6_0-n226742-1285d6d205f pfSense

Crash report details:

PHP Errors:
[18-Feb-2022 02:55:38 America/Indiana/Indianapolis] PHP Fatal error:  Uncaught Error: Call to undefined function check_dnsavailable() in /etc/inc/pkg-utils.inc:1330
Stack trace:
#0 /usr/local/www/widgets/widgets/system_information.widget.php(73): get_system_pkg_version(false, true)
#1 {main}
  thrown in /etc/inc/pkg-utils.inc on line 1330
[18-Feb-2022 02:55:47 America/Indiana/Indianapolis] PHP Fatal error:  Uncaught Error: Call to undefined function check_dnsavailable() in /etc/inc/pkg-utils.inc:1331
Stack trace:
#0 /usr/local/www/widgets/widgets/system_information.widget.php(73): get_system_pkg_version(false, true)
#1 {main}
  thrown in /etc/inc/pkg-utils.inc on line 1331
[18-Feb-2022 03:02:06 America/Indiana/Indianapolis] PHP Fatal error:  Uncaught Error: Call to undefined function check_dnsavailable() in /etc/inc/pkg-utils.inc:1331
Stack trace:
#0 /usr/local/www/widgets/widgets/system_information.widget.php(73): get_system_pkg_version(false, true)
#1 {main}
  thrown in /etc/inc/pkg-utils.inc on line 1331



No FreeBSD crash data found.
```

**To Reproduce**
1. Load the dashboard UI with the version check enabled.

**Expected behavior**
The functions should exist in the patched version

**Screenshots or Response**
If applicable, add screenshots or response data to help explain your problem.

**pfSense Version & Package Version:**
 - pfSense Version: [e.g. pfSense 2.6.0]
 - Package Version [e.g. v1.3.3]

**Affected Endpoints:**
n/a

**Additional context**
Others reported the bug here: https://forum.netgate.com/topic/170025/crash-report-after-upgrading-to-2-6-yesterday

**Comment by mbentley** [comment]
Sorry, I'm now seeing that for 2.6.0, it is using the default overrides since there is not yet a 2.6.0 one.  I did a quick diff from the original 2.5.2 -> 2.6.0 `system.inc` to get a patch file and it does seem to apply cleanly at least (https://gist.github.com/mbentley/032f3f0bf05370cc95dc1e5a10d0d72c).  Not sure if that's how you generate them or not but I could make a PR if that is helpful.  I haven't worked with this code base before so I don't know if there is anything else I am missing though so figured I'd check in first.

**Comment by oakslabs** [comment]
I can confirm the same behavior on 3 pfSenses after the upgrade to 2.6.0.

**Comment by jaredhendrickson13** [comment]
Hey!

Yes, you are correct the overrides don't exist for 2.6.0 yet. I typically have the overrides for new pfSense releases implemented within a week or two of their release. I have the 2.6.0 overrides ready to go and I plan to have them included in a patch this weekend. I'll update this issue when those changes are merged in. 

Thanks!
