### ISSUE TITLE
SERVICES/UNBOUND -> create DNS resolve entry

### ISSUE THREAD

**Issue by megnetx** [jaredhendrickson13/pfsense-api#201]
Hello,
First of all thanks for this project!

I think i found a bug or (this version is also possible I'm a noob :D)

I would like to create a new DNS resolve entry with https://{{$hostname}}/api/v1/services/unbound/start path.
I used this API with JWT token, and I followed the debug steps, and the remote command running is worked.

I use this sequence:

Read the existing configuration:
"Method: GET
URL: https://{{$hostname}}/api/v1/services/unbound"

and make a new host like this 

{
    
    "host": "anything",
    "domain": "localnetwork.intra",
    "ip": "10.0.0.70",
    "descr": "Something interest",
    "aliases": ""
    
}

This JSON is POST-ed with 

"Method: POST
URL: https://{{$hostname}}/api/v1/services/unbound/start"

The response is contained this:

{
  "status": "ok",
  "code": 200,
  "return": 0,
  "message": "Success",
  "data": {
    "unbound": "started"
  }
}

After that I try to make an apply call in this API path: 
"Method: POST
URL: https://{{$hostname}}/api/v1/services/unbound/apply
"
With body like:

{

}

This response also contain success:

{
  "status": "ok",
  "code": 200,
  "return": 0,
  "message": "Success",
  "data": []
}

And the I make a call with the first GET type API path, but the new configuration is not shown.
So I make a restart with this parameters:

Method: POST
URL: https://{{$hostname}}/api/v1/services/syslogd/restart

{

}

But the new configuration not shown at all...

So I misunderstood something or make a wrong body for the start command or I don't know...

Please help if you have any time.

Thx a lot
Best regards
Megnetx

**Comment by jaredhendrickson13** [comment]
Hey!

Looks like you are making requests to the wrong endpoints. To create a Unbound DNS entry/host override, you can make POST requests to /api/v1/services/unbound/host_override. Here's an example using curl:

```
curl -s -k -H "Authorization: Bearer <JWT>" -d '{"host": "anything", "domain": "localnetwork.intra", "ip": "10.0.0.70", "descr": "Something interest", "aliases": []}' -X POST https://<pfSense IP or hostname>/api/v1/services/unbound/host_override
```

Then you can call the /api/v1/services/unbound/apply endpoint to apply the changes:
```
curl -s -k -H "Authorization: Bearer <JWT>" -X POST https://<pfSense IP or hostname>/api/v1/services/unbound/apply
```

After making these two requests you will be able to resolve the DNS entry. Hope this helps. 

Thanks!
