### ISSUE TITLE
Firewall Rule - Gateway cannot be unset

### ISSUE THREAD

**Issue by VIKMSTR** [jaredhendrickson13/pfsense-api#202]
**Describe the bug**
Because the API does not support empty value for gateway attribute in firewall rule endpoint, it cannot be unset back to "*" (Default)

**To Reproduce**
1. Create Firewall Rule with assigned gateway 
2. Update the Firewall Rule with empty "gateway" field
3. See BAD REQUEST error with Unknown firewall rule gateway

**Expected behavior**
Empty value should set the gateway to the Default - the same as in GUI 

**Screenshots or Response**
`{"status":"bad request","code":400,"return":4043,"message":"Unknown firewall rule gateway","data":[]}`
![image](https://user-images.githubusercontent.com/2676163/156401530-9393ea92-443a-40a3-b583-1a1c6e53024a.png)

**pfSense Version & Package Version:**
 - pfSense Version: [e.g. pfSense 2.5.2]
 - Package Version [e.g. v1.3.3]

**Affected Endpoints:**
 - /api/v1/firewall/rule

**Additional context**
Maybe there is some hidden default value that I dont know or is not documented? :)

**Comment by jaredhendrickson13** [comment]
Hey!

Looks like you are correct. The gateway lookup that is called during firewall updates does not check for a value to revert to the default gateway; so once it is set it cannot be unset (from the API at least). This should be fairly easy to fix, I'll see if I can put together enough changes to justify a patch containing this fix. If not, I'll roll this into v1.4.0 which should be released pretty soon. 

As a workaround in the meantime, you can use the API to delete the firewall rule (without applying changes), re-create the rule without specifying a gateway, and then apply the changes. This should have the same effect as updating the entry, but some of the original data such as the `created` field and firewall rule position will be lost. 

I'll update this issue once I have a pull request containing the fix. 

Thanks!

**Comment by VIKMSTR** [comment]
Thanks for response and workaround suggestion! :)
