### ISSUE TITLE
Update System Certificate Endpoint

### ISSUE THREAD

**Issue by Hoto-Cocoa** [jaredhendrickson13/pfsense-api#205]
**Is your feature request related to existing pfSense functionality that is missing from the API? Please describe.**
`/system_certmanager.php?act=edit&id={$id}`

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Update Certificate API Endpoint (similar to create?)

**Describe alternatives you've considered**
Rename Certificate Name to Replacing by Changing old certificate's name?

**Additional context**
I want update system certificate for renew haproxy frontend certificate.

**Comment by jaredhendrickson13** [comment]
This feature is included in v1.4.0.
