### ISSUE TITLE
adv_ DHCP options not updating

### ISSUE THREAD

**Issue by MokkaSchnalle** [jaredhendrickson13/pfsense-api#206]
**Describe the bug**
Updating the adv_ DHCP options on an interface does not work properly.

**To Reproduce**
Request PUT: `{"id": "opt8", "adv_dhcp_option_modifiers": "supersede subnet-mask 255.255.255.0, supersede routers 38.11.22.1"}`

It says 200 Success but the new value is not saved.

Other things like descr are working fine:
`{"id": "opt8", "descr": "foobar"}`

Maybe the comma in the DHCP string is a problem?

**Expected behavior**
The response and the pfsense config should present the updated DHCP options

**Screenshots or Response**
![2022-03-22_19-38-58](https://user-images.githubusercontent.com/71295911/159555715-de3f17ec-e80a-4f96-b800-033e3c080d03.png)

**pfSense Version & Package Version:**
 - pfSense Version: [e.g. pfSense 2.6.0]
 - Package Version [e.g. v1.3.5]

**Affected Endpoints:**
 - URL: [e.g. /api/v1/interface]

**Additional context**
Background:
I am trying to update the dhcp option for a 5G modem interface. This only provides a /8 IP like 38.0.0.1 for a public ip 38.11.22.33. Therefore, I am using the supersede option to set a /24 gateway (e.g. 38.11.22.1) manually. After getting a new Public IP, the supersede gateway needs to be changed to the new ip range.

**Comment by jaredhendrickson13** [comment]
Hey!

The /api/v1/interface doesn't support partial updates in some cases simply due to the amount of conditional validation that is required. In this case, the `type` and `adv_dhcp_config_advanced` fields must also be specified in your request in order for the necessary validation to occur to update the `adv_dhcp_option_modifiers` field. Try changing your request to:

```json
{"id": "opt8", "adv_dhcp_option_modifiers": "supersede subnet-mask 255.255.255.0, supersede routers 38.11.22.1", "type": "dhcp", "adv_dhcp_config_advanced": true}
```

Hope this helps. Let me know if you have any issues.

Thanks!

**Comment by MokkaSchnalle** [comment]
Hi!
thanks for your quick reply!

That fixed it. Thank you!
![2022-03-23_09-50-00](https://user-images.githubusercontent.com/71295911/159659821-03e105ad-23b5-4b13-9f0a-61fc044854e1.png)
