### ISSUE TITLE
GET DHCP address of interface

### ISSUE THREAD

**Issue by MokkaSchnalle** [jaredhendrickson13/pfsense-api#207]
**Is your feature request related to existing pfSense functionality that is missing from the API? Please describe.**
status_interfaces.php in pfsense shows all interface stats and addresses.

**Describe the solution you'd like**
I would like to get the current IP address of DHCP interfaces.
Currently, this seems to be only possible for static addresses.

**Describe alternatives you've considered**
I am currently using a workaround via /status/log/dhcp with a grep filter:

`jqFilter=$(printf '[.data[] | select(contains("dhclient")) | select(contains("New IP Address (%s)"))][-1]' "${interface}")
curlRequest "GET" "/status/log/dhcp" | jq -c "$jqFilter" | grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}"`

**Comment by jaredhendrickson13** [comment]
Hey! 

An endpoint for this already exists. Use /api/v1/status/interface. (https://github.com/jaredhendrickson13/pfsense-api#1-read-interface-status)

Let me know if you have any issues using this endpoint. 

Thanks!

**Comment by MokkaSchnalle** [comment]
Hi!
Ooops, I overlooked that in the documentation.

Works flawlessly.
Thanks!
