### ISSUE TITLE
Problem obtaining API token

### ISSUE THREAD

**Issue by OptiAdriano** [jaredhendrickson13/pfsense-api#208]
Hello!

When i open the API menu on pfSense, change the autentication mode to "API Token" and save it, I can generate an API Token with no problem.

But the client-token hash that shows on the list is truncated, so I can't copy it to put into my application, and I've found no other ways to obtain it.

Any help is appreciated.

![image](https://user-images.githubusercontent.com/102375374/160154419-d04d38ae-8e5f-42e5-9134-6e2f54d7f08c.png)

**Comment by jaredhendrickson13** [comment]
Hey!

See #103. The actual API token is not saved after creation, only a hashed representation of the token. The actual token will appear on the green confirmation banner at the top of the screen after it's created initially.

Let me know if you have any further issues. 

Thanks!

**Comment by OptiAdriano** [comment]
Many thanks, that was some lack of attention from me. Haven't seen that.

I now have a token, and will keep trying to make the authentication work.

I tried authenticating using username and password, and it worked on GET requests, but on POST requests the same authentication kept returning "401 unauthorized". Now I need to try using tokens, let's see if I make it work this time.

![image](https://user-images.githubusercontent.com/102375374/160164802-d2f59097-175e-4341-a973-d07d65b6b56a.png)

Thanks for the work on this API!
