### ISSUE TITLE
Authentication on HTML body doesn't work for POST

### ISSUE THREAD

**Issue by OptiAdriano** [jaredhendrickson13/pfsense-api#211]
Hello!

I'm trying to use pfSense API using purely HTML and PHP, nothing more.

When I use "Local Database" authentication and add on HTML body the user credentials, they work fine for GET requests, but when I try to use the same credentials on POST requests, I receive a "401 Unauthorized" response.

I tried about using "API Token" autentication, but I can't find a way to insert an Authorization header on the HTTP request using only PHP. If I try to use a programming language like Delphi, where I can build the entire HTML header from scratch, I think I'll have no problem, but that's not my present situation.

Do I'm making something wrong or it's a bug? Follows an HTML example of what I'm doing.
```
<form action="<?php echo $url ?>/api/v1/services/dhcpd/lease" method="get">
  Obter concessões DHCP<BR>
  <input type="hidden" name="client-id" value="<?php echo $id_cliente ?>">
  <input type="hidden" name="client-token" value="<?php echo $token_cliente ?>">
  <input type="submit" value="Obter concessões DHCP">
</form>
<br>
<form action="<?php echo $url ?>/api/v1/firewall/rule" method="post">
  Bloquear IP na WAN<BR>
  <label for="src">Informe o IP a ser bloqueado: </label>
  <input type="text" id="src" name="src"><br>
  <input type="hidden" name="client-id" value="<?php echo $id_cliente ?>">
  <input type="hidden" name="client-token" value="<?php echo $token_cliente ?>">

  <input type="hidden" name="type" value="block">
  <input type="hidden" name="interface" value="wan">
  <input type="hidden" name="ipprotocol" value="inet">
  <input type="hidden" name="protocol" value="any">
  <input type="hidden" name="dst" value="any">
  <input type="hidden" name="descr" value="Regra adicionada pelo teste de API">
  <input type="hidden" name="top" value="true">
  <input type="hidden" name="apply" value="true">
  <input type="submit" value="Bloquear IP">
</form>
```

**Comment by crawc** [comment]
With CURL you can POST with headers, etc... 

You would add your API Authorization after line 21 of this example below.
`'Authorization: 6abcd123 abc123e6kva9wfzq8rnu4ce6kva9wfzq8rnu4ce6kva9wfzq8rnu4ce6kva9wfzq8rnu4c',`

Example: https://www.tutsmake.com/php-curl-post-request-example/

**Comment by jaredhendrickson13** [comment]
There are a few issues with having an HTML form interact with the API directly. 

Firstly, the API is primarily designed to work with the `application/json` content type. I don't believe there is a way for an HTML form to submit form data as JSON without the use of JavaScript. You could try to change your form to use `enctype="application/x-www-form-urlencoded"` to allow the API to accept the credentials at least, but even then you will likely have validation issues with boolean or integer type fields as they will all be sent as strings. Additionally, the `client-id` and `client-token` field for the API token authentication method will soon be deprecated so it's probably not the best approach. 

Secondly, HTML and JavaScript will likely disclose your API tokens on the frontend as they will be viewable by the client. Maybe that's not a concern in your specific use case, but could be serious security issue.

My recommendation would be as @crawc suggests, have the HTML form call PHP to use CURL to make the request. You will have full control over content and data types as well as full control over HTTP headers sent in the request. You will also be able to prevent the API tokens from being disclosed in the HTML. 

Hope this helps.

**Comment by OptiAdriano** [comment]
Hello!

Thanks on your reply. Well, your reasoning is valid, so I will try this approach. Make things more complex, more points of failure, and the simpler solution is always desirable.

But let's make it work first.

Many thanks!
