### ISSUE TITLE
Create Interface does not enable or apply

### ISSUE THREAD

**Issue by rainiur** [jaredhendrickson13/pfsense-api#215]
I have create a VLAN via the API and then attempted to create an interface. It creates the interface but will not enable or apply the interface.

{
    "if": "vtnet1.2032",
    "descr": "Test2",
    "enable": "",
    "type": "staticv4",
    "ipaddr": "192.168.32.1",
    "subnet": "24",
    "apply": ""
}

**Comment by rainiur** [comment]
I was able to get this fixed by changing line 63 in  /etc/inc/api/models/APIInterfaceCreate.inc

        // if ($this->initial_data["enable"] === true) {
        if (isset(initial_data["enable"])) {

**Comment by jaredhendrickson13** [comment]
This would be expected since both the `enable` and `apply` fields need to be passed in as booleans in the request body. For example:

```json 
{
  "if": "vtnet1.2032",
  "descr": "Test2",
  "enable": true,
  "type": "staticv4",
  "ipaddr": "192.168.32.1",
  "subnet": "24",
  "apply": true
}
```

**Comment by rainiur** [comment]
Thank you that answered my question perfectly.
