### ISSUE TITLE
All Interfaces not Showing

### ISSUE THREAD

**Issue by rainiur** [jaredhendrickson13/pfsense-api#216]
I am not sure if this is a bug or feature request.

An interface which is not configure but is available does not show on the interface API request. Should they be there or am I missing something?

**Comment by rainiur** [comment]
Figured I would add this as well to better clarify. Is there a means through the API to get all available network ports?

**Comment by jaredhendrickson13** [comment]
Currently, no. You might be able to accomplish this by using the /api/v1/diagnostics/command_prompt endpoint to call `ifconfig` to read all interfaces and something like `grep` to search for the specific interface IDs. 

I'll keep this open as a feature request for now. This should be simple enough to squeeze into a patch in the near future.
