### ISSUE TITLE
API /v1/user GET returns empty data

### ISSUE THREAD

**Issue by wangnanlena** [jaredhendrickson13/pfsense-api#217]
cannot see any actual data in the response.
tried http and https, captured packets in http mode.

**Comment by jaredhendrickson13** [comment]
Tests for this endpoint are passing and I'm not able to replicate this on my local instance. Can you provide the request you are trying?

**Comment by jaredhendrickson13** [comment]
Stale issue. Closing for now. Feel free to re-open if additional information can be provided.
