### ISSUE TITLE
API Token only works for Local Users

### ISSUE THREAD

**Issue by tyron** [jaredhendrickson13/pfsense-api#22]
I was able to generate an API Token with my LDAP user, but attempts to authenticate against the API failed. I finally created a Local User and tested and it works. So I guess this doesn't support LDAP users?

If that's the case, I suggest updating the documentation to reflect that.

**Comment by jaredhendrickson13** [comment]
Hi there, 

You are correct. A local database user is required. This is stated under the requirements section in the documentation. LDAP and RADIUS authentication servers are not supported.

**Comment by tyron** [comment]
Hey, thanks for replying. I didn't find this information neither here https://github.com/jaredhendrickson13/pfsense-api/blob/master/README.md#requirements or https://github.com/jaredhendrickson13/pfsense-api/blob/master/docs/documentation.json , so that's why I suggested adding to one of them.

**Comment by jaredhendrickson13** [comment]
The second item under the requirements section does state `pfSense API requires a local user account in pfSense. The same permissions required to make configurations in the webConfigurator are required to make calls to the API endpoints`. I will however add a snippet under the authentication section in the documentation that makes this requirement more transparent. Thanks for bringing this up.
