### ISSUE TITLE
make_package fails on freebsd 12

### ISSUE THREAD

**Issue by wuarmin** [jaredhendrickson13/pfsense-api#236]
**Describe the bug**
If I try to call `make_package` on pfsense (freebsd 12), I get the following error:

```txt
make: "/usr/share/mk/bsd.port.mk" line 32: Cannot open /usr/ports/Mk/bsd.port.mk
make: Fatal errors encountered -- cannot continue
make: stopped in /root/build/pfsense-api/pfSense-pkg-AP
```

**To Reproduce**
```txt
python3.8 tools/make_package.py --branch master --tag 1.4.2 --freebsd 12
make: "/usr/share/mk/bsd.port.mk" line 32: Cannot open /usr/ports/Mk/bsd.port.mk
make: Fatal errors encountered -- cannot continue
make: stopped in /root/build/pfsense-api/pfSense-pkg-AP
```

**Expected behavior**
Successful package creation, to run E2E tests and test new endpoint

**pfSense Version & Package Version:**
 - pfSense Version: 2.6.0-RELEASE
 - Package Version [e.g. v1.4.2]
 - freebsd  12.3-STABLE

**Comment by mitch40** [comment]
@wuarmin i had the same error with a fresh install of freebsd.
Execute this command before make package:
`portsnap fetch extract`

**Comment by wuarmin** [comment]
@mitch40 thanks. If I execute it, I get:

`portsnap: Command not found.`

**Comment by mitch40** [comment]
@wuarmin , sorry i forget to indicate you have to execute this command as root.

**Comment by wuarmin** [comment]
@mitch40 switching to root makes no diff. it seems that `portsnap` is not present on my system.

**Comment by jaredhendrickson13** [comment]
@wuarmin Are you trying to build the package directly on pfSense? If so, that would be the problem. The package needs to be built on a standalone FreeBSD instance as pfSense intentionally does not include the ports tree or build environments.

**Comment by wuarmin** [comment]
@jaredhendrickson13 Thank you! Yes I tried it on pfSense directly.  That explains a lot. So now we will set up a standalone FreeBSD and try it again. I'll probably get back to you with a PR if that's all right with you.

**Comment by wuarmin** [comment]
On a standalone FreeBSD environment it now worked perfectly.

Thank you for the help
