### ISSUE TITLE
Unable to retrieve pfSense Config 

### ISSUE THREAD

**Issue by jamesjose03** [jaredhendrickson13/pfsense-api#240]
**Describe the bug**
Once the pfSense Config is updated using the PUT request /api/v1/system/config, the other APIs returns the HTML of pfSense login page.

**To Reproduce**
1. Get access token using /api/v1/access_token
2. Get the current pfSense Config using api/v1/system/config
3. Use the config received as response from step 2 in the PUT request /api/v1/system/config
4. After successful PUT request is made, the APIs from step 1-3 return the HTML login page of pfSense UI.

**Expected behavior**
The updated config must be received as response from the APIs. Instead, HTML is being returned.

**Screenshots or Response**
![Screenshot_2022-06-01-11-31-19-90_f56466bc4bb61e6d2de1f3b0468a89d9](https://user-images.githubusercontent.com/31133182/171338001-af0ff867-0926-4c38-84ec-35800e667c04.jpg)

**pfSense Version & Package Version:**
 - pfSense Version: 2.5.1
 - Package Version v1.4.2

**Affected Endpoints:**
 - URL: /api/v1/system/config (PUT, GET)
 - /api/v1/access_token

**Additional context**
Tried updating the pfSense Config using the APIs. Not able to fetch the updated config after the PUT request. The config.xml is updated inside the pfSense VM.

**Comment by wuarmin** [comment]
What's the expiration time of your JWT token?

**Comment by jamesjose03** [comment]
Oops. Seems the issue was from my side. The config was not properly formatted. Anyways, keep up the good work😁. 
Closing the issue
