### ISSUE TITLE
What about IPsec? Is that on roadmap?

### ISSUE THREAD

**Issue by LeartBeqiraj** [jaredhendrickson13/pfsense-api#245]
It would be great if I could access PFsense IPsec service through API from my application.

**Comment by viganraca** [comment]
It sounds good and would be appreciate providing of the API for IPsec. 

Hopefully in one of the next version, Pfsense will make it happen!

**Comment by arikodelabs** [comment]
I vouch for this idea too!

**Comment by ddt154** [comment]
Agreed- IPSEC would be a great addition
