### ISSUE TITLE
Typo in documentation for /sytem/api

### ISSUE THREAD

**Issue by robindbe** [jaredhendrickson13/pfsense-api#246]
**Describe the bug**
This is a very minor typo but nonetheless.

The documentation for the PUT request in /api/v1/system/api says the parameter to set the listening interface is called `available_interfaces` but it's actually `allowed_interfaces`.

**To Reproduce**
Go to documentation page `https://hostname/api/documentation/#/System%20%3E%20API/put_api_v1_system_api`

**pfSense Version & Package Version:**
 - pfSense Version: 2.6.0
 - Package Version 1.4.2

**Affected Endpoints:**
 - URL: /api/v1/system/api

**Comment by jaredhendrickson13** [comment]
Thanks for pointing this out. I'll get this corrected right away.
