### ISSUE TITLE
Bad request on PUT or POST certificate

### ISSUE THREAD

**Issue by alyarb** [jaredhendrickson13/pfsense-api#249]
I'm hoping someone can get a working example JSON of this API command. 

First, I GET the system config to figure out which certificate refid is being used by the webConfigurator.
Then I GET that certificate to examine the formatting of the output JSON... all that works.
Now, I want to PUT new key/certificate PEM data to that same refid and I get bad request, both in the interactive test thing on the Documentation page as well as my curl / powershell environments.

All line breaks and -----BEGIN PRIVATE KEY----- start/end strings are removed so it's just the raw PEM data, no different from the output of the GET command.

The response from the server after a PUT is

```
 {
  "status": "bad request",
  "code": 400,
  "return": 1009,
  "message": "Could not locate system certificate",
  "data": []
}
```

Hoping someone has successfully used this command and has some guidance. Thanks!

**Comment by alyarb** [comment]
Similarly when trying to POST a new certificate with active = true. I get 400 bad request, saying method is required, but I am clearly submitting with method = existing and also tried with method = import:

`curl -X 'POST' \
  'https://fw40.cx.mydomain.com:8080/api/v1/system/certificate' \
  -H 'accept: application/json' \
  -H 'Authorization: Basic YWRtaW46U0RDaDBzdGluZzIwMTE=' \
  -H 'Content-Type: application/json' \
  -d '{
    "active":  true,
    "method":  "import",
    "prv":  "MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDgkIaAcEey26yImhye9KELXXXXXg6QEfOMhFIbhiVC2UgxkoBBb2wu29Qh9bgSs0rziCBCC2BNfcXfhZHFp1kNpCamSEkXdxUJY/P8LmgJvKe9j7VnROVAiGEmPF6Kpye3uYvSE01NUsVaHol5E02RE7fM5GkaCXUoAK09HOngzXja1rW51QlexlrJgsYK0
S7Beta2Zd5OI0GDYVAiRGM1aztFzJxXXXXXufr7+UG114ZhUXT/w52qZHl1Uoj6xHQlUbUeW7j2gHCAlC+Ys8yA3M7Xajj0+7c1xyPdV+AhQ3jzGMOXg16U4PXbZj7LtunXtgamDQ832QQuGYksBpqJAgMBAAECggEADpf11bT2Q95YyQvS3lWhfZnq6jBjm+M+w5v5xgYit8RtF6OgqB/4lNb+YzKXwsdaEJeBGSmqGX8Z89u3THQCqotHY7k
A3wCDIngXbAUMB831zLDhJhPpHhd+0MXXXI8iWqM5Pe65MFQ3tRKU9oRVnx7769nQJrwEnBPnLjiJzm0MyKPotbJpM/6t19xbW2t+QxZAk9PmCwdZQi2YojEGCWUi65lSmYOK5ScWz3XMNonrGaYa6odQ8wCfx8OrvDVS/5bRbmrfaMtBJy4wRb4jO35Q+wH3gwSRssiWzhl6wKy86guNxXcBnb0nwXXXXXaV18cxmfJtXPzO5e1nyafYPQKBg
QD1QbzlIOyC4lDMF5s5Rc2l51snNBFL/w+8Cf3T5t9yb6s5bLebtC71k7I5dqXNVgR9jLyBrlZ8snwCJLPVECQc5p8HovPVzC4iltNJi3qYhQnASQqr3yQYG1B4If4Y0kyuqxPU6okkAaT4un4m7PjNj5WRmGo1lfX0cu19bUKu5wKBgQDqZr+xH9fxCIXXXXVkRSxOkpB354YMVR+lXB/vaXXXsCktYdAqsEbHmvDqyDCNLb8Zr8iMnZG0xxx
ICBpBPNm7RRSXphBwzMDoAP6plk4fRMM4T83RbdXlOmx6KVTMaIphSSIYgn6U7srlXFph8qSdIafMM5AEhkl+C5QMw2ptDwKBgHRcqjiz9ELtCZSrppP30GhkalUhWQuLinWW7/03ztBGtyBZuot/Y8BUQP0Ok//mTd8bhNyqUJJ9RGTn8QKn09p6eP1wjOvlIgZ7NOfx60qt5EB85zlAd6mQXA+DYUF5lbRRquXXXdEljpYMNYpWaH1vIHGht
NKTwcwnMxKNYlQFAoGAIeKMn4xc6Sk0EdDMWZxuVUV2wP6lMC82De+NZky0O4TDzx2uvB0TflN1tFsQObh9QbdZpIo6wAZdu32AXiHvz9Sir3GAOu4+jMtoBRgHXxnPptpShI3+N88EU3yaF5qdNocd+LEUn28Nwa5iGnq7NUPiP/DMRvsqsJ/33Qh6XXXCgYEAkFP94qIzSRE1ZHRJ8umato8MmmQ2vWjGEDtfdZxj0nd50LRx1zMxb5P6ho+
okghO27srwEcl+nZnA8nRMsWm3EQRMfDuu8LN4gZoAg4SZszR5lnegGo2AhKd0qmQNFasq6KC2YZKIlXtgAcAZjH+NYdNt0Ekg5Yby1/ZaVaY/SY=",
    "descr":  "SDC ACME",
    "crt":  "MIIFLjCCBBagAwIBAgISBJjqc8u1cYzKzAhn3hXXXXXFMA0GCSqGSIb3DQEBCwUAMDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQDEwJSMzAeFw0yMjA2MjIxODI3MDdaFw0yMjA5MjAxODI3MDZaMB8xHTAbBgNVBAMMFCouYzMuc2RjLWhvc3RpbmcuY29tMIIBIjANBgkqhkiG9w0BA
QEFAAOCAQ8AMIIBCgKCAQEA4JCGgHBHstusiJocnvShCxWcG14OkBHzjIRSG4YlQtlIMZKAQW9sLtvUIfW4ErNK84ggQgtgTX3F34WRxadZDaQmpkhJF3cVCWPz/C5oCbynvY+1Z0TlQIhhJjxeiqcnt7mL0hNNTVLFWh6JeRNNkRO3zORpGgl1KACtPRzp4M142ta1udUJXsZayYLGCtEuwXrWtmXeTiNBg2FQIkRjNWs7RcycTpbSrrn6+/l
BtdeGYVF0/8OdqmR5dVKI+sR0JVG1Hlu49oBwgJQvmXXXXXzO12o49Pu3Nccj3VfgIUN48xjDl4NelOD122Y+y7bp17YGpg0PN9kELhmJLAaaiQIDAQABo4ICTzCCAkswDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBTKzC8M1wdlkZIYGpgoogV3Dv5ZwjAfB
gNVHSMEGDAWgBQULrMXt1hWy65QCUDmH6+dixTCxjBVBggrBgEFBQcBAQRJMEcwIQYIKwYBBQXXXXXXXWh0dHA6Ly9yMy5vLmxlbmNyLm9yZzAiBggrBgEFBQcwAoYWaHR0cDovL3IzLmkubGVuY3Iub3JnLzAfBgNVHREEGDAWghQqLmMzLnNkYy1ob3N0aW5nLmNvbTBMBgXXXXXERTBDMAgGBmeBDAECATA3BgsrBgEEAYLfEwEBATAoMCY
GCCsGAQUFBwIBFhpodHRwOi8vY3BzLmxldHNlbmNyeXB0Lm9yZzCCAQQGCXXXXXXB1nkCBAIEgfUEgfIA8AB2AN+lXqtogk8fbK3uuF9OPlrqzaISpGpejjsSwCBEXCpzAAABgYzh9V0AAAQDAEcwRQIhAKdAKeOB6MnHXdoPabpOnoK4hkRtq4fUqNe7NsxgKz5RAiB/Ms9RRuwpL9BoRp2ZK27V955sAQJ4Zyen9UA2AMqU/QB2AEalVet1+
pEgMLWiiWn0830RLEF0vv1JuIWr8vxw/m1HAAABgYzh9YEAAAQDAEcwRQIhAPSHT52/EJmz6098xMYFwuE3SQwP1Tr5L4aFEc075V0XAiBZOaA7MTc6duIcX7bSUtvrzGcsudPLSxj+YE5dJ0L8PjANBgkqhkiG9w0BAQsFAAOCAQEAEEld0yQTdGOci6XDc49gZDjZddprv2+Ck/5RIbYOYNg8B5Yw45QIkpB2YwmTTOx1I4JWlYsVBzqWiWt
ZMthhKoq3vR1X1fuhcfpehNCWPZTB/Jvs8JBzYobAK3c8q12OeQdUC3lq2c8Ffn1V/z/xWlErimsVlhLmuUWmKCfJgt+dO4BnOKHt4SE7GeHRtYMN6BlvSaSIqfRjFXzOpV5Py7EACv9mKO7D3LnYwFY3kxLM2cpFd33iimJD6iHJ8A3vjBFqp/xp4pW8FLQVGepIZQnquIodBr5gvKdRa2cpPs3G4tSegDObnnqcE4XPPh6wvgw1afYKw+prd
wjih1DWiQ=="
}'`


`{
  "status": "bad request",
  "code": 400,
  "return": 1031,
  "message": "Certificate management method is required",
  "data": []
}`

**Comment by alyarb** [comment]
I wasn't encoding the PEM data, sorry

**Comment by Bazz0r** [comment]
Hi Alyarb, I have the same issue, can you explain how you encoded the certificate data please?
