### ISSUE TITLE
complete uninstall?

### ISSUE THREAD

**Issue by somedevreally** [jaredhendrickson13/pfsense-api#25]
on pfsense 2.5 when i run 

> pkg delete pfSense-pkg-API

i still see API as sub menu in systems

**Comment by jaredhendrickson13** [comment]
Hey!

I can't seem to replicate this issue on a fresh install of pfSense 2.5 using the latest snapshot. When I run the `pkg delete` command all package files are removed and the API sub menu disappears from the UI as expected. If you could provide the version of pfSense-API and pfSense 2.5 you are using I can look into that a little further. If you are still needing to uninstall any remaining package files you can run the following commands to do so manually:

```
rm -rf /usr/local/www/api
rm -rf /etc/inc/api
rm -rf /etc/inc/php-jwt
rm -rf /usr/local/share/pfSense-pkg-API
rm /etc/inc/priv/api.priv.inc
rm /usr/local/pkg/api.xml
```

Thanks

**Comment by somedevreally** [comment]
ok so this is what happened.
when i installed the pkg, on next pfsense upgrade it removed unwanted pkg and thats how it left that menu.
so now even when i remove the pkg manually it didnt remove the menu
am using
 ``` 
2.5.0-DEVELOPMENT (amd64)
built on Wed Oct 21 
```
will use rm commands thanks

**Comment by jaredhendrickson13** [comment]
Thanks for the additional clarification. I will close this for now but feel free to reopen if this becomes a continual issue. I also wasn't able to replicate the exact issue when updating the pfSense 2.5 version so I'm assuming something went wrong during the update and the package wasn't removed completely. If this issue happens again, the `rm` commands above will manually remove the files installed by the package, or you can try to reinstall pfSense-API and then uninstall it using `pkg delete pfSense-pkg-API`.

**Comment by war59312** [comment]
`rm /usr/local/www/system_restapi_settings.php
`

Need to remove that as well FYI.
