### ISSUE TITLE
/api/v1/openvpn/csc Error 404

### ISSUE THREAD

**Issue by advancedluser** [jaredhendrickson13/pfsense-api#251]
When I try to GET or POST with curl, or from the api/documentation page, I am getting the following error:
`<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

`

And basically the same with curl:
curl -k -H "Authorization: xxxxxxxx xxxxxx" -H "Content-Type: application/json" -X GET https://xxxxxx:xxxx/api/v1/openvpn/csc -d @post_csc.json
`
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
`

The other GET and POST requests that I used so far worked. What could be the issue? Am I doing something wrong?

**pfSense Version & Package Version:**
 - pfSense Version: 2.6.0
 - Package Version: 1.4.2

**Affected Endpoints:**
 - URL: /api/v1/openvpn/csc

**Comment by jaredhendrickson13** [comment]
Looks like this is a documentation discrepancy. The endpoint URL is actually /api/v1/services/openvpn/csc. 

I'll correct that in the next release branch. 

Thanks!

**Comment by advancedluser** [comment]
Thank you very much for the fast reply @jaredhendrickson13, works now!
