### ISSUE TITLE
PUT /api/v1/firewall/alias update alias

### ISSUE THREAD

**Issue by s1mHATs** [jaredhendrickson13/pfsense-api#252]
Hi, How can i add more hosts to alias with PUT without changing the previous values already in alias.
My Alias has 1 IP:  `1.1.1.1`
Commands that I use:
```shell
curl -u admin:pfsense -k -XPUT https://192.168.106.100/api/v1/firewall/alias \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "address": [
    "4.4.4.4"
  ],
  "apply": true,
  "descr": "Updated Blacklists",
  "detail": [
    "test"
  ],
  "id": "Updated_Blacklists",
  "name": "Updated_Blacklists",
  "type": "host"
}'
```
**pfSense Version & Package Version:**
* pfSense Version: 2.6.0
* Package Version: 1.4.2

**Comment by jaredhendrickson13** [comment]
Hey!

A PUT to that endpoint will always replace the existing alias. Instead, you can use a POST request to the /api/v1/firewall/alias/entry endpoint to simply append additional alias address entries. Here's an example of an API call to append the IPs `127.0.0.2` and `127.0.0.3` to an existing alias named `EXAMPLE_ALIAS` that already has `127.0.0.1` configured as an alias address:

```
curl -X 'POST' \
  'https://127.0.0.1/api/v1/firewall/alias/entry' \
  -H 'accept: application/json' \
  -H 'Authorization: Basic XXXXXXXXXXXXX' \
  -H 'Content-Type: application/json' \
  -d '{
   "name": "EXAMPLE_ALIAS"
  "address": ["127.0.0.2", "127.0.0.3"],
  "apply": true
}'
```

Which would return:

```json
{
  "status": "ok",
  "code": 200,
  "return": 0,
  "message": "Success",
  "data": {
    "name": "EXAMPLE_ALIAS",
    "type": "host",
    "descr": "",
    "address": "127.0.0.1 127.0.0.2 127.0.0.3",
    "detail": "Entry added Sun, 26 Jun 2022 23:06:48 -0600||Entry added Sun, 26 Jun 2022 23:07:26 -0600||Entry added Sun, 26 Jun 2022 23:07:26 -0600"
  }
}
```

Hope this helps.

Thanks!

**Comment by s1mHATs** [comment]
Thank you very much for the fast reply @jaredhendrickson13, works now! You are so enthusiastic
