### ISSUE TITLE
Configure Gateway Group via API

### ISSUE THREAD

**Issue by AAGEM** [jaredhendrickson13/pfsense-api#261]
**Is your feature request related to existing pfSense functionality that is missing from the API? Please describe.**
We would like to configure the Default Gateway used by psfense.
Select a Gateway Group via API among those previously configured in pfsense.

This action is only possible via GUI through System / Routing / Gateways by selecting the Default Gateway IPv4.

Thanks

**Comment by jaredhendrickson13** [comment]
Duplicate/to be implemented by #189.
