### ISSUE TITLE
Would be great if api would also support the add-on 'bind dns server' package.

### ISSUE THREAD

**Issue by ddt154** [jaredhendrickson13/pfsense-api#276]
**Is your feature request related to existing pfSense functionality that is missing from the API? Please describe.**
A URL or documentation about the requested functionality. Ex. /firewall_rule.php [...]
/pkg_edit.php?xml=bind.xml

**Is your feature request related to a problem? Please describe.**
Not related to a problem.  Would just love to be able to configure bind dns via api

**Describe the solution you'd like**
Would be great to managed:
  - Bind DNS server settings
  - Managed ACLs/Views
  - Create/Update/Delete DNS Zones

**Describe alternatives you've considered**
I have floated the idea of doing 'bind dns' or other dns server package in a container, but still looking for a good GUI and API interface solution.

**Additional context**

**Comment by sjafferali** [comment]
+1 As a user of the bind package, I would love to see this supported as well.

**Comment by totik234** [comment]
+1

**Comment by sjafferali** [comment]
@jaredhendrickson13 Thanks for all your work on this project!

Is there any chance this can be implemented in v2.0.0?  Being able to modify DNS records using the API would be very useful.

**Comment by jaredhendrickson13** [comment]
@sjafferali It's possible. I haven't looked too much into how much work it will take to develop endpoints for BIND yet. However, assuming the remainder of v2's development goes smoothly, I'm certainly open to adding more features like this. My priority at the moment is reaching feature parity with v1 and completing the features I've already committed to; both of which are about 80% done, I'd estimate. Even if BIND is not included in the initial v2.0.0 release, it will likely be prioritized in a release shortly after, as it has been requested quite often. I'll be sure to update this issue once it's planned for a release.
