### ISSUE TITLE
API token field width

### ISSUE THREAD

**Issue by stasstryukov** [jaredhendrickson13/pfsense-api#279]
**Describe the bug**
When I'm generating token some part of it is replacing with '...'
So I cant use it.

**To Reproduce**
1. Go to 'API'
2. Click on 'Authentication mode', select API Token and press save
3. Scroll down to the buttom of page and press 'Generate'
4. See the result

**Expected behavior**
Full API key token hash

**Screenshots or Response**
https://ibb.co/0thYD6N

**pfSense Version & Package Version:**
 - pfSense Version: [e.g. pfSense 2.6.0]
 - Package Version [e.g. v1.4.3]

**Comment by jaredhendrickson13** [comment]
Hey!

Take a look at #103, this should help solve your problem. Let me know if you have any further issues. 

Thanks!
