### ISSUE TITLE
Monitoring Support

### ISSUE THREAD

**Issue by cmacnichol** [jaredhendrickson13/pfsense-api#28]
First of all, thank you for all of your work on this.  I was about ready to give up on my pFSense installation just because of the lack of ability to program it remotely from other systems.

Do you have any plans to add any kind of status monitoring to the API?  I am thinking primarily of status's for the individual gateway interfaces.  There are others that could be useful, but that is the primary one.  I find the notification abilities of pFSense to be pretty lacking on connection issues and would much prefer to monitor it from other systems.

**Comment by jaredhendrickson13** [comment]
Hi!

Yes I do plan on adding more endpoints intended for monitoring. A gateway status endpoint is actually already in the works and will hopefully be included in the next release. This will allow you to pull the same metrics found in the gateway monitor built in to the UI from the API. I'll keep this issue open and update when I have it included in a pull request. 

Thanks!

**Comment by mwoolweaver** [comment]
@jaredhendrickson13 would it be possible to request DDNS stats?

**Comment by jaredhendrickson13** [comment]
@mwoolweaver 

I'm definitely happy to look into it. I will need to do a bit of research to determine if and when I could implement such a feature. Since this specific issue will be closed when the gateway monitoring features are merged to master, would you mind opening a separate issue for the DDNS stats in the meantime?

Thanks!

**Comment by mwoolweaver** [comment]
> would you mind opening a separate issue for the DDNS stats in the meantime?


I will! 

> Thanks!
