### ISSUE TITLE
Assigning interface via API

### ISSUE THREAD

**Issue by hongjiwei** [jaredhendrickson13/pfsense-api#280]
**Is your feature request related to existing pfSense functionality that is missing from the API? Please describe.**
Ans: Yes, I can assign interface via web ui and the page is interfaces_assign.php.

**Is your feature request related to a problem? Please describe.**
Ans:  Yes, It is.

**Describe the solution you'd like**
Ans: It would be great if I can assign interfaces via API and get the information from response. :) 

**Describe alternatives you've considered**
Ans: I used to try executing some command via shell. It could assign interfaces step by step, but it's very hard to be integrated with other platform.

**Additional context**
<img width="1188" alt="image" src="https://user-images.githubusercontent.com/43867449/191047136-7cf64a98-5a1d-44ef-a594-d2ad5a44b35e.png">

**Comment by jaredhendrickson13** [comment]
Hey!

You can use the /api/v1/interface endpoint to do this. This endpoint will allow you to add new interface configurations and read, update or delete existing interface configurations. You can refer to the embedded API documentation within the pfSense UI after the API package is installed by navigating to System > API > Documentation and looking for the docs on the /api/v1/interface endpoints. 

Let me know if you have any trouble.

Thanks!

**Comment by hongjiwei** [comment]
Thanks for your kind help! It works find :)
I have other questions, how can i get the interface ID? 
I try to update interface with /api/v1/interface, but it shows message "Interface ID is required"...

**Comment by jaredhendrickson13** [comment]
The interface ID is simply the name of the interface you are trying to update. You could also use the physical interface interface ID (e.g. `vmx1`) or the pfSense internal interface ID (e.g. `wan`, `lan`, `opt1`, `opt2`, etc.) if you would rather.

For example, if you wanted to update your LAN interface, set the `id` field in your request payload to `LAN`.

**Comment by hongjiwei** [comment]
Great, All of my questions have been solved :)

Thanks for your kind assistance!
