### ISSUE TITLE
Feature Request : Add / Edit / Delete NAT Entries

### ISSUE THREAD

**Issue by sf32738** [jaredhendrickson13/pfsense-api#29]
Currently, the API does not have capabilities to add/edit/delete NAT entries of the firewall.   Only Read is supported.
It would be nice to have this capability in the API has NAT is a highly used function of a firewall in our IPv4 (shortage) world.

**Comment by jaredhendrickson13** [comment]
Hey!

Thanks for the request. I agree NAT is a very important and much needed addition. I should be able to this feature implemented in the next release. I will update this issue when I have a pull request that includes these features. 

Thanks again!
