### ISSUE TITLE
Certs and key different when get from API

### ISSUE THREAD

**Issue by guiap** [jaredhendrickson13/pfsense-api#296]
When I get the cert and key of CA from API, It's different  from the pfsense site.

Pfsense Site:
![ca_from_pfsense](https://user-images.githubusercontent.com/47855142/201329139-10dc2bd0-789a-4bdb-972a-d40f0bfb8968.png)

API:

![ca_from_api](https://user-images.githubusercontent.com/47855142/201329143-cc960a0e-81e4-4280-ab7b-e77284faf2fa.png)

**pfSense Version & Package Version:**
 - pfSense Version: 2.6.0
 - Package Version 1.5.1 

**Affected Endpoints:**
 - URL: [/api/v1/system/ca]

**Comment by danielmichaels** [comment]
That looks like base64. Can you try decoding it and seeing if the matches.

```
# I only tried the first few characters to prove this, and already you can see.
LS0tLS1CRUd
# returns
-----BEG
```

Try this [page](https://www.base64decode.org)
or `base64 --decode` in the terminal

**Comment by guiap** [comment]
Hello, thanks, works fine.
