### ISSUE TITLE
Authentication error for user 'unknown' via PowerShell

### ISSUE THREAD

**Issue by NorskNoobing** [jaredhendrickson13/pfsense-api#306]
**Describe the bug**
Getting the 401 Unauthorized error when using the correct username and password. The pfSense logs says `authentication error for user 'unknown' from: IP`. It seems like the API won't accept the credentials from PowerShell.

Here's the script:
```powershell
$Bytes = [Text.Encoding]::UTF8.GetBytes("admin:pfsense")
$b64Creds = [Convert]::ToBase64String($Bytes)
$Uri = "10.0.10.1/api/v1/firewall/rule"
$Splat = @{
    "Uri" = $Uri
    "Method" = "GET"
    "Headers" = @{
        "Accept" = "application/json"
        "Content-Type" = "application/json"
        "Authorization" = "Basic $b64Creds"
    }
}
Invoke-RestMethod @Splat
```
Here's the [documentation](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-restmethod?view=powershell-7.3#-authentication) on how the feature works in PowerShell 7.3, but this should be the same for PowerShell 5.1 which is installed by default in Windows.

Note that you'll also need to run [this script](https://gist.github.com/jmassardo/2e0dd7cce292f16ff8f6945b8b3752b5) line 1-14 if you have a self-signed SSL cert on your pfSense install.

**To Reproduce**
1. Open Windows PowerShell (v5.1) on any of the computers that has access to the pfSense webConfig. It's installed by default in Windows, so you can just search for it using Windows search.
2. Run [this script](https://gist.github.com/jmassardo/2e0dd7cce292f16ff8f6945b8b3752b5) line 1-14
3. Run the script that I've put in the description. Note that you'll need to change the username and password at the end of line 1 and change the IP on line 3.

**Expected behavior**
The script authorizing correctly.

**Screenshots or Response**
PowerShell invocation and response:
![image](https://user-images.githubusercontent.com/39239702/212579736-d820b816-73c5-41b6-b9c1-2d81ba8d7fdb.png)
pfSense log:
![image](https://user-images.githubusercontent.com/39239702/212579789-303512a0-6d5c-4c2e-ac5e-6f94c6b0baac.png)

**pfSense Version & Package Version:**
 - pfSense Version: 2.6.0
 - Package Version v1.5.1

**Affected Endpoints:**
 All

**Comment by jaredhendrickson13** [comment]
Hey!

Have you disabled HTTPS in your pfSense instance? If not, you will probably need to prefix `https://` to your `$Uri` variable, or run `Invoke-RestMethod @Splat -PreserveAuthorizationOnRedirect` to prevent Powershell from stripping the authorization header when it hits pfSense's default HTTP redirect.

Let me know if you still have trouble.

Thanks!

**Comment by NorskNoobing** [comment]
Yup, seems like that's the issue. I tried in PowerShell 7 with the PreserveAuthorizationOnRedirect param, and it worked. I'm yet to find a solution in PSv5.1, but I'm guessing I'll have to use .NET

**Comment by NorskNoobing** [comment]
> Hey!
> 
> Have you disabled HTTPS in your pfSense instance? If not, you will probably need to prefix `https://` to your `$Uri` variable, or run `Invoke-RestMethod @Splat -PreserveAuthorizationOnRedirect` to prevent Powershell from stripping the authorization header when it hits pfSense's default HTTP redirect.
> 
> Let me know if you still have trouble.
> 
> Thanks!

Seems like you don't get the error messages from the API through the redirect either. Everything's fixed after just appending `https://` to the url
