### ISSUE TITLE
Create firewall rule with inverted bool

### ISSUE THREAD

**Issue by NorskNoobing** [jaredhendrickson13/pfsense-api#309]
I was wondering if there's any way to create a firewall rule with inverted match for the destination host?
![image](https://user-images.githubusercontent.com/39239702/213007679-c1de1595-7252-4373-bd7f-2caf5dbfa6f0.png)

**Comment by jaredhendrickson13** [comment]
Yes, there is. You can prefix `!` to your source or destination to invert the context of the rule. For example:

```
POST /api/v1/firewall/rule
{
    "type": "pass",
    "interface": "lan",
    "ipprotocol": "inet",
    "protocol": "tcp",
    "src": "!1.2.3.4",
    "srcport": "any",
    "dst": "!4.3.2.1",
    "dstport": "443"
}
```

**Comment by NorskNoobing** [comment]
Thanks for the quick response :) I was also wondering if there's any way to set DHCP relay? I can't see anything about that in the API docs.

**Comment by jaredhendrickson13** [comment]
There's not an API for the DHCP relay currently. There is an open feature request (#121) for this however. New features currently aren't being planned at the moment in preparation of pfSense 2.7.0, but once that is released that could be worked on.

**Comment by NorskNoobing** [comment]
Thanks, I've commented on the issue :)
