### ISSUE TITLE
[Feature Request] DDNS read, add, edit, remove endpoints

### ISSUE THREAD

**Issue by mwoolweaver** [jaredhendrickson13/pfsense-api#31]
All of those wouldn't be necessary just sounded better and more complete request with all 4.

**Comment by jaredhendrickson13** [comment]
Thanks for adding this issue. I had some time to look into this earlier this week. A simple endpoint to read and delete DDNS configuration and statuses would be fairly easy to implement. Creating and updating DDNS configuration however will be something that will take quite a bit of work. Each DDNS provider requires slightly different input validation. As a start, I will work on a read-only endpoint to pull DDNS data and implement the create, update and delete functions in a later release.

**Comment by mwoolweaver** [comment]
> As a start, I will work on a read-only endpoint to pull DDNS data

you are amazing

**Comment by mwoolweaver** [comment]
Also is there a way for me (or anyone else) to test #23?

**Comment by jaredhendrickson13** [comment]
Sure, I've just uploaded a test/beta build of v1.1.0 to the pull request. The build functions but may be missing a few things. Feel free to give it a try if you'd like.
