### ISSUE TITLE
IPsec rules from API not possible

### ISSUE THREAD

**Issue by Purpete** [jaredhendrickson13/pfsense-api#321]
Hello.
I'm testing the api and it's wonderful. Great job. But I have noticed that it is not possible to create ipsec type firewall rules through the API. It always gives me the unknown interface error. On the other hand, I can do lan and wan without problems. Any way to fix this?

**pfSense Version & Package Version:**
 - pfSense Version: [e.g. pfSense 2.6.0]
 - Package Version [e.g. v1.5.1]

**Affected Endpoints:**
 - URL: [ /api/v1/firewall/rule]

**Comment by jaredhendrickson13** [comment]
Hey!

You can use IPsec's ifconfig interface ID `enc0` as the `interface` value in your request to create, update and delete IPsec firewall rules. Let me know if you have any further issues. 

Thanks!

**Comment by Purpete** [comment]
thank you! I'll put it to the test tomorrow!

**Comment by jaredhendrickson13** [comment]
You can set the POST /api/v1/services/ipsec/apply endpoint's `initiate` field to `true` to trigger the P1 and P2 connect for _all_ enabled P1 and P2 entries.

![Screen Shot 2023-02-24 at 12 49 31 PM](https://user-images.githubusercontent.com/50180862/221277085-21407873-477b-49b5-95a1-c3fd2bc2a78e.png)
