### ISSUE TITLE
Broken filter after updating outbound NAT mapping

### ISSUE THREAD

**Issue by KenDFish** [jaredhendrickson13/pfsense-api#327]
I'm trying to use the API on our pfSense (22.05) to update an existing NAT outbound mapping. The mapping is quite specific: it's for all outbound UDP traffic from a range of ports on a specific IP address.

pfSense seems a little strange for outbound rules in that, using the normal UI, the port range needs to be specified as `port1:port2`, rather than the more common `port1-port2`

![image](https://user-images.githubusercontent.com/6280435/223127256-17571276-782b-455e-80c5-7ab11be58fb6.png)

So I sent this `PUT` request to /api/v1/firewall/nat/outbound/mapping
```

{
  "apply": false,
  "descr": "Outbound rule",
  "src": "10.200.40.132/32",
  "srcport": "30000:50000",
  "dst": "any",
  "dstport": "any",
  "target": "1.2.3.4",
  "id": "1",
  "protocol": "udp",  
  "top": false,
  "type": "pass"
}

```
This is accepted; however, if I then do a `GET` to re-read the rules, the filter has been changed to
```
 {
            "source": {
                "network": "10.200.40.132/32"
            },
            "sourceport": "30000-50000",
```

... the `sourceport` has been changed from `30000:50000` to `30000-50000`. Therefore, applying the rules (either via the API or via the UI) causes an error with the filter reload

`There were error(s) loading the rules: /tmp/rules.debug:59: unknown port 30000-50000 - The line in question reads [59]: nat on $WAN inet proto udp from 10.200.40.109/32 port 30000-50000 to any -> 1.2.3.4/32  static-port # Outbound rule
`

How do I sent the update to pfSense via the API, without the `:` being changed to a `-` ?

**Comment by jaredhendrickson13** [comment]
Hey!

Thanks for reporting this issue. This looks to be a bug. The context which replaces `-` with `:` is reversed in the code here which is what is causing this issue:

https://github.com/jaredhendrickson13/pfsense-api/blob/0fea7a6d1d296bfd7f460ce5cab0a97e0d2236d9/pfSense-pkg-API/files/etc/inc/api/models/APIFirewallNATOutboundMappingCreate.inc#L226

I'll have a fix for this in the next patch.

Thanks!
