### ISSUE TITLE
How to add User Certificate

### ISSUE THREAD

**Issue by DTvGe45vc** [jaredhendrickson13/pfsense-api#34]
Hello

Help me please.
I try to add User Certificate with pfsense-api but all my certificates like Server.
How I can change it?

In API Docs I didn't find how to mark type of cert.

Thanks

**Comment by jaredhendrickson13** [comment]
Hi there,

Unfortunately, user certificates are not supported via the API at this time. This would likely take some time to implement, I will keep this issue open as a feature request to work on in a future release. Let me know if you have questions in the meantime. 

Thanks!

**Comment by VirtualSamuraii** [comment]
Hi Jared,

I wanted to thank you for you amazing work and this very useful API.
I'm also requesting this feature (creating and managing user certificates) it would be so awesome !
I have set up a VPN access (Remote SSL/TLS authentication) on one of my VLANs in order to grant access to CTF players on my website. I really need to automate the user certificates creation if my players want to generate and export their VPN Client file configuration.

**Comment by DTvGe45vc** [comment]
Also I would suggest you to think about API function of certificate revocation.
Thank you

**Comment by Boyban** [comment]
Hi, what is the progression of this issue ? 
We have the need of it, and we would like to know if we can contribute/help you to resolve this one

Regards,

**Comment by jaredhendrickson13** [comment]
Hey all,

I am committed to having this feature as well as enhanced certificate management support implemented in the next minor release (v1.3.0). There are a few prerequisites to implementing user certificates and certificate management, the big one potentially being resolved in #125 that I am currently reviewing. Once that is merged, the user certificate endpoint will be next. I am hoping to have this feature beta ready next month and v1.3.0 released early June 🤞🏻 

For those wishing to help move that release along quicker, feel free to checkout the [v1.3.0 pull request](https://github.com/jaredhendrickson13/pfsense-api/pull/115) to test out the features in the beta build and/or check the [v1.3.0 project board](https://github.com/jaredhendrickson13/pfsense-api/projects/3#card-57288054). If there is any work in the To Do section that you feel you can take up, let me know and I can assign the issue to you. Fork the repo and open a PR to merge the feature into the `v130` branch. There will likely be more items added to backlog of the project in the coming weeks.

Thanks!
