### ISSUE TITLE
23.01 - DHCP Table shows all leases online = false

### ISSUE THREAD

**Issue by wesshaw** [jaredhendrickson13/pfsense-api#340]
**Describe the bug**
Sorry if Issues are not allowed for pre-release but I figured it'd be helpful to know.  The DHCP table shows all leases as "online=false" even when things are online.  We use this pretty extensively to assign static IP addresses to devices plugged into specific ports on our switches... thousands of them.

**To Reproduce**
1. Go to /api/v1/services/dhcpd/lease?state=active
2. Observe all leases have the attribute "online=false"

**Expected behavior**
I would expect the devices that are online and accessible to have the attribute "online=true"

**Screenshots or Response**
`{
            "ip": "10.64.0.135",
            "type": "dynamic",
            "starts": "2023/04/17 15:09:13",
            "ends": "2023/04/17 17:09:13",
            "mac": "c8:05:06:00:17:f7",
            "online": false,
            "hostname": "host1",
            "state": "active"
        },
        {
            "ip": "10.64.0.149",
            "type": "dynamic",
            "starts": "2023/04/17 15:09:09",
            "ends": "2023/04/17 17:09:09",
            "mac": "c8:05:06:00:07:d6",
            "online": false,
            "hostname": "host2",
            "state": "active"
        },`

**pfSense Version & Package Version:**
 - pfSense Version: 23.01-RELEASE (amd64)
 - Package Version: https://github.com/jaredhendrickson13/pfsense-api/releases/download/v1.6.0_devc01a130595fc4edd1b/pfSense-23.01-pkg-API.pkg

**Affected Endpoints:**
 - URL: /api/v1/services/dhcpd/lease

**Comment by jaredhendrickson13** [comment]
Hey!

Issues are definitely welcome for pre-releases! The internal identifier for online DHCP leases may have changed in pfSense so the API is no longer looking for the correct `online` identifier. Can you run the following command under 'Execute PHP Commands' in the Diagnostics > Command Prompt webConfigurator page and post the output here?

```php
var_dump(system_get_dhcpleases()["lease"]);
```

Feel free to scrub any sensitive values like IPs or MAC addresses. Mainly looking for what is shown in the `online` field.

Thanks!

**Comment by sjafferali** [comment]
@jaredhendrickson13 

Also hitting this issue. I have attached the output of `var_dump(system_get_dhcpleases()["lease"]);` only showing the `online` field. Let me know if this is not sufficient and I can massage the output further to include more of it. 

[output2.txt](https://github.com/jaredhendrickson13/pfsense-api/files/11548979/output2.txt)

**Comment by jaredhendrickson13** [comment]
@sjafferali thanks for providing that. I'll take a deeper look later today but I think I see the issue already. The keywords used for the `online` field have changed so the comparison the API makes no longer works. Seems like we'll need to make this a string field rather than a boolean.
