### ISSUE TITLE
Set expiration to "never" when creating a user via the API

### ISSUE THREAD

**Issue by svenfulen** [jaredhendrickson13/pfsense-api#348]
When creating a user in the Web interface, the password will not expire if you leave the expiration date is blank.  However, when I use the API and set the expiration to an empty string ("") it sets the expiration date to the current date.  Am I doing this API request incorrectly?

![image](https://github.com/jaredhendrickson13/pfsense-api/assets/73049985/bddca8c6-b1a4-4956-ab4e-4895e84a3c99)

I am currently setting the expiration date to 12/31/2050 as a workaround.

**Comment by jaredhendrickson13** [comment]
You can leave the `expires` field out of your request body entirely to prevent an expiration from being set. It is an optional field. 

Otherwise, the `expires` field can also be unset for an existing user by setting `expires` to a blank string in a PUT request.

Hope this helps!
