### ISSUE TITLE
[Feature Request] DHCPD non-static mappings

### ISSUE THREAD

**Issue by daimenworrall** [jaredhendrickson13/pfsense-api#35]
There are endpoints to retrieve static mappings, would it be possible to add an endpoint to get non-static mappings also?

Thank you.

**Comment by jaredhendrickson13** [comment]
Hey there,

Yes, I believe that should be a relatively simple addition. I will need to look into a bit more to be sure. I'm assuming you are looking for an endpoint that returns the data found on the Status > DHCP Leases page within the UI, is that correct?

Thanks!

**Comment by daimenworrall** [comment]
Yeah that's right, we can already get the static ones bit they dynamic / non-static ones would be quite useful too. 

Thank you.
