### ISSUE TITLE
DHCPd static mapping gateway updates not working

### ISSUE THREAD

**Issue by christianholzDE** [jaredhendrickson13/pfsense-api#351]
**Describe the bug**
Trying to use the PUT https://{pfSense_ip}/api/v1/services/dhcpd/static_mapping endpoint to update a static mapping with a different default GW does not change the mapping after 200 reply.

**To Reproduce**
1. Send PUT request to https://{pfsense_ip}/api/v1/services/dhcpd/static_mapping
2. Provide the following parameters in the PUT request: {'interface': 'lan', 'id': {valid_id_number}, 'item': {'id': {same_id_number}, 'mac': {mac}, 'cid': {cid}, 'ipaddr': '', 'hostname': {hostname}, 'descr': '', 'filename': '', 'rootpath': '', 'defaultleasetime': '', 'maxleasetime': '', 'dnsserver': [{list_of_dns_servers}], 'gateway': {new_gateway}, 'domain': '', 'domainsearchlist': '', 'ddnsdomain': '', 'ddnsdomainprimary': '', 'ddnsdomainsecondary': '', 'ddnsdomainkeyname': '', 'ddnsdomainkeyalgorithm': 'hmac-md5', 'ddnsdomainkey': '', 'tftp': '', 'ldap': '', 'nextserver': '', 'filename32': '', 'filename64': '', 'filename32arm': '', 'filename64arm': '', 'uefihttpboot': '', 'numberoptions': ''}}
3. Observe REST call return: response: 200, {"status":"ok","code":200,"return":0,"message":"Success","data":{original, unmodified data without changed gateway}

**Expected behavior**
The returned record should reflect the changed gateway or produce a corresponding HTTP error code.

**Screenshots or Response**
n/a

**pfSense Version & Package Version:**
 - pfSense Version: 2.6.0 RELEASE
 - Package Version: 1.5.3

**Affected Endpoints:**
 - URL: /api/v1/services/dhcpd/static_mapping

**Additional context**
n/a

**Comment by jaredhendrickson13** [comment]
Hey!

I can't seem to reproduce this. Can you provide any more info from your request? 

Here's an example of the requests I'm using that show it's working:

1) A GET request to show the static mapping I'm updating along with it's ID:
```
curl -s -k -u 'admin:pfsense' -X GET https://127.0.01/api/v1/services/dhcpd/static_mapping?interface=lan
```
```json
{
  "status": "ok",
  "code": 200,
  "return": 0,
  "message": "Success",
  "data": [
    {
      "id": 0,
      "mac": "00:00:01:00:00:00",
      "cid": "",
      "ipaddr": "",
      "hostname": "",
      "descr": "",
      "filename": "",
      "rootpath": "",
      "defaultleasetime": "",
      "maxleasetime": "",
      "gateway": "",
      "domain": "",
      "domainsearchlist": "",
      "ddnsdomain": "",
      "ddnsdomainprimary": "",
      "ddnsdomainsecondary": "",
      "ddnsdomainkeyname": "",
      "ddnsdomainkeyalgorithm": "hmac-md5",
      "ddnsdomainkey": "",
      "tftp": "",
      "ldap": "",
      "nextserver": "",
      "filename32": "",
      "filename64": "",
      "filename32arm": "",
      "filename64arm": "",
      "uefihttpboot": "",
      "numberoptions": ""
    }
  ]
}
```

2) A PUT request to assign values including an alternate gateway to the static mapping:
```
curl -s -k -u 'admin:pfsense' -X PUT https://127.0.0.1/api/v1/services/dhcpd/static_mapping -d '{
    "id": 0,
    "interface": "lan",
    "mac": "00:00:01:00:00:00",
    "ipaddr": "10.123.0.5",
    "hostname": "",
    "descr": "Example mapping",
    "gateway": "10.123.0.2"
  }'
```
```json
{
  "status": "ok",
  "code": 200,
  "return": 0,
  "message": "Success",
  "data": {
    "mac": "00:00:01:00:00:00",
    "cid": "",
    "ipaddr": "10.123.0.5",
    "hostname": "",
    "descr": "Example mapping",
    "filename": "",
    "rootpath": "",
    "defaultleasetime": "",
    "maxleasetime": "",
    "gateway": "10.123.0.2",
    "domain": "",
    "domainsearchlist": "",
    "ddnsdomain": "",
    "ddnsdomainprimary": "",
    "ddnsdomainsecondary": "",
    "ddnsdomainkeyname": "",
    "ddnsdomainkeyalgorithm": "hmac-md5",
    "ddnsdomainkey": "",
    "tftp": "",
    "ldap": "",
    "nextserver": "",
    "filename32": "",
    "filename64": "",
    "filename32arm": "",
    "filename64arm": "",
    "uefihttpboot": "",
    "numberoptions": ""
  }
}
```
