### ISSUE TITLE
GET /api/v1/system/ca and /api/v1/system/cert does not return a list of CAs/certs

### ISSUE THREAD

**Issue by jaredhendrickson13** [jaredhendrickson13/pfsense-api#357]
**Describe the bug**
Identified in #355. The `data` section of the response should return a list of CA and certificate objects, not the entire parent section.

**To Reproduce**
1. Ensure CAs are present in the config
2. Make a GET request to /api/v1/system/ca or /api/v1/system/cert
3. Notice how the `data` field is an associative array that includes the `ca` and/or `cert` parent key.

**Expected behavior**
The `data` section of the response should be a list of CA and/or certification objects without the `ca`/`cert` parent key present`

**pfSense Version & Package Version:**
 - pfSense Version: 2.6.0
 - Package Version 1.5.3

**Affected Endpoints:**
 - URL: /api/v1/system/ca
 - URL: /api/v1/system/cert

**Comment by xinspl** [comment]
oh if thats a bug... The same happens with URL: /api/v1/system/certificate ... I try to look into code to find solution

**Comment by jaredhendrickson13** [comment]
Yep that looks like the same issue, thanks for pointing that out. I'll get a patch for that one as well.
