### ISSUE TITLE
Cannot create OpenVPN client 

### ISSUE THREAD

**Issue by szgeri88** [jaredhendrickson13/pfsense-api#360]
Hello,

I would like to create an OpenVPN client instance/service via REST API but I have got the error message listed below after I sent the POST request to API server:

```
{
    "status": "bad request",
    "code": 400,
    "return": 2153,
    "message": "OpenVPN Client the field 'Server host or address' must contain a valid IP address or domain name.",
    "data": []
}
```

Creating a server instance is fine, it works without any problem, I experienced mentioned issue only for the client instance.

A read the API documentation/scheme and there is not any related field where I could set OpenVPN server's IP or hostname, however it has been already created.
Maybe the feature works, just the documentation does not include necessary field.

Additional informations:
 - pfSense version 2.6.0
 - package version: 1.5.3
 - POST URL: /api/v1/services/openvpn/client

Thank you.

**Comment by jaredhendrickson13** [comment]
Hey!

Thanks for reporting this. Looking at the code, `server_addr` is present and useable; but you're correct it is missing from the documentation. I'll have that field added to the documentation in the next patch.

Thanks again!
