### ISSUE TITLE
Unable to add new OpenVPN client when using "exit_notify" field

### ISSUE THREAD

**Issue by szgeri88** [jaredhendrickson13/pfsense-api#362]
Hello,

I would like to add a new OpenVPN client via URL `api/v1/services/openvpn/client`, each field (optional fields as well) were added to POST request but after sending request I have got the response below:

```
{
    "status": "bad request",
    "code": 400,
    "return": 2129,
    "message": "Unknown OpenVPN Server/Client Exit Notify",
    "data": []
}
```

The `exit_notify` field has been set (I tried it with all the available values - "none", "once", "twice"), the API response remains the same. However, when I remove `exit_notify` field, the POST request will be successful.

I don't know if it is a bug or did I just use the field in wrong way? 

Thank you.

**Comment by jaredhendrickson13** [comment]
Hey!

This looks like a documentation discrepancy. Those are the correct options for the _/api/v1/services/openvpn/server_ `exit_notify` field, but looking at the code the options for `exit_notify` on /api/v1/services/openvpn/client are actually: `x1`, `x2`, `x3`, `x4`, `x5`, `disable`. I'll get the documentation corrected for this field.

Thanks!

**Comment by szgeri88** [comment]
Thank you, it is correct now.
