### ISSUE TITLE
GET specific OpenVPN client/server instance based on vpnid

### ISSUE THREAD

**Issue by szgeri88** [jaredhendrickson13/pfsense-api#363]
Hello,

I tried to pull a specific OpenVPN client/server instance via GET URLs `api/v1/services/openvpn/client` and `/api/v1/services/openvpn/server`, however, the mentioned URLs supports only pulling all the OpenVPN clients and servers. 

It would be a good solution, if we could choose (optionally), which instance and related data want to pull, for example based on `vpnid` field.

Thank you.

**Comment by xinspl** [comment]
the endpoint /api/v1/services/openvpn/server works noramlly with query over GET.
`{"vpnid": "1"}`

**Comment by szgeri88** [comment]
> the endpoint /api/v1/services/openvpn/server works noramlly with query over GET. `{"vpnid": "1"}`

You're right, I have tested it and it works.  Thank you.
