### ISSUE TITLE
pfsense-api is not compatible with pfsense 2.7

### ISSUE THREAD

**Issue by maximegirardet** [jaredhendrickson13/pfsense-api#367]
Hi,

pfsense-api is not yet compatible with pfsense 2.7 (latest version) because of FreeBSD version upgrade :)
```
pkg: wrong architecture: FreeBSD:12:amd64 instead of FreeBSD:14:amd64
```

**Comment by jaredhendrickson13** [comment]
Hey!

[v1.6.0](https://github.com/jaredhendrickson13/pfsense-api/pull/359) will add support for pfSense CE 2.7.0 and pfSense Plus 23.01/23.05. Should be released in the next day or two. There are pre-release builds of v1.6.0 available on the releases page if you'd like to test.

Thanks!
