### ISSUE TITLE
GET /api/v1/system/version is not returning current version for pfSense 2.6.0 and pfSense API 1.4.3

### ISSUE THREAD

**Issue by fibiworks** [jaredhendrickson13/pfsense-api#373]
When OS is connected to the internet, the call to `/api/v1/system/version` is not returning the current value of the installed pfSense API plugin but returns null.

If the OS is not connected to the internet, it still works and returns the plugin version.

On Friday 2023-06-30 (4:52am GMT+0200) the same API call was working on both OS, with and without internet access.

On Monday, 2023-07-03 (4:50am GMT+0200) the API call is failing on OS with internet access.

It is used file `/etc/inc/api/models/APISystemAPIVersionRead.inc`, it calls via shell "pkg info pfSense-pkg-API"

This command works on OS without internet, but it fails on OS with internet

```sh
pkg info pfSense-pkg-API

# ld-elf.so.1: /lib/libc.so.7: version FBSD_1.7 required by /usr/local/sbin/pkg not found
```

It seems that `pkg-static` call is working

```sh
pkg-static info pfSense-pkg-API
```

Therefore, the temporary solution is to replace it directly in the shell call

```sh
sed -i in-place 's|pkg info pfSense-pkg-API|pkg-static info pfSense-pkg-API|' /etc/inc/api/models/APISystemAPIVersionRead.inc
```

**Comment by fibiworks** [comment]
The issue is not related to pfsense-api

But above solution can be helpful for users of pfsense-api plugin

**Comment by jaredhendrickson13** [comment]
Hey!

I can't think of a good reason not use `pkg-static` instead of `pkg` for this endpoint since it's just reading installed packages. I'll consider this a bug and have a fix in the next patch.

Thanks!

Thanks!
