### ISSUE TITLE
Problem adding network to Firewall Alias with 1.60

### ISSUE THREAD

**Issue by aeleus** [jaredhendrickson13/pfsense-api#374]
When adding a network to an existing Firewall Alias, an extra, automatically-generated description is added to the list of details. This causes a misalignment between the number of networks and the number of descriptions (details).
 
**To Reproduce**

Read current config:
curl -u admin:pfsense -H "Content-Type: application/json" -d '{"name":"My_Alias"}' -X GET https://pfsense.example.com/api/v1/firewall/alias

Returns:
{"status":"ok","code":200,"return":0,"message":"Success","data":{"63":{"name":"My_Alias","type":"network","address":"1.1.1.1\/32","descr":"","detail":"Existing network"}}}

Add a network:
curl -u admin:pfsense -H "Content-Type: application/json" -d '{"address":["2.2.2.2/32"],"apply":true,"detail":["New Network description"],"name":"My_Alias"}' -X POST https://pfsense.example.com/api/v1/firewall/alias/entry

Returns:
{"status":"ok","code":200,"return":0,"message":"Success","data":{"name":"My_Alias","type":"network","address":"1.1.1.1\/32 2.2.2.2\/32","descr":"","detail":"Existing network||New Network description||Entry added Tue, 04 Jul 2023 10:48:47 -0400"}}

Two networks, three descriptions.

**Expected behavior**
Expected return:
{"status":"ok","code":200,"return":0,"message":"Success","data":{"name":"My_Alias","type":"network","address":"1.1.1.1\/32 2.2.2.2\/32","descr":"","detail":"Existing network||New Network description"}}

Two networks, two descriptions.

**pfSense Version & Package Version:**
 - pfSense Version: 2.7.0
 - Package Version: 1.6.0

**Affected Endpoint:**
 - URL: /api/v1/firewall/alias/entry

**Comment by jaredhendrickson13** [comment]
Hey!

Thanks for reporting this. I can reproduce and see where the issue is. I'll have a fix included in the next patch.

Thanks again!
