### ISSUE TITLE
pfSense 2.7.0: php errors & crash report after install

### ISSUE THREAD

**Issue by maxlluky** [jaredhendrickson13/pfsense-api#380]
**Describe the bug**
Hello, I have the following crash reports with the new pfSense version 2.7.0 after installing the API. I have tested with two pfSense instances. Unfortunately both times the same error. The API can be used "normally" after the installation. However, after creating a new API token, a PHP error message also appears in the webui.

**To Reproduce**
1. Install the API via the Webui -> Command Prompt
2. Reload the Webui
3. See the Crash Report

**Expected behavior**
A normal install of the API without any crash report or php error-messages

**pfSense Version & Package Version:**
 - pfSense Version: [pfSense 2.7.0]
 - Package Version [latest (19.07.2023)]

**Additional context**
Crash report begins.  Anonymous machine information:

amd64
14.0-CURRENT
FreeBSD 14.0-CURRENT #1 RELENG_2_7_0-n255866-686c8d3c1f0: Wed Jun 28 04:21:19 UTC 2023     root@freebsd:/var/jenkins/workspace/pfSense-CE-snapshots-2_7_0-main/obj/amd64/LwYAddCr/var/jenkins/workspace/pfSense-CE-snapshots-2_7_0-main/sources/FreeBSD-src-REL

Crash report details:

PHP Errors:
[19-Jul-2023 11:08:53 Europe/Berlin] PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /etc/inc/api/framework/APITools.inc:1136
Stack trace:
#0 /etc/inc/api/framework/APITools.inc(1174): APITools\api_request('https://10.252....', 'PUT', '{"enable":"","p...', 'anka-gw-02-sync', '###############')
#1 /usr/local/share/pfSense-pkg-API/manage.php(82): APITools\sync()
#2 /usr/local/share/pfSense-pkg-API/manage.php(161): sync()
#3 {main}
  thrown in /etc/inc/api/framework/APITools.inc on line 1136

**Comment by jaredhendrickson13** [comment]
Hey!

Thanks for reporting this. This looks like a regression in the API sync feature due to the changes in PHP 8 introduced in pfSense 2.7. I'll work on a patch and see what I can do to improve tests for the sync feature in the future.

Thanks!
