### ISSUE TITLE
API version compare returns always "update_available" false

### ISSUE THREAD

**Issue by av-commits** [jaredhendrickson13/pfsense-api#390]
**Describe the bug**
intval in function below with version string starting with v e.g. v1.6.1 always return 0 --> 0 < 0 --> false
https://github.com/jaredhendrickson13/pfsense-api/blob/1b19911336b42d773847e828c155ab6d3202201e/pfSense-pkg-API/files/etc/inc/api/models/APISystemAPIVersionRead.inc#L68

I would recommend to use php [version_compare()](https://www.php.net/manual/en/function.version-compare.php) 
`return version_compare(self::get_api_version(), self::get_latest_api_version()) == -1;`

that work in my tests and also handles thing like 1.12.1 lower version then 2.0.1

**To Reproduce**
1. Call /api/v1/system/api/version on old api version system

**Expected behavior**
Return true if new API version is available

**Screenshots or Response**
n/a

**pfSense Version & Package Version:**
 - pfSense Version: pfSense 2.7.0
 - Package Version v1.6.1 / v1.6.2

**Affected Endpoints:**
 - URL: /api/v1/system/api/version

**Additional context**

**Comment by jaredhendrickson13** [comment]
Sounds like a great option. I'll include this in the next patch.

Thanks!
