### ISSUE TITLE
Alias description is blank if its the first alias on the list

### ISSUE THREAD

**Issue by SamB-GB** [jaredhendrickson13/pfsense-api#395]
**Describe the bug**
When adding an alias via the api/v1/firewall/alias/entry if its the first alias on the list the description doesn't get added.

**To Reproduce**
Submit CURL request:

```
curl -X 'POST'   'https://firewall_url/api/v1/firewall/alias/entry'   -H 'accept: application/json'   -H 'Authorization: Basic authcode'   -H 'Content-Type: application/json'   -d '{
  "address": ["192.168.1.10"],
  "apply": true,
  "detail": ["This is a description"],
  "name": "ALIAS_NAME"
}'
``` 

```
{"status":"ok","code":200,"return":0,"message":"Success","data":{"name":"ALIAS_NAME","type":"host","address":"192.168.1.10","descr":"Test Alias ","detail":"||This is a description"}}
```

**Expected behavior**
Description should be added.

**Screenshots or Response**
If applicable, add screenshots or response data to help explain your problem.

**pfSense Version & Package Version:**
 - pfSense Version: 23.05.1
 - Package Version v1.6.2

**Affected Endpoints:**
 - URL: /api/v1/firewall/alias/entry

**Additional context**

**Comment by jaredhendrickson13** [comment]
Thanks for reporting this. I'll have a fix included in the next patch!
