### ISSUE TITLE
Put method on /api/v1/user got HTTP 405 error

### ISSUE THREAD

**Issue by wangnanlena** [jaredhendrickson13/pfsense-api#397]
**Describe the bug**
I test put method to modify user password, however, it doesn't work.
I got the following error:
<html>

<head>
	<title>405 Not Allowed</title>
</head>

<body>
	<center>
		<h1>405 Not Allowed</h1>
	</center>
	<hr>
	<center>nginx</center>
</body>

</html>

GET & POST method works fine.

**To Reproduce**
use Postman to test.
basic auth.
json content

**Expected behavior**

**Screenshots or Response**
If applicable, add screenshots or response data to help explain your problem.
![image](https://github.com/jaredhendrickson13/pfsense-api/assets/2317422/404904f3-2909-43a2-a12d-e790f091d84f)

**pfSense Version & Package Version:**
 - pfSense Version: [pfSense 2.7.0]
 - Package Version [v1.6.2]

**Affected Endpoints:**
 - URL: [e.g. /api/v1/user/rule]

**Comment by jaredhendrickson13** [comment]
Hey!

This response indicates an incomplete API installation. The webConfigurator must be restarted after the package is installed to allow PUT and DELETE requests. You can run `/etc/rc.restart_webgui` to complete the installation. If it still does not work, remove the package and reinstall it using the full command displayed in the readme. 

Thanks!
