### ISSUE TITLE
PUT system/config not working. Unable to write config

### ISSUE THREAD

**Issue by dsl81** [jaredhendrickson13/pfsense-api#405]
**Describe the bug**
Recieving 504 Gateway Time-out when trying to put config.

**To Reproduce**
1. run curl -X 'PUT' -d '{}'
2. get no response
**Expected behavior**
Replace configuration

**Screenshots or Response**
```
 % curl --insecure -X 'PUT' \
  'https://10.1.20.200/api/v1/system/config' \
  -H 'accept: application/json' \
  -H 'Authorization: client-id token'
  -d '{}'


<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**pfSense Version & Package Version:**
 - pfSense Version: pfSense 2.7.0
 - Package Version v1.6.4

**Affected Endpoints:**
 - URL:  /api/v1/system/config

**Additional context**
Also tryed to upload same config as got from curl -X 'GET' 'https://10.1.20.200/api/v1/system/config'

**Comment by dsl81** [comment]
Any info on this? 
Maybe -d '{}' is wrong?

**Comment by jaredhendrickson13** [comment]
Hey!

Sorry for missing this initially! Using `-d {}` would effectively erase the entire pfSense config, which would likely cause an error. However, it looks like the new configuration access functions introduced in pfSense 2.7 do not allow you to replace the entire configuration like in older versions of pfSense, which is the actual problem here. It seems to cause an infinite loop. I'll need to take a look and see if there is a reliable way around that, if not this endpoint may need to be repurposed or deprecated.

Thanks!

**Comment by dsl81** [comment]
Thanks for the reply! 
Don't know if it helps but in [fauxapi](https://github.com/ndejong/pfsense_fauxapi), there is same function and it works even on pfsense 2.7.0. My knowledge of php and pfsense functions is not enough to tell if it could be reused here. Fauxapi is not maintained for 3 years now and was not promised to work since 2.5.x. I think that maintaing api for every 3rd party app like free radius or frr is quite difficult, so replacing entire config is rather usefull.

**Comment by jaredhendrickson13** [comment]
Thanks! I'll have to do some more digging, but I would assume fauxapi is not using the new configuration access methods that were added in 2.7, and is still using the old direct configuration access. Reverting to the direct configuration access may be a suitable solution for this endpoint though. I'll do some testing and keep you posted.

**Comment by jaredhendrickson13** [comment]
Seems like reverting back to the direct config access for this endpoint fixes the issue. I'll include the fix in the next patch.
