### ISSUE TITLE
Crash in v2.0.0

### ISSUE THREAD

**Issue by sjafferali** [jaredhendrickson13/pfsense-api#442]
**Describe the bug**
After installing v2.0.0 of my pfsense instance, I started getting reports of a crash in the UI. 

**pfSense Version & Package Version:**
 - pfSense Version: 23.09.1-RELEASE (amd64)
 - Package Version [pfSense REST API v2.0.0-dev-4daf959](https://github.com/jaredhendrickson13/pfsense-api/releases/tag/v2.0.0-dev-4daf959)

**Additional context**
Below is the contents of the crash report. 

```
Crash report begins.  Anonymous machine information:

amd64
14.0-CURRENT
FreeBSD 14.0-CURRENT amd64 1400094 #1 plus-RELENG_23_09_1-n256200-3de1e293f3a: Wed Dec  6 21:00:32 UTC 2023     root@freebsd:/var/jenkins/workspace/pfSense-Plus-snapshots-23_09_1-main/obj/amd64/Obhu6gXB/var/jenkins/workspace/pfSense-Plus-snapshots-23_09_1

Crash report details:

PHP Errors:
[08-Feb-2024 08:15:00 America/Los_Angeles] PHP Fatal error:  Cannot declare class Firebase\JWT\JWT, because the name is already in use in /etc/inc/firebase/php-jwt/src/JWT.php on line 28



No FreeBSD crash data found.
			
```

Not sure if its related, but I do have both the v1.7.1 package and v2.0.0 package installed on this system.

**Comment by sjafferali** [comment]
I think this is likely related to having both versions v1.7.1 and v2.0.0 installed at the same time. Accessing the v1.7.1 documentation via the UI shows a white screen with the above error after the v2.0.0 install.

**Comment by jaredhendrickson13** [comment]
You're correct, this is a bug when running both the v1 and v2 packages concurrently. I don't have a current workaround that doesn't involve a custom build at moment, unfortunately. The end goal is to allow both packages to be installed concurrently but doing so introduces some conflicts which I've been working through, this being the biggest of them. Both packages install the `php-jwt` dependency during the build process which results in two versions of the dependency being present in the PHP include path. I should hopefully have a fix for this in the next dev build.

**Comment by jaredhendrickson13** [comment]
Fixed in https://github.com/jaredhendrickson13/pfsense-api/releases/tag/v2.0.0-dev-094eefe
