### ISSUE TITLE
POST | IPsec Phase2 | "hash-algorithm-option" is required even for GCM Algorithms

### ISSUE THREAD

**Issue by DolevBaron** [jaredhendrickson13/pfsense-api#448]
**Describe the bug**
The "hash-algorithm-option" parameter is required as part of the body in POST requests to the 'services/ipsec/phase2/' endpoint regardless of the provided "encryption-algorithm-option", even though the GUI states the following: "Hash is ignored with GCM algorithms.".

**To Reproduce**
Send a request to the aforementioned endpoint while omitting the "hash-algorithm-option' parameter and including the following:
`  
"encryption-algorithm-option": [
	{
	  "name": "aes128gcm",
	  "keylen": "auto"
	}
  ],
`

**Expected behavior**
The POST request should be processed and a Phase2 should be created with no Hash Algorithm selected.

**pfSense Version & Package Version:**
 - pfSense Version: v2.7.2-RELEASE (amd64)
 - Package Version: pfSense-2.7-pkg-API

**Affected Endpoints:**
 - URL: /api/v1/services/ipsec/phase2

**Comment by jaredhendrickson13** [comment]
Thanks for reporting this issue! I'll have a fix for this in the next patch.
