### ISSUE TITLE
OpenVPN Client Enable/Disable

### ISSUE THREAD

**Issue by danielearrighi** [jaredhendrickson13/pfsense-api#451]
I'm trying to setup an API call to disconnect and reconnect the VPN client on demand. 

**To Reproduce**
When I call the `/api/v1/services/openvpn/client` with 
```json
{
  disable: true
}
```
it works, but the **auth_user** property gets set to `null` (no problem if I pass the user in the request's body).
If I then call the same API with
```json
{
  disable: false
}
```
It doesn't work and the VPN Client stays disabled.

**Expected behavior**
Disable and Enable the VPN client correctly.

**pfSense Version & Package Version:**
 - pfSense Version: 2.7.2
 - Package Version 1.7.2

**Affected Endpoints:**
 - URL: [api/v1/services/openvpn/client]

**Comment by jaredhendrickson13** [comment]
Thanks for reporting this!

I can confirm this is a bug. There is conflicting logic for the `disabled` field that prevents it from being set to `false` once it's been set to `true`. I'll have a fix for this in the next patch.

Thanks!
