### ISSUE TITLE
Is or will be 24.03 compatible?

### ISSUE THREAD

**Issue by urbaman** [jaredhendrickson13/pfsense-api#452]
**Is your feature request related to a problem? Please describe.**
Installation error on 24.03

**Describe the solution you'd like**
Working on 24.03

**Describe alternatives you've considered**
No other alternative

**Comment by jaredhendrickson13** [comment]
Can you provide the error you're encountering?

**Comment by urbaman** [comment]
```
Fetching pfSense-23.09-pkg-API.pkg: .......... done
Installing pfSense-pkg-API-1.7_2...

Failed to install the following 1 package(s): https://github.com/jaredhendrickson13/pfsense-api/releases/latest/download/pfSense-23.09-pkg-API.pkg
```

**Comment by kdbutler69** [comment]
This is what I'm getting: "pkg: wrong architecture: FreeBSD:14:* instead of FreeBSD:15:amd64"

**Comment by jaredhendrickson13** [comment]
Thanks @urbaman and @kdbutler69. 

Looks like they've moved to FreeBSD 15 for Plus. I'll try to spin up a FreeBSD 15 builder this weekend and push a 24.03 compatible build of v1.7.2.

**Comment by jaredhendrickson13** [comment]
Can I get someone to test installing this build on 24.03 and verify it installs correctly?

https://github.com/jaredhendrickson13/pfsense-api/releases/tag/v1.7.3_deve64c61dc38ba5ea57ed2a0a5295d78c43d2e2e2f

**Comment by urbaman** [comment]
@jaredhendrickson13 I can confirm it installs and works!
