### ISSUE TITLE
Create firewall rule using aliases

### ISSUE THREAD

**Issue by h-medjahed** [jaredhendrickson13/pfsense-api#46]
When we try to create a firewall rule using aliase name for dstport attribute we get this error  {"status": "bad request,"code": 400,"return": 4049", "message": "**Invalid firewall rule destination port**", "data":[]}

The body 
{
  'type': 'pass',
  'interface': 'WAN',
  'ipprotocol': 'inet',
  'protocol': 'tcp',
  'srcport': 'any',
  'src': 'any',
  'dst': '20_0019_ip_itgg0ebarwmsingk',
  'dstport': 'Ports_20_0019_itgg0ebarwmsingk',
  'descr': 'fw with alias',
  'apply': True
}

**Comment by h-medjahed** [comment]
To overcome this issue I have modified /api/models/APIFirewallRuleCreate.inc ligne 164
replace  is_port_or_range with is_port_or_range_or_alias

**Comment by jaredhendrickson13** [comment]
Hey!

Thanks for your help reporting issues. This was a good catch, feel free to open a pull request with this change if you'd like. Otherwise I can have a fix for this in the next patch. 

Thanks!
