### ISSUE TITLE
Add pfSense-dark theming for v2

### ISSUE THREAD

**Issue by KristijanL** [jaredhendrickson13/pfsense-api#463]
i use pfSense-dark Theme, but the system_restapi_* dont dont have it, would it be possible to add it?

<img width="1203" alt="Screenshot 2024-05-10 at 12 59 15" src="https://github.com/jaredhendrickson13/pfsense-api/assets/977481/0d459747-d7fc-469f-ba68-c64f98e80cc9">

<img width="1193" alt="Screenshot 2024-05-10 at 12 59 29" src="https://github.com/jaredhendrickson13/pfsense-api/assets/977481/965d9e5d-9fda-451d-ba97-b0b66fb317ea">

**Comment by jaredhendrickson13** [comment]
pfSense usually handles which CSS to use on its own, or at least it does in v1; but it seems there's an issue preventing the page from seeing the correct web GUI settings from within a PHP class method. I have a workaround I can push to fix this.
