### ISSUE TITLE
Valid CIDR errors as invalid for Allowed Networks

### ISSUE THREAD

**Issue by raidekoptix** [jaredhendrickson13/pfsense-api#464]
**Describe the bug**
As it says on the tin, entering a valid cider of "10.1.1.0/24" gets flagged as invalid and does not save.

**To Reproduce**
1. Go to System -> API
2. Click on Display Advanced 
3. Scroll down to Allowed Networks
4. Enter "10.1.1.0/24"
5. Click Save
6. See error

**Expected behavior**
I expect it to allow 10.1.1.0/24 as a valid CIDR

**Screenshots or Response**
If applicable, add screenshots or response data to help explain your problem.

**pfSense Version & Package Version:**
 - pfSense Version: 2.7.2-RELEASE 
 - Package Version [e.g. v1.7.3]

**Affected Endpoints:**
 - N/A

**Additional context**
It's worth noting that other /24s such as 192.168.1.0/24 work just fine.

**Comment by jaredhendrickson13** [comment]
Hmm I'm currently able to save that CIDR on v1.7.3 without issue. Can you provide the error message you receive when you try to save?

Thanks!

**Comment by raidekoptix** [comment]
Strangely, I tried again this afternoon to reproduce the error, and it magically worked. I have no idea what was wrong, all other settings remain untouched. I guess we can close this one, sorry.

**Comment by raidekoptix** [comment]
I dug the error out of my history, and it appears upon looking at it again some whitespace snuck into the field:

"Access list entry '10.1.1.0/24 ' is not a valid IPv4 or IPv6 CIDR."

**Comment by jaredhendrickson13** [comment]
Ah that'd be expected behavior at the moment then. Excess whitespace would cause the validation to fail since the networks are separated by single spaces. This could probably use some extra validation to automatically remove excess whitespace and make the field more fault tolerant. I'll keep this open as a potential enhancement.

Thanks!
