### ISSUE TITLE
RESTAPI (v2) - DHCP Server NTP Server Limit Incorrect

### ISSUE THREAD

**Issue by crawc** [jaredhendrickson13/pfsense-api#475]
**Describe the bug**
pfSense supports setting 4 NTP servers for each DHCP server but the RESTAPI limit is off by 1 only allowing 3 to be set.

`PUT /api/v2/services/dhcp_server` has been confirmed but I'm not sure about `PUT /api/v2/services/dhcp_servers`

**To Reproduce**
PUT /api/v2/services/dhcp_server

`{
    "id": "opt1",
    "interface": "vtnet1.101",
    "enable": true,
    "range_from": "172.16.1.20",
    "range_to": "172.16.1.250",
    "domain": "cr101.test.com",
    "failover_peerip": "172.16.1.3",
    "defaultleasetime": 2592000,
    "maxleasetime": 3888000,
    "gateway": "172.16.1.1",
    "dnsserver": [
        "172.16.1.1",
        "8.8.8.8",
        "9.9.9.9",
        "1.1.1.1"
    ],
    "winsserver": null,
    "ntpserver": [
        "172.16.1.1",
        "time-a-g.nist.gov",
        "pool.ntp.org",
        "time.google.com"
    ],
    "staticarp": false,
    "ignorebootp": false,
    "ignoreclientuids": false,
    "nonak": false,
    "disablepingcheck": false,
    "dhcpleaseinlocaltime": true,
    "statsgraph": false,
    "numberoptions": [
        {
            "parent_id": "lan",
            "id": 0,
            "number": 66,
            "type": "string",
            "value": "\"http://boot.test.com/CFG/\""
        }
    ]
}`

**Result**
`{
    "code": 400,
    "status": "bad request",
    "response_id": "LENGTH_VALIDATOR_MAXIMUM_CONSTRAINT",
    "message": "Field `ntpserver` exceeds the maximum array length of 3.",
    "data": []
}`

**Expected behavior**
Set the 4 NTP servers

**pfSense Version & Package Version:**
 - pfSense Version: pfSense 2.7.2
 - Package Version: v2.0.0-dev-990b919

**Affected Endpoints:**
 - URL: PUT /api/v2/services/dhcp_server

**Comment by crawc** [comment]
After changing line 175 of `RESTAPI/Models/DHCPServer.inc` to `many_maximum: 4` I was able to set all 4.

https://github.com/jaredhendrickson13/pfsense-api/blob/e7d99a46f182a9a06df0b6e6b39c010817f6927c/pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Models/DHCPServer.inc#L175

**Comment by jaredhendrickson13** [comment]
Good catch! Seems like I fat fingered that one 😅 I'll push a fix for this tonight.

Thanks!
