### ISSUE TITLE
Tried to update to beta 2.0.0, UI did not show updated version, attempt to uninstall leaves GUI even after reboot

### ISSUE THREAD

**Issue by MysticalMount** [jaredhendrickson13/pfsense-api#480]
**Describe the bug**
Tried to update to beta 2.0.0, UI did not show updated version, attempt to uninstall leaves GUI even after reboot

**To Reproduce**
1. Install v1.7.4 stable
2. Use pkg-static command to install beta
3. Check gui, looks like still v1.7.4
4. Uninstall via cli tool (after reloading shell as command is not on path until relaunching shell)

Successfull uninstall:
```
[2.7.2-RELEASE][admin@pf.int.keepclm.com]/root: pfsense-restapi delete
pfSense-pkg-RESTAPI-2.0_0-beta-e8cd8dd: missing file /usr/local/www/api/v2/documentation/index.php
pfSense-pkg-RESTAPI-2.0_0-beta-e8cd8dd: missing file /usr/local/www/api/v2/schema/index.php
pkg-static: unlinkat(usr/local/www/api/v2/schema/): No such file or directory
pkg-static: unlinkat(usr/local/www/api/v2/): No such file or directory
pkg-static: unlinkat(usr/local/www/api/v2/documentation/): No such file or directory
pkg-static: unlinkat(usr/local/www/api/v2/): No such file or directory
Updating database digests format: . done
Checking integrity... done (0 conflicting)
Deinstallation has been requested for the following 1 packages (of 0 packages in the universe):

Installed packages to be REMOVED:
	pfSense-pkg-RESTAPI: 2.0_0-beta-e8cd8dd

Number of packages to be removed: 1

The operation will free 6 MiB.
[1/1] Deinstalling pfSense-pkg-RESTAPI-2.0_0-beta-e8cd8dd...
Removing RESTAPI components...
Menu items... done.
Loading package instructions...
Configuration... done.
[1/1] Deleting files for pfSense-pkg-RESTAPI-2.0_0-beta-e8cd8dd: .........
[1/1] Deleting files for pfSense-pkg-RESTAPI-2.0_0-beta-e8cd8dd...
[1/1] Deleting files for pfSense-pkg-RESTAPI-2.0_0-beta-e8cd8dd... done
Restarting webConfigurator... done.
```

7. Check GUI, v1.7.4 showing as installed (even after 2.0.0 upgrade)
8. Reboot system
9. GUI still showing as installed at v1.7.4
10. Check package list via pkg info and package has been uninstalled

**Expected behavior**
Expected both the beta version to reflect in GUI, and also the uinstall to reflect in the GUI, especially after reboot, but perhaps that shouldnt even be required

**Screenshots or Response**
If applicable, add screenshots or response data to help explain your problem.

**pfSense Version & Package Version:**
 - pfSense Version: [e.g. pfSense 2.7.2]
 - Package Version [e.g. v1.7.4 + v2.0.0beta]

**Affected Endpoints:**
N/A

**Additional context**

**Comment by jaredhendrickson13** [comment]
This is expected behavior. See #474.
