### ISSUE TITLE
Services HAPROXY frontend action "Internal Server Error"

### ISSUE THREAD

**Issue by alex2ospit** [jaredhendrickson13/pfsense-api#481]
**Describe the bug**
When using POST  /api/v2/services/haproxy/frontend/action

 "code": 500,
    "status": "internal server error",
    "response_id": "ENDPOINT_RECEIVED_UNEXPECTED_ERROR",
    "message": "Attempt to assign property `internal_name` on null\n#0 /usr/local/pkg/RESTAPI/Models/HAProxyFrontendAction.inc(228): RESTAPI\\Models\\HAProxyFrontendAction->set_field_internal_names()\n#1 /usr/local/pkg/RESTAPI/Core/Model.inc(1777): RESTAPI\\Models\\HAProxyFrontendAction->to_internal()\n#2 /usr/local/pkg/RESTAPI/Core/Model.inc(1803): RESTAPI\\Core\\Model->_create()\n#3 /usr/local/pkg/RESTAPI/Core/Endpoint.inc(730): RESTAPI\\Core\\Model->create(false)\n#4 /usr/local/pkg/RESTAPI/Core/Endpoint.inc(657): RESTAPI\\Core\\Endpoint->post()\n#5 /usr/local/www/api/v2/services/haproxy/frontend/action/index.php(3): RESTAPI\\Core\\Endpoint->process_request()\n#6 {main}",
    "data": []

**To Reproduce**
using POSTMAN post to /api/v2/services/haproxy/frontend/action

Body: 

{
  "parent_id": 0,
  "action": "use_backend",
  "acl": "testing",
  "backend": "testing"
}

**pfSense Version & Package Version:**
 - pfSense Version: pfSense 2.7.2
 - Package Version v2.0.0-beta-e8cd8dd

**Affected Endpoints:**
 - URL: /api/v2/services/haproxy/frontend/action

**Comment by jaredhendrickson13** [comment]
Thanks for reporting this. I'll take a look today and work on a fix.

**Comment by alex2ospit** [comment]
Thanks for the fast respond on this. How can we pull the latest changes to pfsense to test it out?

**Comment by alex2ospit** [comment]
> Thanks for the fast respond on this. How can we pull the latest changes to pfsense to test it out?
got it done. just copy the edited file in the RESTAPI folder at /usr/local/pkg/RESTAPI/Models

tested. it works as expectation.

**Comment by jaredhendrickson13** [comment]
Thanks for confirming. I've just released [v2.0.0-beta-9824774](https://github.com/jaredhendrickson13/pfsense-api/releases/tag/v2.0.0-beta-9824774) which contains the fixes for this along with some other fixes.
