### ISSUE TITLE
not compatible with pfSense 24.03

### ISSUE THREAD

**Issue by sueess86** [jaredhendrickson13/pfsense-api#482]
the API cannot be installed on a pfSense 7100 with version 24.03.
Apparently the package is not compatible with FreeBSD 15 and requires version 14.

`pkg -C /dev/null add https://github.com/jaredhendrickson13/pfsense-api/releases/latest/download/pfSense-2.7-pkg-API.pkg && /etc/rc.restart_webgui
Fetching pfSense-2.7-pkg-API.pkg: 100%    2 MiB   1.7MB/s    00:01
Installing pfSense-pkg-API-1.7_4...
pkg: wrong architecture: FreeBSD:14:* instead of FreeBSD:15:amd64

Failed to install the following 1 package(s): https://github.com/jaredhendrickson13/pfsense-api/releases/latest/download/pfSense-2.7-pkg-API.pkg`

freebsd-version
15.0-CURRENT

**Comment by jaredhendrickson13** [comment]
Looks like you're trying to install the package built for pfSense CE 2.7. Just change the `2.7` in your install command with `24.03` to install the package built for 24.03.
