### ISSUE TITLE
Response code 500 when calling /api/v2/firewall/nat/one_to_one/mappings

### ISSUE THREAD

**Issue by hirosumee** [jaredhendrickson13/pfsense-api#491]
**Describe the bug**
When tried to call `/api/v2/firewall/nat/one_to_one/mappings` endpoint , i faced the below 500  response code
`{
  "code": 500,
  "status": "internal server error",
  "response_id": "ENDPOINT_RECEIVED_UNEXPECTED_ERROR",
  "message": "Named parameter $parent_id overwrites previous argument\n#0 /usr/local/pkg/RESTAPI/Core/Model.inc(1554): RESTAPI\\Models\\OneToOneNATMapping->__construct(parent_id: NULL)\n#1 /usr/local/pkg/RESTAPI/Core/Model.inc(1737): RESTAPI\\Core\\Model::read_all(NULL, 0, 0)\n#2 /usr/local/pkg/RESTAPI/Core/Endpoint.inc(742): RESTAPI\\Core\\Model::query(Array, Array, NULL, 0, 0)\n#3 /usr/local/pkg/RESTAPI/Core/Endpoint.inc(688): RESTAPI\\Core\\Endpoint->get()\n#4 /usr/local/www/api/v2/firewall/nat/one_to_one/mappings/index.php(3): RESTAPI\\Core\\Endpoint->process_request()\n#5 {main}",
  "data": []
}`

**To Reproduce**
1. Call API `/api/v2/firewall/nat/one_to_one/mappings`

**Expected behavior**
Return list of one_to_one mapping list

**Screenshots or Response**
<img width="1443" alt="image" src="https://github.com/jaredhendrickson13/pfsense-api/assets/32713077/2276a919-7bc7-4808-993e-2f5c591a8a8b">

**pfSense Version & Package Version:**
 - pfSense Version: 2.7.2-RELEASE (amd64) built on Thu Dec 7 3:10:00 +07 2023 FreeBSD 14.0-CURRENT
 - Package Version: v2.0.0-rc-30b2715

**Affected Endpoints:**
 - URL: /api/v2/firewall/nat/one_to_one/mappings

**Additional context**

**Comment by jaredhendrickson13** [comment]
Thanks for reporting this, I'll push out a fix today.

**Comment by jaredhendrickson13** [comment]
The latest release candidate build contains a fix for this as well as new tests to ensure it doesn't pop up again:

https://github.com/jaredhendrickson13/pfsense-api/releases/tag/v2.0.0-rc-217e88f
