### ISSUE TITLE
Support read all existing port_forward

### ISSUE THREAD

**Issue by hirosumee** [jaredhendrickson13/pfsense-api#492]
**Is your feature request related to existing pfSense functionality that is missing from the API? 
Please support read all existing port_forward, as convention , i think it should be `/api/v2/firewall/nat/port_forwards`

**Is your feature request related to a problem? Please describe.**
I can't find anyway to get all port_forward instead of try with each increment id until meet not found

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jaredhendrickson13** [comment]
It actually looks like this endpoint was unintentionally removed in a previous release. I'll make sure this is re-added. Thanks for reporting!

**Comment by jaredhendrickson13** [comment]
Not currently. The functionality to read all port forwards is already present within the package but the actual endpoint to call it is missing. I'll have an updated release candidate build available today to address this.

**Comment by jaredhendrickson13** [comment]
This endpoint is available again in the latest release candidate: https://github.com/jaredhendrickson13/pfsense-api/releases/tag/v2.0.0-rc-217e88f
