### ISSUE TITLE
Call api-v2 through pfsense-lan

### ISSUE THREAD

**Issue by ouyoung33** [jaredhendrickson13/pfsense-api#507]
Hello, after installing API-V2, I can access the api through the public network, but for security, we generally use the lan port of pfsense to access and call the api, which can be implemented in API-V1 before, but not in API-V2. I can ping my pfsense-lan port ip address from an external machine (whose network card is on the same subnet as my pfsense-lan), but I can't when I call the api. Is there any special configuration in the configuration of API-V2?

**Comment by jaredhendrickson13** [comment]
Yes there are three ways you can limit access to the API with v2. It's recommended all three are configured for optimal security:

1. Use regular firewall rules to only allow access to port 443 (or whatever port you have the web GUI running on) on your LAN interface(s) under Firewall > Rules. It is strongly recommended you do not have rules allowing public access to pfSense on WAN interfaces.
2. Use the 'Allowed Interfaces' option under 'System > REST API > Settings' to select only the interfaces you want to have access to the API. If no interfaces are selected here, all interfaces will have access to the API. Any API requests received on interfaces that are not selected here will be denied API access. 
3. Define API access rules under 'System > REST API > Access List' that only allow access to your LAN subnets. Optionally, you can restrict which pfSense users have access to the API here as well.
