### ISSUE TITLE
Whether api-v1 will go offline in the future is no longer supported

### ISSUE THREAD

**Issue by ouyoung33** [jaredhendrickson13/pfsense-api#508]
Hello, at present, the official version of api-v2 has been released, we found that v2 is quite different from v1, for our development team, the amount of code we need to modify will be larger. I want to know Whether api-v1 will go offline in the future is no longer supported?

**Comment by jaredhendrickson13** [comment]
Good question. This was briefly mentioned in the [v2 release announcement](https://github.com/jaredhendrickson13/pfsense-api/discussions/500), but I can explain more here.

I will keep supporting v1. It will continue to get bug fixes, compatibility updates, and security patches. However, v1 probably won't get new features. You can use v1 and v2 together and slowly move to v2.

I will support v1 for a reasonable amount of time unless one of these happen:

1. The number of v1 downloads stays very low for a long time. This would likely mean people are not using it much anymore.
2. A future pfSense update makes v1 incompatible and fixing it would require big changes.

I will also open polls in the future to see how many people are still using v1 before deciding to stop supporting it.

Hope this helps.
