### ISSUE TITLE
/api/v2/status/logs does not query all log events

### ISSUE THREAD

**Issue by aeleus** [jaredhendrickson13/pfsense-api#509]
**Describe the bug**
I just upgraded to REST API v2.01 from 1.75. I can no longer query all system and firewall events.

**To Reproduce**
When querying https://pfsense.domain.tld/api/v2/status/logs/system (or firewall), the oldest event is always the first event in the current log file. Example:
Jul 13 15:08:00 pfSense newsyslog[83161]: logfile turned over due to size>500K

No events from the rotated log files are returned. If the query is run just after the log files are rotated, only a single result is returned.
Changing values for limit=0&offset=0 still only returns results from the current log file.

**Expected behavior**
The ability to query all log events like the UI does (https://pfsense.domain.tld/status_logs.php and https://pfsense.domain.tld/status_logs_filter.php)

**pfSense Version & Package Version:**
- pfSense Version: 2.7.2-RELEASE
- Package Version: 2.0_1

**Affected Endpoints:**
- URL: /api/v2/status/logs/system
- URL: /api/v2/status/logs/firewall

**Comment by jaredhendrickson13** [comment]
This doesn't look like a bug, both v1 and v2 only look at the most recent log file and don't attempt to decompress or look at log files that have already been rotated:

https://github.com/jaredhendrickson13/pfsense-api/blob/5db64cd7be7d236a0b5cd840a1768058e1b42d84/pfSense-pkg-API/files/etc/inc/api/models/APIStatusLogSystemRead.inc#L27-L32

https://github.com/jaredhendrickson13/pfsense-api/blob/b21981dd1f3aaf12234e9294c19331b0945c226b/pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Models/SystemLog.inc#L28-L39

 In v1 this was intentionally done to prevent API calls from hanging when reading a large number of logs, but it's likely feasible to do this in v2 now that pagination is supported. I'll see if I can work it into v2.1.0.

Thanks!
