### ISSUE TITLE
Newer FreeBSD version for package pfSense-pkg-RESTAPI

### ISSUE THREAD

**Issue by sherif-fanous** [jaredhendrickson13/pfsense-api#524]
**Describe the bug**
Trying to install the latest release on a Netgate 6100 running 24.03 and I get the following error

```console
[24.03-RELEASE][admin@netgate-6100]/root: pkg-static -C /dev/null add https://github.com/jaredhendrickson13/pfsense-api/releases/latest/download/pfSense-24.03-pkg-RESTAPI.pkg
Fetching pfSense-24.03-pkg-RESTAPI.pkg: 100%  751 KiB 768.5kB/s    00:01
Installing pfSense-pkg-RESTAPI-2.0_3...
Newer FreeBSD version for package pfSense-pkg-RESTAPI:
To ignore this error set IGNORE_OSVERSION=yes
- package: 1500017
- running kernel: 1500012
Ignore the mismatch and continue? [y/N]: N

Failed to install the following 1 package(s): https://github.com/jaredhendrickson13/pfsense-api/releases/latest/download/pfSense-24.03-pkg-RESTAPI.pkg
```

**pfSense Version & Package Version:**

- pfSense Version:

```console
24.03-RELEASE (amd64)
built on Wed Apr 24 13:38:00 EDT 2024
FreeBSD 15.0-CURRENT
```

- Package Version: 24.03

Any idea if this should be safe to ignore and continue?

**Comment by jaredhendrickson13** [comment]
Yes, it's safe to continue since the package doesn't contain any binary or kernel specific dependencies and you are on FreeBSD 15. The package is just PHP and a couple shell scripts really. However, the confirmation prompt may prevent updates for the package from working correctly from the UI or API. But you can still update from the CLI to confirm the prompt.

I do find it odd that there would be slightly different builds for 24.03, this installs cleanly using the AMI of 24.03 on AWS. I'll see if I can adjust the Makefile to ignore the kernel mismatch by default, in the past the IGNORE_OSVERSION did not help.

**Comment by jaredhendrickson13** [comment]
I found an issue with my FreeBSD 15 build server that likely pushed a build with the incorrect flags. I just rebuilt v2.0.3 and updated the release. Let me know if you still see the issue occur.

Thanks!

**Comment by sherif-fanous** [comment]
That fixed it @jaredhendrickson13 

```console
[24.03-RELEASE][admin@netgate-6100]/root: pkg-static -C /dev/null add https://github.com/jaredhendrickson13/pfsense-api/releases/latest/download/pfSense-24.03-pkg-RESTAPI.pkg
Fetching pfSense-24.03-pkg-RESTAPI.pkg: 100%  752 KiB 770.4kB/s    00:01
Installing pfSense-pkg-RESTAPI-2.0_3...
Extracting pfSense-pkg-RESTAPI-2.0_3: 100%
Saving updated package information...
done.
Loading package configuration... done.
Configuring package components...
Loading package instructions...
Custom commands...
Menu items... done.
Writing configuration... done.
Building endpoints... done.
Building privileges... done.
Building forms... done.
Building privileges... done.
Generating OpenAPI documentation... done.
Restoring REST API configuration... no backup found.
Starting REST API settings sync... not configured.
Configuring schedule for \RESTAPI\Caches\AvailablePackageCache... done.
Configuring schedule for \RESTAPI\Caches\RESTAPIVersionReleasesCache... done.
Initiating webConfigurator restart... done.
```
