### ISSUE TITLE
Add FireWall Shaper support please

### ISSUE THREAD

**Issue by StormYudi** [jaredhendrickson13/pfsense-api#53]
Hi, thank you for your hard work to make this amazing api,

and I am wondering if you can add the support for Firewall-Shaper functions, I would appreciate it, thank you very much!

**Comment by jaredhendrickson13** [comment]
Hey! 

Thanks for the request. This is a great suggestion. I can take a look at the traffic shaper code and see how difficult it will be to implement into an API endpoint. If it's pretty straightforward I can probably squeeze it into the next minor release. I'll update this issue when I've had the chance to look further. 

Thanks again!

**Comment by StormYudi** [comment]
Thank you for your work! I am looking forward to it~
