### ISSUE TITLE
Wireguard add Description Peer

### ISSUE THREAD

**Issue by lapf10** [jaredhendrickson13/pfsense-api#534]
Hi,

First of all, congratulations on the superb work developed on this API, it will undoubtedly help a lot of people.

I'm just exploring the wireguard part and I think it would be interesting to have the possibility of adding the peer description and not requiring the Pre-shared Key as in the GUI

thanks,

**Comment by jaredhendrickson13** [comment]
Looks like the description field was planned for the original release but was never implemented. Probably skipped over on accident. I'll make sure that's implemented in v2.1.0.

As for the `presharedkey` field, it is currently not a required field. You can exclude the field from the request data altogether or you can set the field to `null` to unset its current value.

**Comment by lapf10** [comment]
Thanks for the reply
I'll be waiting for the next update.
Regarding the presharedkey, when you send null or exclude the request field, the API returns
`{"code":400,"status":"bad request","response_id":"FIELD_EMPTY_NOT_ALLOWED","message":"Field `presharedkey` cannot be empty.","data":[]}`

**Comment by jaredhendrickson13** [comment]
Ah you're right, I see the issue. This warrants a separate issue so I've opened #541. Feel free to follow that issue for updates.

Thanks!
