### ISSUE TITLE
Could not PATCH /api/v2/interface for GIF interface

### ISSUE THREAD

**Issue by chocomus** [jaredhendrickson13/pfsense-api#536]
I have GIF interface in pfsense, but could not PATCH /api/v2/interface to update that interface.

With pfsense-api v1, I could update the interface, but not with pfsense-api v2.

The following is the curl CMD results of GET /api/v2/interface and PATCH /api/v2/interface.

```
curl -X 'GET' \
  'https://pfsense.localdomain:32250/api/v2/interface?id=opt9' \
  -H 'accept: application/json' \
  -H 'x-api-key: foobar' | jq
----
{
  "code": 200,
  "status": "ok",
  "response_id": "SUCCESS",
  "message": "",
  "data": {
    "id": "opt9",
    "if": "gif0",
    "enable": true,
    "descr": "transix",
    ...
  }
}
----
```

```
curl -X 'PATCH' \
  'https://pfsense.localdomain:32250/api/v2/interface' \
  -H 'accept: application/json' \
  -H 'content-type: application/json' \
  -H 'x-api-key: foobar' \
  -d '{"id":"opt9","if":"gif0","enable":true}' | jq
----
{
  "code": 400,
  "status": "bad request",
  "response_id": "FIELD_INVALID_CHOICE",
  "message": "Field `if` must be one of [igb0, em0, ovpns3, ovpnc1, ovpnc2, tun_wg0, em0.10, em0.20, em0.30, em0.99]",
  "data": []
}
----
```

**Comment by jaredhendrickson13** [comment]
Thanks for reporting this. v2 uses a different built-in pfSense function to determine available interfaces than v1, but apparently the new function doesn't include _all_ auxiliary interfaces. I'll either supplement that function or just switch it back to old one in the next release.
