### ISSUE TITLE
Support for NTP Server Configurations

### ISSUE THREAD

**Issue by degas2226** [jaredhendrickson13/pfsense-api#54]
Hi, Want to appriciate your hard work for making this amazing api.

It is great if we can add one API for adding/updating time servers, thank you very much!

![image](https://user-images.githubusercontent.com/9531477/103256786-7de48000-49b4-11eb-8cb4-b7eb17b82bdd.png)

**Comment by jaredhendrickson13** [comment]
Hey!

Thanks for the request. This one is already in the works and will be included in the next minor release (v1.2.0). Hoping to have that released by the end of January. I'll keep this request open and update it as soon as I have a pull request containing this feature.

Thanks again!

**Comment by degas2226** [comment]
Thank you for your work! I am looking forward to it.
