### ISSUE TITLE
When importing a certificate in V1, the certificate type is always "server"

### ISSUE THREAD

**Issue by Coffee-Processing-Unit** [jaredhendrickson13/pfsense-api#540]
**Describe the bug**
When importing a certificate in V1, the certificate type is always "server".

**To Reproduce**

1. make a request to /system/certificate, in the body, set the field "method" to "import". Also set the "type" field to "user". 
2. The response is ("message": "Success"). the returned object "type" field is set to "server".
3. In the GUI management interface, the certificate type is "server".

**Expected behavior**
The certificate type will match the requested type

**Root Cause**
I found the cause of this behavior, but I wanted to hear your explanation for it.
This code is from the APISystemCertificateCreate.inc file. Why are you overriding the certificate type to be a server?

```# Validate 'existing' method fields
        if ($this->cert_method === "existing") {
            $this->__validate_crt();
            $this->__validate_prv();
            $this->validated_data["type"] = "server";
        }
```

in pfSense's GUI, when importing a certificate, it has no type at all. When I remove this line from your code and send the request, the certificate is created without a type as well. 
Why is this line needed?

**Affected Endpoints:**
/api/v1/system/certificate

**Comment by jaredhendrickson13** [comment]
This endpoint was originally developed on pfSense 2.3 years ago. Certificates types were used a little differently back then and the original endpoint was only intended to set the certificate used by the webConfigurator. 

Nowadays, you're right. There likely is no need for the certificate type at all and it could be removed. Although having it shouldn't cause any functional difference. A PR to the `legacy` branch is welcome.
