### ISSUE TITLE
Command pfense-restapi update says that there is no update available

### ISSUE THREAD

**Issue by lapf10** [jaredhendrickson13/pfsense-api#555]
Hi,

I have seen that a new version has been released, however when I try to update using the `pfense-restapi update` command it says that there is no update available.
What am I doing wrong? Can you help?

**Screenshots or Response**
![imagem](https://github.com/user-attachments/assets/a561866f-9065-4d4c-993e-25e8879f4d9d)

**pfSense Version & Package Version:**

- pfSense Version: 2.7.2
- Package Version: 2.0_3

**Comment by jaredhendrickson13** [comment]
Thanks for reporting. This looks like a bug, I can reproduce this from v2.0.3 to v2.1.0. The version comparison is not returning a value in the format the package is expecting so it always assumes there is no update available. I'll work on a patch.

In the meantime, there are three different options you can still use to update:

1. Apply the update from the System > REST API > Updates page.
2. Run `pfsense-restapi revert v2.1.0` from the command line.
3. Delete the existing package with `pfsense-restapi delete` and reinstall it from scratch using the install command in the documentation.

**Comment by lapf10** [comment]
now the version value returning correct.

![imagem](https://github.com/user-attachments/assets/33b69f9a-8e79-4a32-8b87-788ec69f1ffd)
