### ISSUE TITLE
Installation Error - PHP ERROR Type 64

### ISSUE THREAD

**Issue by AubreyKloppers** [jaredhendrickson13/pfsense-api#556]
**Describe the bug**
Installation using instructions do not succeed.  

**To Reproduce**

1. pkg-static -C /dev/null add https://github.com/jaredhendrickson13/pfsense-api/releases/latest/download/pfSense-24.03-pkg-RESTAPI.pkg
2. Fetching pfSense-24.03-pkg-RESTAPI.pkg: 100%  783 KiB 801.8kB/s    00:01
Installing pfSense-pkg-RESTAPI-2.1...
Extracting pfSense-pkg-RESTAPI-2.1: 100%
Saving updated package information...
done.
Loading package configuration... done.
Configuring package components...
Loading package instructions...
Custom commands...
Menu items... done.
Writing configuration... done.
<pre style="white-space: pre-wrap;">PHP ERROR: Type: 64, File: /usr/local/pkg/RESTAPI/Validators/NumericRangeValidator.inc, Line: 23, Message: Cannot use float as default value for parameter $maximum of type int</pre><pre style="white-space: pre-wrap;">PHP ERROR: Type: 64, File: /usr/local/pkg/RESTAPI/Validators/NumericRangeValidator.inc, Line: 23, Message: Cannot use float as default value for parameter $maximum of type int</pre><pre style="white-space: pre-wrap;">PHP ERROR: Type: 64, File: /usr/local/pkg/RESTAPI/Validators/NumericRangeValidator.inc, Line: 23, Message: Cannot use float as default value for parameter $maximum of type int</pre><pre style="white-space: pre-wrap;">PHP ERROR: Type: 64, File: /usr/local/pkg/RESTAPI/Validators/NumericRangeValidator.inc, Line: 23, Message: Cannot use float as default value for parameter $maximum of type int</pre><pre style="white-space: pre-wrap;">PHP ERROR: Type: 64, File: /usr/local/pkg/RESTAPI/Validators/NumericRangeValidator.inc, Line: 23, Message: Cannot use float as default value for parameter $maximum of type int</pre><pre style="white-space: pre-wrap;">PHP ERROR: Type: 64, File: /usr/local/pkg/RESTAPI/Validators/NumericRangeValidator.inc, Line: 23, Message: Cannot use float as default value for parameter $maximum of type int</pre>pkg-static: POST-INSTALL script failed

**Expected behavior**
Package installed successfully. 

**Screenshots or Response**
PHP ERROR: Type: 64, File: /usr/local/pkg/RESTAPI/Validators/NumericRangeValidator.inc, Line: 23, Message: Cannot use float as default value for parameter $maximum of type int

**pfSense Version & Package Version:**

- pfSense Version: 24.03-RELEASE (arm)]
- Package Version pfSense-24.03-pkg-RESTAPI.pkg

**Comment by jaredhendrickson13** [comment]
Is this on a Netgate 3100? If so, see #502. The v2 package currently isn't supported on 32-bit architectures.

**Comment by AubreyKloppers** [comment]
Thank you.  32bit worked...
