### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by Joenny-stack** [jaredhendrickson13/pfsense-api#568]
**Describe the bug**
I tried to install the package command line: and it gave me the followingwhen I try to access the IP : Parse error: syntax error, unexpected ':', expecting ')' in /etc/inc/priv/restapi.priv.inc on line 21 

**To Reproduce**

1. Go to pfsense command prompt, paste the following to install package pkg-static add https://github.com/jaredhendrickson13/pfsense-api/releases/latest/download/pfSense-2.7.2-pkg-RESTAPI.pkg, 
2. Edit link to leave it like this for an earlier version : pkg-static add https://github.com/jaredhendrickson13/pfsense-api/releases/latest/download/pfSense-2.7-pkg-RESTAPI.pkg and execute command
3. See error

**Expected behavior**

**Screenshots or Response**
![image](https://github.com/user-attachments/assets/61d991a2-221f-42cc-b25b-f54d97bb1a53)

**Comment by jaredhendrickson13** [comment]
The error suggests you have an old version of PHP. What version of pfSense are you using?

**Comment by Joenny-stack** [comment]
Unfortunately I can't verify the version now I am locked out of the web interface.

How can I rectify this.

**Comment by jaredhendrickson13** [comment]
You'll need either console access or an SSH session. Once you have a command line, removing this file
should allow you back in the UI:

```
rm /etc/inc/priv/restapi.priv.inc
```

Then you can run this command to remove the package from the system:

```
pkg-static delete pfSense-pkg-RESTAPI
```

**Comment by Joenny-stack** [comment]
Thank you

Which pfsense ce version is compatible with the api?

**Comment by jaredhendrickson13** [comment]
Currently, the latest version of the API only supports [pfSense CE 2.7.2](https://pfrest.org/INSTALL_AND_CONFIG/#supported-pfsense-versions). 

Development on this package typically follows the latest CE and Plus releases only so older versions lose support pretty quickly after new pfSense releases.
