### ISSUE TITLE
Issue with Preshared key - Always says invalid

### ISSUE THREAD

**Issue by sudheeshb** [jaredhendrickson13/pfsense-api#581]
Describe the bug

Getting the following error when I tried to post/patch for the URL https://mypfsense.org/api/v2/vpn/wireguard/peer' 

response_id":"WIREGUARD_PEER_PRESHAREDKEY_INVALID","message":"Field `presharedkey` must be a valid WireGuard pre-shared key

To Reproduce

Make a POST request to /api/v2/vpn/wireguard/peer with presharedkey set to null or an empty string. You will get a WIREGUARD_PEER_PRESHAREDKEY_INVALID error. 

See the code snippet below. 

peer_params =
{'id': '20', 'enabled': True, 'tun': 'tun_wg20', 'endpoint': 'valid_ip_address', 'port': '51820', 'descr': '', 'persistentkeepalive': None, 'publickey': 'validkey=', 'allowedips': [{'parent_id': '20', 'id': 0, 'address': '0.0.0.0', 'mask': 0, 'descr': ''}], 'presharedkey': ' ', 'name': 'tun_wg20'}

url = 'https://mypfsense.org/api/v2/vpn/wireguard/peer' 
out = requests.post(url, json = peer_params, verify=True, headers=headers)

This will produce an error like below.

response_id":"WIREGUARD_PEER_PRESHAREDKEY_INVALID","message":"Field `presharedkey` must be a valid WireGuard pre-shared key

Expected behavior

Empty strings should be allowed by the Model

pfSense Version & Package Version:

    pfSense Version: 2.7.2 CE
    Package Version v2.1.3

Affected Endpoints:

    URL: /api/v2/vpn/wireguard/peer

**Comment by jaredhendrickson13** [comment]
Thanks for reporting. I'll have a fix for this in v2.2.0. Should be out later tonight.

**Comment by sudheeshb** [comment]
Thanks for the quick feed back.  Also appreciate your effort for building such us a useful tool which helps in automation!.  Waiting for the fix.
