### ISSUE TITLE
An option control which are the sensitive fields in a configurable matter

### ISSUE THREAD

**Issue by Coffee-Processing-Unit** [jaredhendrickson13/pfsense-api#582]
Firstly, thank you for the new 2.2.0 version and for adding the use_tls field.
 
**Background**
This feature request is related to the recently added expose_sensitive_fields pfSense REST API setting.
The sensitive fields setting replaced some of the "write_only" setting, and now some of the fields that weren't previously exposed can be optionally exposed.
 
**Feature description**
I request an option to control which fields are expose_sensitive_fields in a configurable matter.
That is, without requiring to change the code. 
The reason is not to have only all-or-nothing option - to enable part of the sensitive fields to be read.

**Describe the solution you'd like** 
A solution I thought about is to add a "exclude_from_sensitive_fields" field in the RESTAPI xml configuration file. The format of values in this field will be "<field_model>_<field_name>" for example.
 
I am looking forward to your thoughts and solutions.

**Comment by jaredhendrickson13** [comment]
I like your solution. That shouldn't be too difficult to implement either. I'll see if I can get this working without making too many changes. Should be able to include it in the patch if that's the case.

Thanks!

**Comment by Coffee-Processing-Unit** [comment]
Thank you!
when is the

**Comment by jaredhendrickson13** [comment]
I should be able to have the patch out sometime next week. I've unfortunately had limited time available this month.
