### ISSUE TITLE
IPSEC VPN Automatic Based on Content option on  myid_type and peerid_type

### ISSUE THREAD

**Issue by mdepedrof** [jaredhendrickson13/pfsense-api#584]
In IPSec VPN Phase1 to identify peers in Gui I have the option to specify a String "Automatic Based on Content". Unfortunely i cant find this option in REST API
![image](https://github.com/user-attachments/assets/c1d22503-5009-4db7-a1eb-0b11abfb6fc6)

**Describe the solution you'd like**
Maybe add to de array the opcion "content" to match with te gui opption on myid_type and peerid_type

In gui I have this:
![image](https://github.com/user-attachments/assets/d9be00b5-77e3-4a8e-a64d-4d9915556940)

**Comment by mdepedrof** [comment]
While searching in the gui I have seen that the option I am talking about is marked as “auto”. Could this option be added in the Array of the peerid and peerid_type?

![Captura de pantalla 2024-10-18 180617](https://github.com/user-attachments/assets/1e2bcce7-5ccf-4a5f-91da-72829086b53f)

**Comment by mdepedrof** [comment]
Is this posible? Thanks for your work!

**Comment by jaredhendrickson13** [comment]
It's likely all that needs to be done is add `auto` to the list of choices for that field, if that's the case that can be put in the next patch. I'll have to look at the pfSense codebase to be sure though, sometimes these types of values don't directly relate to its config value and get expanded into different field values.

**Comment by jaredhendrickson13** [comment]
Confirmed that's all that's needed for this. I'll have the changes included in the next patch which should be out this week.

Thanks!

**Comment by mdepedrof** [comment]
Thanks for your work. Awesome!
