### ISSUE TITLE
v2.2.0 Documentation on Netgate 4200 gives "Failed to load API definition."

### ISSUE THREAD

**Issue by war59312** [jaredhendrickson13/pfsense-api#585]
**Describe the bug**
v2.2.0 Documentation on Netgate 4200 gives "Failed to load API definition."

That is /api/v2/documentation gives "Failed to load API definition." on v2.2.0.

Rolled back to v2.1.3 and /api/v2/documentation loads correctly once more.

**To Reproduce**

1.) Upgrade from v2.1.3 to v2.2.0 via System > REST API > Updates

2.) Try and view System > REST API > Documentation, now get the "Failed to load API definition." error.

3.) Roll back to v2.1.3 on System > REST API > Updates

4.) System > REST API > Documentation now loads correctly once more.

**Expected behavior**
I expect for System > REST API > Documentation to still work when on v.2.2.0.

**Screenshots or Response**
![image](https://github.com/user-attachments/assets/0986007e-9da3-4a40-b2f8-6a618e37354d)

**pfSense Version & Package Version:**

- pfSense Version: 24.03-RELEASE
- Package Version: v2.2.0 / v2.1.3

**Comment by jaredhendrickson13** [comment]
The OpenAPI schema path changed in v2.2.0, looks like your browser may still have the Swagger config with the old path cached. Try clearing your browser cache and see if it loads correctly afterward.

**Comment by war59312** [comment]
Got you, indeed. :)

Can fix this by setting `Cache-Control: no-store, no-cache, must-revalidate`

**Comment by jaredhendrickson13** [comment]
I'll consider this resolved since this path shouldn't change again in the future.
