### ISSUE TITLE
API for updating System/API/Settings

### ISSUE THREAD

**Issue by degas2226** [jaredhendrickson13/pfsense-api#59]
Hi Jared,
It is great if you can add one api to update your plugin settings like for updating **Network Interfaces, Authentication Mode, 
JWT Expiration**.
![image](https://user-images.githubusercontent.com/9531477/103756637-b24fe000-5035-11eb-8b0f-5a73684f8ba0.png)

**Comment by jaredhendrickson13** [comment]
Hey!

Thanks for your patience, I've unfortunately not had much time to work on this project this month so I apologize for the wait. This feature should be something relatively easy to implement. I can likely have this included in the next minor update. I'll keep this marked as backlogged for now and update the issue when I start/have a pull request ready. 

Thanks again!
