### ISSUE TITLE
Add "Automatic Based on Content" option on ipsec myid_type and peerid_type

### ISSUE THREAD

**Issue by mdepedrof** [jaredhendrickson13/pfsense-api#597]
In IPSec VPN Phase1 to identify peers and my side, in Gui I have the option to specify a String "Automatic Based on Content". Unfortunely i cant use this option  with ansible `pfsensible.core.pfsense_ipsec_aggregate` or `pfsensible.core.pfsense_ipsec`

**Is your feature request related to existing pfSense functionality that is missing from the API? Please describe.**
Searching in the gui (/vpn_ipsec.php), I have seen that the option I am talking about is marked as `auto`
![image](https://github.com/user-attachments/assets/e45a6926-ea5b-46b9-979f-28fbb5c3a4a2)

**Describe the solution you'd like**
the best solution would be to allow in the array of options to use the option `auto`.

**Comment by jaredhendrickson13** [comment]
This feature was already implemented in [v2.2.1](https://github.com/jaredhendrickson13/pfsense-api/releases/tag/v2.2.1). Seems like this issue was intended for a different repo?

**Comment by mdepedrof** [comment]
Oh.. Sorry!! my mistake
