### ISSUE TITLE
Wish: status OpenVPN

### ISSUE THREAD

**Issue by fbnielsen1959** [jaredhendrickson13/pfsense-api#61]
The most interesting would be from the OpenVPN server, so I can see client status (we have up to 80 clients online)

**Comment by jaredhendrickson13** [comment]
Hi again, 

I'll do a bit of research on this one and see what it would take to factor this into an endpoint. I'll provide an update when I get the chance to take a look. 

Thanks!

**Comment by itmarcanals** [comment]
Hi!
 For me in OpenVPN is interesting:
 
 - GET Lists and status of all OpenVPN Servers
 - Actions start/stop/restart
 - Optional: GET config of specific OpenVPN Server

With this i think is suficient.

Thanks and great work!!!

**Comment by OlliTheDarkness2020** [comment]
Hello,
it would also be nice if the following were possible via the API:

Create / delete servers / users.

In connection with the openvpn-client-export package, a corresponding download of the respective data of the configuration types.

Thanks very much
