### ISSUE TITLE
API stopped working under pfSense Plus 24.11

### ISSUE THREAD

**Issue by madbrain76** [jaredhendrickson13/pfsense-api#611]
**Describe the bug**
I just upgraded pfSense + to 24.11 . I can't get the API to work .

**To Reproduce**

1. Go to System / API . You get 403
2. System / Package manager doesn't list the REST API package
3. using SSH to remove the pfSense-pkg-RESTAPI-2.2.2 package, and reinstalling  https://github.com/jaredhendrickson13/pfsense-api/releases/download/v2.2.2/pfSense-24.03-pkg-RESTAPI.pkg does not solve the problem

**Expected behavior**
The API should continue to work, or there should be a new REST API package available

**Screenshots or Response**
N.A

**pfSense Version & Package Version:**

24.11-RELEASE (amd64)
built on Wed Nov 27 10:22:00 PST 2024
FreeBSD 15.0-CURRENT

**Affected Endpoints:**

All

**Comment by jaredhendrickson13** [comment]
See #610. It's being worked on, but will take a while.

**Comment by madbrain76** [comment]
Thanks. I searched the issues before I filed this one. I didn't realize it was a discussion already.

**Comment by jaredhendrickson13** [comment]
Dev builds with very basic compatibility with 24.11 are available in this [pre-release](https://github.com/jaredhendrickson13/pfsense-api/releases/tag/v2.3.0-dev-96ab4c0). This should address some of the issues seen with authentication and configuration access; and allow the package to work on a fundamental basis. There are still issues I am actively working to fix, and I'm sure there are more that I'm unable to see with my limited access to pfSense Plus. For those able to test, especially on Netgate hardware, it would be much appreciated and definitely speed up the process.
