### ISSUE TITLE
WireGuard API `/api/v2/vpn/wireguard/tunnels` endpoint returns `null` in `address` field

### ISSUE THREAD

**Issue by matiasAS** [jaredhendrickson13/pfsense-api#614]
# 🐞 **WireGuard API returns `null` in `address` field after tunnel update**

**Describe the Bug**  
When querying the WireGuard API endpoint `/api/v2/vpn/wireguard/tunnels`, the `address` field returns `null` even though the tunnel and interface are configured correctly.

---

**To Reproduce**  

1. Go to **VPN → WireGuard → Tunnels**.
2. Create or edit a tunnel with a valid configuration (e.g., description, listen port, keys).  
   **<PANTALLAZO TUNNEL REGISTRADO>**
3. Assign the tunnel to an interface (e.g., **Interfaces → Assignments**).  
   **<DETALLES INTERFACE>**
4. Configure a static IPv4 address for the interface (e.g., `10.5.5.1/24`) and apply the changes.
5. Restart the WireGuard service or pfSense.
6. Make a GET request to the WireGuard API endpoint:

   ```bash
   curl -X 'GET' \
     'http://<pfSense-IP>:23815/api/v2/vpn/wireguard/tunnels' \
     -H 'accept: application/json' \
     -H 'Authorization: Bearer <your_token>'


The response shows null in the address field.
<RESPONSE REQUEST>


**Expected Behavior**

The API should return the correct address assigned to the WireGuard tunnel, such as 10.5.5.1/24, instead of null.



**Screenshots or Response**

Tunnel Registered:
![image](https://github.com/user-attachments/assets/82889b58-daaa-4c7e-b534-cc922bb52fa9)

![image](https://github.com/user-attachments/assets/b94afd58-4c1b-41d6-a6cc-5570f2f91400)



Interface Details:
![image](https://github.com/user-attachments/assets/9a16da3e-c51f-40cc-976e-f81164550493)

API Response:
![image](https://github.com/user-attachments/assets/09343b7f-10bd-4b35-a502-aca41edf9873)

![image](https://github.com/user-attachments/assets/3596a4ad-825e-4c8e-b8fb-958ae48bcf09)

**pfSense Version & Package Version**

pfSense Version: 2.7.2-RELEASE (amd64) CE
API Package Version: 2.2.2


**Affected Endpoint**

URL: GET /api/v2/vpn/wireguard/tunnels


**Additional Context**

I am using pfSense in a virtual machine on a local network to learn how to use the API.

I would like to know if this is a bug or if I am misconfiguring something. If it is a misconfiguration, please let me know what needs to be corrected.

This issue occurs even after updating the tunnel description and restarting pfSense to force a configuration refresh. The tunnel and interface configurations appear correct in the GUI, but the API response remains inconsistent.

**Comment by jaredhendrickson13** [comment]
This behavior is normal and expected. The /api/v2/vpn/wireguard/tunnel* endpoints get their data from the `installedpackages/wireguard/tunnels` section of the XML config. However, in your example, the address is set under the `interfaces/opt2` section, not in the tunnel configuration. The `addresses` field only applies to addresses directly assigned to the tunnel object, not those assigned through an interface.

Below is where the `addresses` equivalent is in the UI:
<img width="1156" alt="Screenshot 2024-12-07 at 7 34 08 PM" src="https://github.com/user-attachments/assets/3f852740-4795-4480-b455-ca2eff55ec6e">

To view the address of your tunnel interface you would use /api/v2/interfaces in this case.

**Comment by matiasAS** [comment]
@matiasAS ok, thanks, and best regards from Chile!

**Comment by jaredhendrickson13** [comment]
That is because existing `addresses` values are still present in the config. pfSense does not remove or update existing `addresses` in the tunnel object when it is assigned to an interface, it simply ignores them and uses the address assigned to the interface instead. The UI explains this behavior a bit:

<img width="919" alt="Screenshot 2024-12-08 at 9 13 41 AM" src="https://github.com/user-attachments/assets/c7744763-2338-42e7-82ae-d3a29f37b024">
