### ISSUE TITLE
Issues when creating outbound mapping

### ISSUE THREAD

**Issue by StormYudi** [jaredhendrickson13/pfsense-api#65]
So I was trying to add outbound rules by:
https://xxx/api/v1/firewall/nat/outbound/mapping
with params:
{
    "interface": "wan",
    **"protocol": "any",**
    "src": "172.16.1.100",
    "dst": "any",
    "target": "X.X.X.X",
    "descr": "OUT",
    "top": false,
    "apply": true
}

It return :
{
    "status": "bad request",
    "code": 400,
    "return": 4089,
    "message": "Unknown outbound NAT mapping protocol",
    "data": []
}

But I want the outbound NAT match all network protocols, is that a BUG?

**Comment by jaredhendrickson13** [comment]
Hey!

Thanks for reporting this. Not sure how I missed this, but yes it appears to be a bug. `any` is not listed as a valid choice for the protocol field during input validation. Seems it is also missing the translation to the XML configurations expected value.

https://github.com/jaredhendrickson13/pfsense-api/blob/4ea75b07e9bc7d267c95cd37d098466234313a69/pfSense-pkg-API/files/etc/inc/api/models/APIFirewallNATOutboundMappingCreate.inc#L31

I'll have a fix for this available in the next patch. 

Thanks again!
