### ISSUE TITLE
Endpoint Request : Create RADIUS Auth Servers

### ISSUE THREAD

**Issue by sf32738** [jaredhendrickson13/pfsense-api#75]
Add a new remote RADIUS authentication server

Endpoint: /user/auth_server/radius
Method: POST

----
DELETE and GET (READ) already exist for this endpoint.  Missing the PUT (Create) method.

**Comment by jaredhendrickson13** [comment]
Hey!

Thanks for the request. This one will be a bit trickier to implement so it may take some time. I'll keep this issue backlogged until myself or another contributor can take a look. 

Thanks again!
