### ISSUE TITLE
Add Source/Destination Option "This Firewall (self)"

### ISSUE THREAD

**Issue by Vermill1on** [jaredhendrickson13/pfsense-api#79]
Currently the source and destination option "This firewall (self)" is missing when creating firewall rules, which can be selected in the GUI. In an API read, this is stored as follows:

```
                "destination": {
                    "network": "(self)"
                },
```
Unfortunately, I have not yet found a way to create them ({\"status\":\"bad request\",\"code\":400,\"return\":4045,\"message\":\"Invalid firewall rule destination\",).

**Comment by jaredhendrickson13** [comment]
Hey!

Good catch. If you have fix implemented for this already feel free to open a pull request and I can take a look. Otherwise I can work on this when I get the free time. 

Thanks!
