### ISSUE TITLE
KNOWN ISSUE: pkg: wrong architecture: FreeBSD:11:amd64 instead of FreeBSD:12:amd64

### ISSUE THREAD

**Issue by jaredhendrickson13** [jaredhendrickson13/pfsense-api#81]
This morning Netgate released pfSense 2.5.0. This forces all instances of pfSense 2.4.x to use the latest 2.5.0 package repos and marks the previous 2.4.x repo as deprecated, therefor breaking package installations for the FreeBSD 11 platform. From the CLI you may get this error when trying to install the API package on pfSense 2.4.x:
`pkg: wrong architecture: FreeBSD:11:amd64 instead of FreeBSD:12:amd64`

If you get this error **do not update or install any packages**! If you are planning on updating to pfSense 2.5 now, update pfSense first and then install the API for pfSense 2.5. If you are planning to stay on pfSense 2.4.x for a while, login to pfSense and navigate to System > Update and change the package repo branch to the previous 2.4.x repo:

![Screen Shot 2021-02-17 at 6 58 28 PM](https://user-images.githubusercontent.com/50180862/108297807-0e3f7580-7159-11eb-9a48-6f38714a4eb9.png)

https://www.netgate.com/blog/pfsense-plus-21-02-release-and-pfsense-ce-2-5-0-release-now-available.html

_This is not an issue specific to the API package, pfSense will no longer allow you to install FreeBSD 11 based packages until the repo is reverted to the previous stable version._

**Comment by mwoolweaver** [comment]
I assume you will be releasing 2.6 package (no eta needed)?

**Comment by jaredhendrickson13** [comment]
@mwoolweaver yes. As of right now the current 2.5 package should work for 2.6. However, future releases will include a build specifically for 2.6 to use for testing while pfSense 2.6 moves through the development process.
