### ISSUE TITLE
Bug Report - ARP Table

### ISSUE THREAD

**Issue by github59173** [jaredhendrickson13/pfsense-api#83]
ARP Table page causes crash on 2.5.0-RELEASE(clean/fresh install in vm for testing purposes)
![unknown](https://user-images.githubusercontent.com/79297055/108457144-dd2d7680-7226-11eb-8191-669777f995a8.png)
![unknown2](https://user-images.githubusercontent.com/79297055/108457145-ddc60d00-7226-11eb-8b23-84f2fb497099.png)

**Comment by jaredhendrickson13** [comment]
Thanks for reporting this issue. I've confirmed this is a bug. I will have a patch ready this weekend along with some other 2.5.0 fixes. I'll update this issue once the PR is up. 

Thanks!
