### ISSUE TITLE
Allowing duplicate DNS entries

### ISSUE THREAD

**Issue by degas2226** [jaredhendrickson13/pfsense-api#86]
Hi,

DNS Server API is allowing the duplicate entries.
This is happening when we make POST call to /api/v1/system/dns/server with already existing dns server entries.

![image](https://user-images.githubusercontent.com/9531477/108815049-cfd30c00-75d9-11eb-9667-10bfde1f8cf1.png)

Thank You,
Ashok Kumar Dega.

**Comment by jaredhendrickson13** [comment]
Thanks for reporting this issue. Luckily this doesn't seem to have any significant side effects besides being unable to make the changes on the system.php UI page until the duplicate DNS servers are removed. Regardless, I will work on a fix and update this issue once I have a PR containing the fix. 

Thanks again!
