### ISSUE TITLE
Get DNS Override ID

### ISSUE THREAD

**Issue by crimv42** [jaredhendrickson13/pfsense-api#90]
First thanks for this projects, its a huge help!

I wanted to see if maybe I missed something in the documentation, but I am trying to find a way to get the ID of a host override from the API, so that I can script/config-manage the updating/deleting of records that are added with the script. Currently it appears the endpoint to list the overrides doesn't contain that info:

```
      "host": "host1",
      "domain": "domain.com",
      "ip": "192.168.0.1",
      "descr": "DESCRIPTION",
      "aliases": ""
```
Is that something that would be possible to add?

Thanks again for this great project!

**Comment by jaredhendrickson13** [comment]
Hey! 

Thanks for reaching out, I'm glad you find value in the project! In most cases, the API will handle IDs the same way the pfSense webConfigurator does. The ID will be the array index value of the `data` field. For example:

```
curl -s -k -d '{"client-id": "admin", "client-token": "pfsense"}' -X GET https://172.16.209.9/api/v1/services/unbound/host_override | jq .
{
  "status": "ok",
  "code": 200,
  "return": 0,
  "message": "Success",
  "data": [
    # This object's ID is 0
    {
      "host": "",
      "domain": "example.com",
      "ip": "127.0.0.255",
      "descr": "",
      "aliases": ""
    },
    # This object's ID is 1
    {
      "host": "another-test",
      "domain": "example.com",
      "ip": "127.0.0.200",
      "descr": "",
      "aliases": ""
    },
    # This object's ID is 2
    {
      "host": "test",
      "domain": "example.com",
      "ip": "127.0.0.100",
      "descr": "",
      "aliases": ""
    }
  ]
}
```

Most people will typically use a loop with a counter to determine the ID of the object they are looking for. Some things to keep in mind:
- pfSense starts arrays at index 0 and increases in increments of 1
- IDs are dynamic. For example. if the object with ID 1 is deleted, ID 2 will become ID 1 as pfSense will reindex the array

There is an active effort (#41) to make API responses a more accurate representation of the request data which would include the ID in the API response, but that is likely still a ways off. In the meantime, documentation will be updated to clarify how to obtain object IDs. Let me know if you have any questions.

Thanks!

**Comment by crimv42** [comment]
Thanks for that info, that makes a lot of sense, and I should be able to work in an easy loop that does what I need with that info. 

Thanks again!
