### ISSUE TITLE
NAT Port foward: port specification doesn't allow port aliases

### ISSUE THREAD

**Issue by babs** [jaredhendrickson13/pfsense-api#91]
On pfSense 2.5 (not tested on 2.4), I'd like to use port aliases to create new port_forward as it's possible through the web interface.
While trying so, I've the following message:

        {
          "status": "bad request",
          "code": 400,
          "return": 4010,
          "message": "Invalid port forward redirect port",
          "data": []
        }

**Comment by jaredhendrickson13** [comment]
Hey!

Looking at the latest release, the port forwards endpoint does not check the input against existing aliases which explains the error you receive. You are correct, aliases are supported in port forwards on both pfSense 2.4 and 2.5. This should be a simple fix I can have included in the next patch. I plan to have a patch released by the end of this week so I should be able to squeeze this in no problem. I will update this issue once I have a PR containing the fix. 

Thanks!

**Comment by babs** [comment]
I'll give you a feedback as soon as I can test it :)

**Comment by babs** [comment]
Tested, works.
