### ISSUE TITLE
Password is not set correctly when creating new local users

### ISSUE THREAD

**Issue by joaodiogo123** [jaredhendrickson13/pfsense-api#95]
Hello,

When I create a local user via the API it seems like the password is not set correctly. At least when trying to login in the OpenVPN client, I always get the AUTH_FAILED message. Only after changing the password manually via the WebConfigurator can I login successfully.

Can someone please help me with this issue?

**Comment by danielmichaels** [comment]
I too have found this issue, as a workaround you can update that user using a POST request. It will then accept the password.

I meant to raise this issue previously - thanks @joaodiogo123 for bringing this up.

**Comment by joaodiogo123** [comment]
Thanks for the tip @danielmichaels . I'm gonna try it. It seems like something that can be easily automated, but it's a shame it's happening.

BTW, do you have a way of creating several users with one POST request? I'm trying to do it with a group of objects in JSON but I always get a "bad request" status with a "400" code and the message "Username required".

**Comment by danielmichaels** [comment]
@joaodiogo123 I have not tried to create more than one user at a time so I can't personally help you much with that question.

**Comment by jaredhendrickson13** [comment]
Hey!

@joaodiogo123 thanks for reporting this issue. I've verified this is a bug and I am currently working on a fix. Essentially the password is created _after_ the user is written to configuration, so no password is saved on the backend when the user is created. The workaround @danielmichaels mentioned is correct and will get things working in the meantime. I'll update this issue when I have a PR containing the fix. 

Thanks again!
