### ISSUE TITLE
HA Sync to sync API config and tokens

### ISSUE THREAD

**Issue by babs** [jaredhendrickson13/pfsense-api#97]
It would be nice if in case of HA setup, to have API's config synced between nodes including keys and tokens.

**Comment by jaredhendrickson13** [comment]
Hey!

This is a good idea. I'll look into it a bit to see if there's an easy way to use the built-in pfSense HA Sync function or if a custom implementation will be needed.

In the meantime, there is a fairly simple way to do this from the command line now if you need something working earlier:

1) Run `pfsense-api backup` on the master node.
2) Copy the `/usr/local/share/pfSense-pkg-API/backup.json` file from the master node to the same path on the backup node. `scp` or `rsync` should be able to do this.
3) Run `pfsense-api restore` on the backup node.
